### ISSUE TITLE
develop concept for generic engines

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1024]
This issue collects everything related to generic engines to develop an overall concept which shall then be broken down into several issues for implementation.

### Engines
- it might be possible to extend a Java interface in JS (see #983)
- JS must be asked if a certain engine is installed (see #605)

### Containers
As the containers highly depend on the engine which is using them, the container handling has to be done in JS as well. 
- container information specific for a certain engine must be loaded (see also  #477)
- the engine version used by a specific container must be updated (see #992 and #702)
- specific settings must be handled in a generic way (see #620)

**Comment by ImperatorS79** [comment]
Until this is done, you could add a simple way to update wine containers version (and distribution) (like a list of already installed wine version) an remove it when you implemented your generic engines.

**Comment by plata** [comment]
Done.
