### ISSUE TITLE
Apps aren't shown with miniature

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1055]
When doing the following the app miniatures in the "Apps" tab disappear:

1. Select the "Games" category
2. Switch the list widget to the miniature free one (the last one)
3. Select the "All" category
4. Switch back to the first list widget

The result will look like this:
![grafik](https://user-images.githubusercontent.com/18488086/29709831-3035713c-898e-11e7-9cab-7b5750da4417.png)

**Comment by plata** [comment]
I cannot reproduce this on the current master.

**Comment by ImperatorS79** [comment]
I'm using the current master.

Step to reproduce

Open Phoenicis->go to apps tab->change the way apps are displayed->cross testing->go back to the first way

![pol 5 bug](https://user-images.githubusercontent.com/19779882/29741643-738c2758-8a71-11e7-9ca3-4edd5dd06962.gif)

**Comment by plata** [comment]
Did exactly the same. Doesn't happen here.

**Comment by madoar** [comment]
Maybe it's the java version or some other part of the environment.
I'm using Oracle JDK:

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by plata** [comment]
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by ImperatorS79** [comment]
Ubuntu 17.04

`openjdk version "1.8.0_131"`
`OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)`
`OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)`

**Comment by madoar** [comment]
Ok, so it doesn't seem to be java.
I'm using Linux Mint 18.2 (based on Ubuntu 16.04)

**Comment by plata** [comment]
One of you has to debug it. I cannot investigate as I do not have the failure.

**Comment by madoar** [comment]
The problem is, you don't get an exception or any other kind of error.
Interesting is also, that a click on the filter text clear button leads to the appearance of the missing labels.

I think this may be a java glitch.

**Comment by plata** [comment]
Maybe we can just apply the filter again after switching the list type if it's really a Java problem?

You should attach a debugger to see what's really causing the issue (e.g. are the miniatures really not there or just not shown etc.).

**Comment by madoar** [comment]
I'll do some tests later.
I want to change the use of `FilteredList` to our own implementation `PhoenicisFilteredList`, maybe this will change the behavior somewhat.

**Comment by madoar** [comment]
Ok, after changing `FilteredList` to `PhoenicisFilteredList` the effect is a little bit better:
![grafik](https://user-images.githubusercontent.com/18488086/29771369-ab88eb90-8bf3-11e7-9735-409e5e5751b9.png)

**Comment by plata** [comment]
What's that :P

**Comment by madoar** [comment]
I did the same, that @ImperatorS79 did in his gif. The "missing" miniatures seem to belong to the applications that are marked as testing. I guess the css style is somehow not applied...

**Comment by madoar** [comment]
Fun fact:
This effect is only visible in the icons list (the first one), not in the compact list (the second one)...
In the compact list the icons are always shown correctly...

**Comment by plata** [comment]
@madoar any update on this?

**Comment by madoar** [comment]
No not really. I'm currently low on time to check this in more detail. 
I don't think this is a big problem currently, because it doesn't make the application unusable you just have to "clear" your search to make the miniatures show up again, therefore I would suggest to leave this as is for now.

**Comment by qparis** [comment]
Any update on this?

**Comment by plata** [comment]
Closed. Doesn't seem to happen anymore. Feel free to reopen if you experience this again.
