### ISSUE TITLE
add EnginesManager class

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1104]
Shall provide an interface to interact with engines. For now, we need `isInstalled(EngineVersionDTO)` (see #1099).

**Comment by madoar** [comment]
How do we check if an engine version is installed?
Do we check whether a specific folder exists or do we call a javascript function?

**Comment by plata** [comment]
We should call a javascript function. Actually it exists already: `Wine#installed()`.

**Comment by madoar** [comment]
This seems to be engine specific. Can we do this in an engine independent way?

**Comment by plata** [comment]
I'm not sure. However, it doesn't really matter for this issue. As long as the `EnginesManager` provides the functionality, it's fine. We can always change the internal implementation later on.

**Comment by plata** [comment]
fixed in #1298
