### ISSUE TITLE
rename repository to "phoenicis"

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1126]
I propose to rename the repository from "POL-POM-5" to "Phoenicis" to better reflect that it is one software which is released in different flavors (PlayOnLinux and PlayOnMac). 
Moreover, we might eventually release Phoenicis 6 etc., so it doesn't make a lot of sense to have the version number in the repository name.

**Comment by madoar** [comment]
I think this is a good idea, **but** we should do this after we've created the phoenicis website and after we've given the people a little bit of time to adjust to the software and the name.
I believe that the repository name is currently the main thing that let's the people see that this repository ties in with play on linux / play on mac.

**Comment by plata** [comment]
I'd rather do the exact opposite: rename it now before anyone got used to the current name.

**Comment by aaronfranke** [comment]
I agree with @madoar, most people don't know what "Phoenicis" is and it's important to let them know that it is actually PlayOnLinux/PlayOnMac 5.

**Comment by plata** [comment]
That's true for sure. However, I doubt that it makes sense to do this via the repository name. In my opinion, the new website should make this clear. So if you go to the website and then to GitHub from there, it will rather be confusing if the repository is called "POL-POM-5" after the website explained you that it's name is "Phoenicis".

**Comment by plata** [comment]
@qparis @madoar any objections against the renaming? I would like to do it now before we release alpha. Hopefully, alpha leads to more people trying Phoenicis and I don't want to explain to them where the "POL-POM-5" repository is gone suddenly.

**Comment by aaronfranke** [comment]
Will the alpha release be accompanied by announcements about the name change? If so, I support it.

**Comment by plata** [comment]
@aaronfranke yes, we will have to explain the new name anyways. The GitHub organization is called "PhoenicisOrg", the website is phoenicis.org, the software is called like this already so renaming the repository is just the last missing bit.

**Comment by madoar** [comment]
I'm fine with renaming the repository

**Comment by plata** [comment]
Done.
