### ISSUE TITLE
Runtime dependencies

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1151]
When using Phoenicis 5 with wine it requires some additional dependencies to work correctly (see also https://github.com/PhoenicisOrg/Scripts/pull/468).
For example, if you want to have sound in wine you need to have the following packages installed:
- lib32-alsa-plugins 
- lib32-libpulse 
- lib32-openal

The point here is, that these required packages depend on the kind of scripts you want to execute. If for example you want to use a Scrumm script, or a DosBox script, I don't think they are needed.

To solve the problem of missing runtime dependencies, I propose the introduction of **runtime dependency profiles**:
Every script type can define their own runtime profile, i.e. wine scripts can define a wine dependency profile.
When the user installs a script or during the installation (or first start) of Phoenicis 5 the application checks if the user has the required profile installed/enables, if this isn't the case he is asked if he wants to enable it.
When enabling a profile Phoenicis 5 will try to install all dependencies belonging to the profile.
This installation process may require additional root permissions, which need to be entered when activating a profile.

**Comment by plata** [comment]
I would prefer to install all dependencies (even if they might never be needed) during installation of e.g. the .deb. We cannot (and should not) assume that a user of Phoenicis can get root permissions during runtime.
Does anyone know how this was handled in PoL/PoM 4?

**Comment by madoar** [comment]
> I would prefer to install all dependencies (even if they might never be needed) during installation of e.g. the .deb.

Let's assume that we (PoL 5) support multiple "platforms", like wine, dosbox and scrumm, but I, as the user, only want to use/run wine scripts.
Wouldn't your approach force me to download and install a lot of dependencies, that I don't need? 
These additional unnecessary dependencies can also take a lot of free disc space, which is problematic for systems with limited disc space. 

> We cannot (and should not) assume that a user of Phoenicis can get root permissions during runtime.

Why? 
I mean other applications also may require root permissions during runtime. 
For example, 2 or 3 weeks ago I installed steam on my linux system, during the first start the steam updater opened a terminal to tell me it requires me to install some additional dependencies to make steam run on my machine. After agreeing to this prompt it asked me for root permissions.
I don't see a reason why we shouldn't do the same?

> Does anyone know how this was handled in PoL/PoM 4?

I have no clue.

**Comment by plata** [comment]
> Wouldn't your approach force me to download and install a lot of dependencies, that I don't need?

Yes. But I doubt that it will be "a lot". Moreover I don't think that those dependencies will require a lot of disc space.

There's one big difference compared to Steam: Steam asks you on first run. So once it is setup, you can use it without root permissions. With the approach you've suggested, however, you might need root permissions at any given point in time. This effectively prevents that a user without root permissions can install applications in Phoenicis (in general).

**Comment by qparis** [comment]
In POLv4, we strictly forbid any action that would require root permission. The program will just scan the system and alert the user to install any required dependencies; but at the end, it is up to him to install them. It also ensure that the code stay portable accross distributions

**Comment by madoar** [comment]
@qparis how is the system scanned?
I mean isn't this kind of distribution dependent?

@plata I didn't mean to force the user the user to install the dependencies.
I'm more or less thinking about a button, which the user can press, that checks the system for the dependencies linked to the selected profile (i.e. wine).
Afterwards a small dialog should be opened which shows the user in a list which libraries are installed (maybe through color coding?).
In addition this dialog should contain two buttons at the end:
- an `install` button. This button would open a terminal, with the system dependent command to install the missing libraries
- an `close` button. This button would simply close the dialog and do nothing else

The whole feature is not meant to be mandatory for the user, just an optional service which he can use to check if all possibly required libraries are installed.

**Comment by qparis** [comment]
There are plenty of operation that can be done independently: 
* Check that a given binary exists
* Check that the system supports direct rendering (https://github.com/PlayOnLinux/POL-POM-4/tree/master/src) 
* Check the version of different programs 
* Check that the filesystem used is compatible
* etc...

**Comment by plata** [comment]
@madoar I see. There's another big problem I see here: If we want the dependencies per script, everybody who commits a script would have to somehow check the runtime dependencies which is not trivial at all.

I see some possibilities:
1. We define the dependencies per script (I believe this is difficult to maintain and rather error prone).
2. We define the dependencies on engine level.
3. We install the dependencies with the .deb (won't work for engines which we don't know).
4. We just add the known problems and solutions to a FAQ on phoenicis.org.

**Comment by madoar** [comment]
I agree with you.
The question is for which solution should we go?
I guess the easiest one would be installing everything with the `.deb` file, with the disadvantage that we may install a lot of dependencies we don't want.
The second easiest solution is to define everything in a FAQ.
The hardest solutions are defining them on the script and engine level.
I don't think it's feasible to define them on the script level, because at least some script designers (myself included) don't really know which system libraries are required for what.
Therefore I think it makes more sense to use the engine level to define the possible dependencies for an engine type.

For the beginning I think we should go for the third and fourth choice. The fourth choice is especially important for all users that can't use a `.deb` installer.
Later on I would like to do a more generic solution, i.e. the second choice.

**Comment by plata** [comment]
Ok, then lets go for the FAQ once the website is ready.

**Comment by ekultails** [comment]
Both DEB and RPM packages support "suggests" for optional suggested dependencies. These do not get installed by default unless a special flag is given to the package manager to install all of the suggested dependencies.

https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-depends
https://fedoraproject.org/wiki/Packaging:WeakDependencies

No matter what, for the grand audience, a FAQ about this entire discussion is a must. If a list of useful, and not necessary, dependencies could be made then those could also be additions to the packages as optional dependencies.

**Comment by plata** [comment]
Do you think we should collect the dependencies in the wiki on GitHub until the website is ready?

**Comment by ekultails** [comment]
That sounds like an excellent idea. I constantly reference the GitHub Wiki for information on how to setup and use Phoenicis (and honestly I have not ported over my PlayOnLinux 4 scripts to it yet).

Off the top of my head, I don't know what all of the dependencies we would be recommending outside of what was already mentioned at the beginning of this discussion. Specifically, 32-bit dependencies of common libraries used in Wine would be great to mention.

These might help point us in the right direction initially:

* https://wiki.archlinux.org/index.php/Wine
* https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/wine
* https://src.fedoraproject.org/rpms/wine/blob/master/f/wine.spec

 I imagine this will be an evolving list on the Wiki.

**Comment by plata** [comment]
@madoar if I remember correctly, you've been the one who ran into the problem of missing dependencies. Could you add a page to the scripts wiki?

**Comment by plata** [comment]
@ekultails I really encourage you to port your scripts. It's super easy to write scripts for Phoenicis.

**Comment by plata** [comment]
I think we should close this. On the one hand, we have flatpak which precisely defines the environment. On the other hand, we have an issue for the website to list possible dependencies as well.
