### ISSUE TITLE
use Travis to release via Launchpad PPA

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1165]
see
* https://docs.travis-ci.com/user/deployment/launchpad/
* https://askubuntu.com/questions/71510/how-do-i-create-a-ppa

**Comment by madoar** [comment]
When do you think we should approach this issue?

**Comment by plata** [comment]
When we decide that
1. we want to publish our own PPA (I think, we do)
2. we want to publish the PPA on Launchpad

**Comment by madoar** [comment]
Is there a good alternative to Launchpad?

**Comment by plata** [comment]
Not that I know. You can use any webserver to provide a repository (currently it is http://deb.playonlinux.com) but I think a PPA on Launchpad is the "standard" way to do this.

**Comment by plata** [comment]
Do we want to maintain packages on Launchpad? It's probably quite some work and has we have the flatpak it might make sense to use that.

**Comment by plata** [comment]
@qparis we will build the release packages manually, correct? So I will close this.
