### ISSUE TITLE
add build instructions for OSX to GitHub pages

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1203]

**Comment by madoar** [comment]
In addition I think we should add a maven plugin to automatically build a `dmg` installer for OSX.

**Comment by plata** [comment]
Fine for me. My problem is I don't have OSX here so I can't do nothing about it.

**Comment by madoar** [comment]
I think we should be able to use https://github.com/federkasten/appbundle-maven-plugin for the creation of a `dmg` installer, but you're right someone using OSX should do this.

**Comment by atilling** [comment]
I have OSX and I can provide feedback. Also a java developer of sorts myself.

**Comment by plata** [comment]
That would be great! Do you know where to add it/how to build the GitHub pages locally? If not, I can provide you some guidance there.

In general if you're willing to provide code for Phoenicis or contribute in any other way, you're very welcome to join us.

**Comment by atilling** [comment]
I know how to checkout and build from Github and Maven - I do contribs to some public projects as well as Java projects in my job. I haven't looked into this particular maven plugin but I will.

**Comment by plata** [comment]
Ok.

Just in case:
1. go to `docs`
2. change the page (in this case `_docs/Users/build.md`)
2. run `bundle exec yekyll serve`
3. check the website (usually `127.0.0.1:4000`)

**Comment by atilling** [comment]
Cloned the repo and built. Built fine now. Just my eclipse isn't liking gettext for some reason.

**Comment by plata** [comment]
@atilling have you been able to compile by now? If so, would be great if you could provide a pull request with the description for OSX so we can close this.
