### ISSUE TITLE
Check compatibility with Java 10

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1205]
Now that Java 10 is released (see also: http://jdk.java.net/10/), we need to check that Phoenicis POL/POM 5 is compatible to Java 10.

Travis doesn't support Java 10 yet (see also: https://github.com/travis-ci/travis-ci/issues/9368), so I think we'll need to wait until then.

**Comment by plata** [comment]
It's not so urgent, even Java 9 didn't really hit the road yet.

**Comment by madoar** [comment]
Yes.
I just thought I would add a new issue for this, before I forget about the Java 10 release ;)

**Comment by plata** [comment]
Sure.

**Comment by plata** [comment]
Java 10 + 11 is built in Travis.
