### ISSUE TITLE
Create a downloadable .deb please

### ISSUE THREAD

**Issue by TriMoon** [PhoenicisOrg/phoenicis#1206]
To have more people test this POL5 version you should create an downloadable/installable .deb package.
I'm interested in a 64bit version for Debian 9.4 :wink:

**Comment by plata** [comment]
We will only do this for releases. Currently we are still pre-alpha so there will not be a .deb of the development software.
However, you can build a .deb for yourself (should be quite easy by following the [wiki](https://github.com/PhoenicisOrg/POL-POM-5/wiki/Build)).

**Comment by TriMoon** [comment]
I didn't ask for a specific stable debian version.
Debian has special branches for all software stages including pre-alpha, fe. testing, sid etc.
eg. you can even make automated nightly deb's...

Re your last line see OP...If i wanted to build it myself i would not have posted this.

**Comment by plata** [comment]
Well, in fact Travis is building the .deb. It's just not uploaded somewhere right now. We can upload releases with GitHub releases but that doesn't make sense for nightlies (in my opinion). So what we would need is some place where we can upload the build artifacts (for free).

**Comment by TriMoon** [comment]
First of all i'm not a package developer, that said i suggest you to read some of these:

- [Debian: devel/#workinprogress](https://www.debian.org/devel/#workinprogress)
- [Debian wiki: MemberBenefits](https://wiki.debian.org/MemberBenefits)
You're not the only free software developer with these issues 😉

**Comment by plata** [comment]
Thanks for the input. I will have a look. In general, we're a bit low on manpower so really maintaining packages for several distributions will most probably be above our capabilities. I could imagine that we'll rather go for snap/flatpak in the end.

**Comment by LyzardKing** [comment]
If travis is building the deb it could be uploaded to the github releases, tagged as a dev build

**Comment by plata** [comment]
@LyzardKing we can consider that. I'm not sure that this makes sense, though (see my comment above). The currently uploaded deb is for alpha which actually is a release, so it makes sense to have it there.

**Comment by plata** [comment]
Closed as alpha release is available from GitHub releases.
