### ISSUE TITLE
Themes: sidebarTitle and sidebarButton text color not correct

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1277]
Must use

```CSS
.text {
    -fx-fill: white;
}
```

**Comment by madoar** [comment]
How exactly is the color not correct?
Can you please provide a screenshot, i.e. before vs. after.

**Comment by plata** [comment]
Currently, the themes use `-fx-text-fill`. This doesn't seem to work (with Less?). I noticed it when I worked on the Mint-X theme. The color is simply not used (i.e. you can put whatever color you want to `-fx-text-fill` and it will just keep the default text color.

**Comment by plata** [comment]
That's strange: `-fx-text-fill` works for the dark theme but not for the others.
