### ISSUE TITLE
Conflict when different openjdk versions are installed

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis#1304]
### Expected behavior
It's more a question I'm asking
### Actual behavior
When openjdk-11 is installed alongside openjdk-8 on ubuntu 18.04, and phoenicis is built with openjdk-8, phoenicis failed to launch with
```
Error : impossible to find or load the main class org.phoenicis.javafx.JavaFXApplication
Caused by : java.lang.NoClassDefFoundError: javafx/application/Application
```
### Steps to reproduce
Have both openjdk-jre 11 and 8 installed, build phoenicis with openjdk-8-jdk one and try to launch it
### System information
* ded3f97725ad3f4579626c6d17bb7ae8ba671555
* Ubuntu 18.04
* openjdk-8

**Comment by plata** [comment]
How did you run Phoenicis (i.e. which script did you use)?. This sounds like a problem with the classpath.

**Comment by madoar** [comment]
I think this may be linked to #1214

**Comment by madoar** [comment]
Yes, I think this is a possibility

**Comment by plata** [comment]
Can we improve `phoenicis.sh` such that it uses the correct JDK/JRE version?

**Comment by madoar** [comment]
I don't think so.
My guess is, that maybe OpenJDK 10 and 11 use a different (newer) OpenJFX version, which is not installed.
I think it's more a system configuration problem, than a Phoenicis problem.

@ImperatorS79 do other self built JavaFX applications work?

**Comment by ImperatorS79** [comment]
I do not have any other OpenJFX apps.

**Comment by plata** [comment]
You can try with https://docs.oracle.com/javase/8/javafx/get-started-tutorial/hello_world.htm.

**Comment by ImperatorS79** [comment]
Could you give me a link about how to build it ? My knowledge of java is only `mvn clean package`^^.

**Comment by plata** [comment]
```
javac HelloWorld.java HelloWorld.class
java HelloWorld
```

**Comment by ImperatorS79** [comment]
I got : `javac : invalid flag : HelloWorld.class`

**Comment by plata** [comment]
Ok... and only `javac HelloWorld.java`?

**Comment by ImperatorS79** [comment]
Works, but then `java HelloWorld` gives `Error : cannot find or load main class of HelloWorld`

**Comment by ImperatorS79** [comment]
Same error

**Comment by plata** [comment]
Can you try https://github.com/zonski/hello-javafx-maven-example?

**Comment by ImperatorS79** [comment]
After `mvn clean compile jfx:package`
```
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:1.2:package (default-cli) on project hello-javafx-maven-example: Execution default-cli of goal com.zenjava:javafx-maven-plugin:1.2:package failed: An API incompatibility was encountered while executing com.zenjava:javafx-maven-plugin:1.2:package: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
```

**Comment by plata** [comment]
@madoar any ideas?

**Comment by madoar** [comment]
@ImperatorS79 what version of maven are you using?
It is possible, that the used maven plugin requires a newer version of maven.

**Comment by plata** [comment]
Regardless of the maven example: why can't the simple `HelloWorld` example be compiled?

**Comment by ImperatorS79** [comment]
[https://packages.ubuntu.com/bionic/maven](https://packages.ubuntu.com/bionic/maven )->maven (3.5.2-2)

**Comment by plata** [comment]
We really should not focus on maven here.

I just tried the following minimal JavaFX example:
```Java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Test extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override 
    public void start(Stage stage) {        
        stage.setTitle("Hello World!");
        stage.show();
    }

}
```
Save as `Test.java`, then compile with `javac Test.java` and run with `java Test`.

If that doesn't work, your problem is really a general configuration issue.

**Comment by ImperatorS79** [comment]
works with openjdk8 alone, but when openjdk11 is installed alongside, I got this : 
```
Test.java:1: error: package javafx.application does not exist
import javafx.application.Application;
                         ^
Test.java:2: error: package javafx.scene does not exist
import javafx.scene.Scene;
                   ^
Test.java:3: error: package javafx.stage does not exist
import javafx.stage.Stage;
                   ^
Test.java:5: error: cannot find symbol
public class Test extends Application {
                          ^
  symbol: class Application
Test.java:12: error: cannot find symbol
    public void start(Stage stage) {        
                      ^
  symbol:   class Stage
  location: class Test
Test.java:8: error: cannot find symbol
        launch(args);
        ^
  symbol:   method launch(String[])
  location: class Test
Test.java:11: error: method does not override or implement a method from a supertype
    @Override 
    ^
7 errors
```
BTW on ubntu 18.04, openjfx version is 8u161 -> [https://packages.ubuntu.com/bionic/openjfx](https://packages.ubuntu.com/bionic/openjfx)

**Comment by plata** [comment]
Ok. Then it seems to be clear that it doesn't find JavaFX. Can you try to add the path to `phoenicis.sh`:
```
CLASSPATH=<path to  jfxrt.jar>:${CLASSPATH}:$POL_HOME/lib/*
```
The path is probably `/usr/share/java/openjfx/jre/lib/ext/jfxrt.jar`.

**Comment by ImperatorS79** [comment]
I used `CLASSPATH=/usr/share/java/openjfx/jre/lib/ext/*:${CLASSPATH}:$POL_HOME/lib/*`
and got : 
`Error: JavaFX Runtime Components Required to Run This Application are missing`

**Comment by plata** [comment]
Do you have a jfxrt.jar in that path?

**Comment by plata** [comment]
As this is really similar to #1335, I will close this issue (I want to avoid discussing the same stuff twice).
