### ISSUE TITLE
generic engine settings for a container

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1309]
Currently, the engine settings for a container (GLSL etc.) are implemented specifically for Wine in Java. We need a generic way to implement this in Javascript with a Java interface.

Rough idea:
Java interface `EngineSetting` with the methods:
* `String[] getOptions()`
* `String getCurrentOption()`
* `void setOption(String container, String option)`

Affected classes:
* `WinePrefixContainerDisplayTab`
* `WinePrefixContainerController`
* `org.phoenicis.containers/wine/**`, `WinePrefixContainerDTO` (should be deleted)

Open questions:
* How to handle translations? The options may not be translated when they are passed to/from Javascript but shall be translated in the GUI.

**Comment by madoar** [comment]
What exactly should these methods of the new interface `EngineSetting` do? 
What do the Strings contains?

Can you create a prototype implementation of the changes?

**Comment by plata** [comment]
For example: we would have a setting called `DirectDraw renderer`. It's `getOptions` would return `["default", "gdi", "opengl"]`. These would be used to fill a combobox. The selected entry of the combobox is returned to Javascript via `setOption`. The Javascript setting implementation would then change the registry accordingly.
