### ISSUE TITLE
JEP 335: Deprecate the Nashorn JavaScript Engine

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1352]
After checking the JEPs on http://openjdk.java.net/jeps/0, I've stumbled over JEP 335, which suggests to deprecate the nashorn javascript engine.

As of now this is just an idea, which is discussed on the jdk-dev newsletter, found at http://mail.openjdk.java.net/pipermail/jdk-dev/2018-June/thread.html.

The issue seems to be, that the maintainers of nashorn regard it as difficult/challenging to maintain with the (lously cited) "rapid pace at which ECMAScript language constructs are adapted and modified".

Therefore they suggest to first deprecate the corresponding packages, and later remove them from the JDK.

What are our longterm options:
- first, we can ignore the whole issue for now. The earliest, Nashorn can be deprecated is Java 11.
   This means, that Nashorn can be removed at the earliest in Java 12, which is still in the future.

   In addition it is also possible, that "the community" will continue the development of Nashorn.
- our second solution would be to switch from Nashorn to some other JavaScript engine available for Java.
   The problem here is, that as far as I know no alternative is production ready as of now.
   
   Alternatives in development I know of are GraalVM ([Graal.js](https://github.com/graalvm/graaljs)) and [Project Detroit](http://mail.openjdk.java.net/pipermail/announce/2018-January/000243.html)
- another solution would be to switch from JavaScript to another (scripting) language. 

   The disadvantages of this solution is, that it would require the most work and the new language may be harder to learn for possible script developers.
   In addition I'm not sure if this is a good idea at our current development status (especially when we're currently planning to release an alpha version).

   The advantage of this solution is, that there are some other language which have a better integration with Java than Nashorn JavaScript (jython for example).

**Comment by plata** [comment]
As you said, this will not happen any time soon. We should really not spend our time thinking about something that might or might not come. Even if they decide to drop it, Java versions supporting it will be around for years.
Therefore I suggest to close this issue and discuss the topic again if it's required.

**Comment by madoar** [comment]
I don't think we should close this.
It seems to be official now: Nashorn will be marked as deprecated in Java 11 (see [here](http://openjdk.java.net/projects/jdk/11/)).
I believe we should check alternatives as early as possible.
The earlier we check alternatives, the less code we need to migrate later on.

**Comment by plata** [comment]
Yes, saw this as well. I think GraalVM is a suggested successor. Nevertheless I believe that we should wait a little more before we decide something. Maybe things get a bit clearer in the near future.

**Comment by madoar** [comment]
Yes, GraalVM, i.e. graal.js, seems to be the best solution long term.
I don't think we need to decide now what we should use in the future, I just believe we should check our alternatives as early as possible, because the new solution is likely to do some things different.

**Comment by plata** [comment]
Is there anything else except GraalVM which you think we should consider?

**Comment by DanielJoyce** [comment]
Graal is the framework dynamic languages on the JVM going forward. It supports JS, Python, and others, with more being added. There is no 'other' right now...

**Comment by plata** [comment]
I've read somewhere that Rhino could be an alternative.

**Comment by madoar** [comment]
Some more up to date news about graal.js (copied from #1303):
It seems like the release candidates for graal.js have been published to [maven central](https://mvnrepository.com/artifact/org.graalvm).
In addition, there is a first version of a repository which demonstrates [graal.js with maven](https://github.com/graalvm/graal-js-jdk11-maven-demo).

**Comment by plata** [comment]
These links should be helpful:
- https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f
- https://github.com/graalvm/graaljs/blob/master/docs/user/NashornMigrationGuide.md
- https://amarszalek.net/blog/2018/06/08/evaluating-javascript-in-java-graalvm/
- https://mvnrepository.com/artifact/org.graalvm

**Comment by plata** [comment]
Seems like GraalVM cannot run JavaFX applications currently.

**Comment by plata** [comment]
Like I said in a different issue, I would like to stabilize our APIs. Having done the include by ID, the next step in my opinion should be Graal because it might have some effects on how we implement Java interfaces in Javascript.
@madoar in my first GraalVM approach, it seemed that you had an idea how to continue. Could you give it a try (based on the graalvm branch)?

**Comment by madoar** [comment]
I agree, the next step should be to migrate to `graal.js`.

I don't have the time currently to work on this. 
I first want to finish my work on the JavaFX parts, before I begin working on other parts of Phoenicis.
I think it should be enough to replace every occurrence of `ScriptObjectMirror` (nashorn) with `Value` (graal.js). 
In addition the associated methods need to be changed as well.

**Comment by plata** [comment]
Done.
