### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1368]
Starting with JDK 11 OpenJFX won't be included in the JDK anymore.
Therefore, we should think about how we can support OpenJFX 11 in the future, and how we can provide support for Java 10- and Java 11+ at the same time.

I've also created an issue asking the last question at the OpenJFX github repository, see [here](https://github.com/javafxports/openjdk-jfx/issues/141).

**Comment by plata** [comment]
As a maybe a bit brute force solution: we could decide to deploy flatpak for Linux (no idea about Mac OS).

**Comment by madoar** [comment]
I believe a flatplat package is a good idea either way.
According to the newest post on https://github.com/javafxports/openjdk-jfx/issues/141, it seems like we can be compatible to both Java 10- and Java 11+ at the same time.

In addition, I believe it's worth to think about changing the system requirements for Phoenicis to Java 11 early on.
This should also solve all the JavaFX issues we currently have with OpenJDK 9 and 10.

**Comment by plata** [comment]
The problem is that we should not require a Java version which is not easily available in one of the big LTS systems (e.g. Ubuntu 16.04 does not provide Java 10/11 if I'm not mistaken).

**Comment by madoar** [comment]
Yes, you're right.

**Comment by plata** [comment]
OpenJFX 11 can be installed with maven.
