### ISSUE TITLE
Script downloads incorrect wine version

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#1388]
### Expected behavior
The script should download wine.3.10-staging 64bit
### Actual behavior
Instead it gets wine 3.1-staging 64bit
### Steps to reproduce
1. Download my Anno 2070 script and place it in your local repo under "Games" subdirectory. (https://github.com/PhoenicisOrg/scripts/pull/679)
2. Run the Uplay variant of this script. Once it downloads the Uplay installer it downloads the wrong wine.
### System information
* software version (git revision) of phoenicis and scripts repositories
POL git revision 9180a71
Using scripts repository version a283000
* used operating system
Ubuntu 18.04 x64
* used Java version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2372778/phoenicis.log)

**Comment by plata** [comment]
Please add
```Javascript
print("winePackage.url: " + winePackage.url);
```
to https://github.com/PhoenicisOrg/scripts/blob/a28300013e29256bb748b0397262c9530fc6c052/Engines/Wine/Engine/Implementation/script.js#L74 and paste the result here.

**Comment by Zemogiter** [comment]
[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2375975/phoenicis.log)
I added the print line like so:
```
...
var tmpFile = createTempFile("tar.gz");
print("winePackage.url: " + winePackage.url);
new Downloader()
...
```
Nothing about `winePackage.url`

**Comment by plata** [comment]
Just tested myself (with custom installer): got printout `winePackage.url: http://www.playonlinux.com/wine/binaries/phoenicis/staging-linux-amd64/PlayOnLinux-wine-3.10-staging-linux-amd64.tar.gz`. That's perfectly fine.

**Comment by plata** [comment]
Ok, I've checked your script. You must use "3.10" (in `""`). But before you do that: Can you change the `==` in https://github.com/PhoenicisOrg/scripts/blob/a28300013e29256bb748b0397262c9530fc6c052/Engines/Wine/Engine/Implementation/script.js#L54 and https://github.com/PhoenicisOrg/scripts/blob/a28300013e29256bb748b0397262c9530fc6c052/Engines/Wine/Engine/Implementation/script.js#L56 to `===`?

**Comment by Zemogiter** [comment]
I did that but why is triple equal sign needed? The script only checks the first three characters in `vineVersion`?

**Comment by plata** [comment]
Check this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators.
If you run `console.log(3.10 == "3.1");`, it gives you `true`. Don't ask me why **exactly** that happens, but I think it explains the problem.
Can you make a pull request with the `===`?
