### ISSUE TITLE
POL5 opens, immediate error about Engine Tools

### ISSUE THREAD

**Issue by redstik** [PhoenicisOrg/phoenicis#1401]
As soon as the POL window opens, this message appears:
https://imgur.com/a/2IeRCyR
Stacktrace : https://pastebin.com/Nk1WLtd9

### System information:
Git version and latest git repo cloned
Operating system :: Arch Linux x86_64 
Java: 1.8.0_181

**Comment by plata** [comment]
Is the error correct? I.e. can you run `git status` in that folder? What happens if you delete the folder and try again (in case the clone failed somehow).
@madoar could it be that a jgit update broke this?

**Comment by madoar** [comment]
@redstik can you please manually delete the specified folder (`/home/bas/.Phoenicis/cache/git-331995911`) and restart Phoencis?
Please tell us afterwards if it works now.

@plata no we had this issue previously as well.
Normally a redownload of the git repository solves this issue 
I'm not sure what is the reason for this error.
Maybe we should add a validity check, whether the folder contains a valid git repository somewhere.

**Comment by plata** [comment]
I wasn't aware of that. We should definitely do that. Can you open an issue?

**Comment by qparis** [comment]
I have also noticed this problem. The two time it happened, it was the very first time that the user launched POL. 
I cannot reproduce the problem even after deleting /tmp and $HOME though

**Comment by redstik** [comment]
> @redstik can you please manually delete the specified folder (`/home/bas/.Phoenicis/cache/git-331995911`) and restart Phoencis?
> Please tell us afterwards if it works now.
> 
> @plata no we had this issue previously as well.
> Normally a redownload of the git repository solves this issue
> I'm not sure what is the reason for this error.
> Maybe we should add a validity check, whether the folder contains a valid git repository somewhere.
Fixed, after deleting the folder.
