### ISSUE TITLE
Folder '...' is no git-repository

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1402]
### Expected behavior
Phoenicis starts correctly

### Actual behavior
Phoenicis doesn't start correctly with an error message containing: `Folder '...' is no git-repository`. (see also #1401)

### Steps to reproduce
This issue occurs sometimes. I'm not really sure what the reason for the bug is, but in all cases I know of, a manual deletion of the folder and a restart of Phoenicis has solved the issue.

**Comment by madoar** [comment]
A short-term solution for this issue could be a validity check after the repository has been downloaded, to see if it contains all necessary files for a git-repository.

**Comment by plata** [comment]
This might be helpful: https://stackoverflow.com/questions/11031244/jgit-validate-if-repository-is-valid

**Comment by pmorch** [comment]
Additional information: Here is a screenshot of how it looks:
![firstrun-no-gitrepository - cropped](https://user-images.githubusercontent.com/159292/46582672-e8fbb200-ca4a-11e8-8434-4c553657a38b.png) and the log file from such a run: [firstrun.txt](https://github.com/PhoenicisOrg/phoenicis/files/2453961/firstrun.txt)

It was made from a fresh VirtualBox Xubuntu 18.04 image following [Build | Phoenicis Documentation](https://phoenicisorg.github.io/phoenicis/Users/build/). It occurred the very first time it was run. `rm -rf /home/test/.Phoenicis/cache/git-331995911` and restarting made the problem disappear.

**Comment by plata** [comment]
@pmorch is it reproducable? I.e. does it happen every time in a fresh VM? In that case, we could investigate this.

**Comment by pmorch** [comment]
Yes, I happens every time in my VM ( I think I tried 4-5 times reverting to a snapshot between each attempt ). I started out from a with a relatively vanilla Xubuntu 18.04 snapshot in VirtualBox.

**Comment by pmorch** [comment]
Ok, so I just tried again with a brand, spanking new [Xubuntu 18.04-1](http://nl.archive.ubuntu.com/ubuntu-cdimage-xubuntu/releases/18.04/release/) VirtualBox VM.

I ran:

```
# apt install virtualbox-guest-utils
# cat phoenicis.sh 
set -x
set -e

# See https://phoenicisorg.github.io/phoenicis/Users/build/

wget -nc https://dl.winehq.org/wine-builds/Release.key && sudo apt-key add Release.key
sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
sudo apt-get purge wine* libwine
sudo apt-get update
sudo apt-get install -y --install-recommends winehq-devel
sudo apt-get update
sudo apt-get install -y git maven openjdk-8-jdk openjfx libxext6:i386

export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64
git clone https://github.com/PhoenicisOrg/phoenicis.git
cd phoenicis
mvn clean package
# ./phoenicis.sh 
```

Then unzipped and ran the built ./phoenicis.sh (not the one above)

"Loading engine tools failed" 

`.Phoenicis/cache/git-331995911/` is an empty directory.

**Comment by plata** [comment]
@qparis do you have an idea why this might be happening?

**Comment by qparis** [comment]
Not really, but it seems to happen the very first time Phoenicis is openned for a given user. 
What is really weird is that once it has happened, it seems to never happen again, even if you delete the whole home directory.
I could not make enough experiments to be sure though

**Comment by plata** [comment]
In the flatpak, it happens all the time. You cannot fix it. However, I did one run where it worked so I got the feeling that it's a timing issue. Like several threads trying to clone at the same time.

**Comment by qparis** [comment]
Have you tried to put the code in a “synchronized” block to ensure that it is run only once?

**Comment by plata** [comment]
I used a mutex. Check the pr.
