### ISSUE TITLE
It should be possible to start an installation on a relatively small window

### ISSUE THREAD

**Issue by pmorch** [PhoenicisOrg/phoenicis#1410]
### Expected behavior

Ok, this is not the end of the world and easy to work around. Consider it usability feedback.

It should be possible to start an installation on a relatively small window. Either because because the window just works or because scrollbars appear if the content is too large.

Or, if there is a minimum window size, ensure the window cannot have a size smaller than that.

### Actual behavior

The next button is inaccessible. No scrollbars visible.

### Steps to reproduce
* Start with a fresh Xubuntu 18.04 installation
* Follow [Build | Phoenicis Documentation](https://phoenicisorg.github.io/phoenicis/Users/build/)
* Hit and work around #1402 
* Try to install e.g. MS Office 2010
* See ![window-too-small](https://user-images.githubusercontent.com/159292/46582782-da15ff00-ca4c-11e8-9cd6-e1f243deabba.png)

### System information
* software version (git revision) of phoenicis

```
test@xfce1804:~/phoenicis$ git log -1
commit c571d6c1db11eb72f2b370893b98575be4e088e5 (HEAD -> master, origin/master, origin/HEAD)
Author: plata <plata@users.noreply.github.com>
Date:   Fri Sep 28 20:02:53 2018 +0200

    Add support for JDK 11 (#1404)

```
... and scripts repositories

? How do I determine that?

* Just updated Xubuntu 18.04

* used Java version

```
test@xfce1804:~/phoenicis$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
test@xfce1804:~/phoenicis$ dpkg-query -W | grep openjdk
openjdk-11-jre-headless:amd64	10.0.2+13-1ubuntu0.18.04.2
openjdk-8-jdk:amd64	8u181-b13-0ubuntu0.18.04.1
openjdk-8-jdk-headless:amd64	8u181-b13-0ubuntu0.18.04.1
openjdk-8-jre:amd64	8u181-b13-0ubuntu0.18.04.1
openjdk-8-jre-headless:amd64	8u181-b13-0ubuntu0.18.04.1
```

**Comment by plata** [comment]
We didn't want to enforce a minimum window size on purpose because that can have very strange effects especially on low res screens. You're point is totally valid though and I think I know where the scrollbar should be added. Nevertheless: Can you post a screenshot of the behavior just to be sure?
