### ISSUE TITLE
cannot open playonlinux 5.0

### ISSUE THREAD

**Issue by suomilanittaja** [PhoenicisOrg/phoenicis#1414]
it just dont open.
used operating system: ubuntu 18.10
installed javas: java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by ImperatorS79** [comment]
Which command did you use to launch phoenicis ? 
If you have any java 10-11 package installed, you should remove them before building (at the moment).

**Comment by plata** [comment]
@ImperatorS79 I'm not really sure that this is still required.
