### ISSUE TITLE
Manual installations

### ISSUE THREAD

**Issue by suomilanittaja** [PhoenicisOrg/phoenicis#1415]
Is manual installations possible if not please add it.

**Comment by ImperatorS79** [comment]
The Local an Online installer in the app tab are maybe what you are looking for.

**Comment by plata** [comment]
The installers mentioned by @ImperatorS79 are indeed what is the considered solution for this use case. If you need anything else, let us know.

**Comment by plata** [comment]
Closed due to inactivity. Feel free to re-open if you're still missing something.
