### ISSUE TITLE
Darwin 64Bit Versions

### ISSUE THREAD

**Issue by atilling** [PhoenicisOrg/phoenicis#1420]
I'm not sure if this should be under Phoenicis or under Scripts, it seems to be more of PlayOnLinux site issue.

In Phoenicis looking at Engines for 64 bit windows that latest version listed as available is 2.0 from WineHQ I can see stable 3.0.3 and staging 3.17 both should 64 bit support https://dl.winehq.org/wine-builds/macosx/download.html
But the playon site doesn't show a POL wine that corresponds. I remember some talk earlier about using a different repo for Wine but I'm not finding it. What is different about the tar on the POL site verses what's on WinHQ? Can I do some build/testing work to make the newer Wine versions available?

**Comment by ImperatorS79** [comment]
The way to use the macOS builds from winehq is there -> [https://github.com/PhoenicisOrg/wine-sources](https://github.com/PhoenicisOrg/wine-sources).

**Comment by qparis** [comment]
Hi

Currently, darwin 64bits builds are not compiled automatically because they are not cross-built. This is why you do not have all the versions. As a short workaround, I can relaunch manually the script locally.

I'm currently thinking about rewriting winebuild

**Comment by plata** [comment]
You can use the official builds with this: https://github.com/PhoenicisOrg/wine-sources/blob/master/winehq-macosx.json (set it in your .properties).

**Comment by qparis** [comment]
This is the first step to rewrite winebuild service:
https://github.com/PhoenicisOrg/phoenicis-winebuild

This first version is able to build a consistent linux-x86 wine version on any operating system

**Comment by qparis** [comment]
Update: We are now able to build darwin-x86, darwin-amd64 and linux-x86 builds. 

Stay tuned

**Comment by qparis** [comment]
@atilling You can try to build manually one build to see if it works for you if you want

**Comment by atilling** [comment]
Tried to use the https://github.com/PhoenicisOrg/wine-sources/blob/master/winehq-macosx.json in properties. Engine tab is blank and get a Debug:

Found key 'webservice.wine.url' in PropertySource 'URL [file:/Users/atilling/Library/Phoenicis/config.properties]' with value of type String
[DEBUG] org.phoenicis.engines.EnginesManager (l.116) - Unable to unserialize engine json

**Comment by atilling** [comment]
Got it, had to use the URL: https://raw.githubusercontent.com/PhoenicisOrg/wine-sources/master/winehq-macosx.json
The other URL returns the GITHub interface in addition to the file.

**Comment by atilling** [comment]
If you are referring to the readme for wine-sources that is incorrect.
Currently

> Available Wine sources
Lutris (Linux): https://github.com/PhoenicisOrg/wine-sources/master/lutris-linux.json
WineHQ (OSX): https://github.com/PhoenicisOrg/wine-sources/master/winehq-macosx.json

If you click the links currently in the readme you get empty json files with the github interface.
Should be
`Available Wine sources
Lutris (Linux): https://raw.githubusercontent.com/PhoenicisOrg/wine-sources/master/lutris-linux.json
WineHQ (OSX): https://raw.githubusercontent.com/PhoenicisOrg/wine-sources/master/winehq-macosx.json

**Comment by plata** [comment]
You're right. Fixed.

**Comment by plata** [comment]
Can we close the issue?
