### ISSUE TITLE
Find solution to securly exchange secret data

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1422]
We need a way to exchange e.g. credentials for the GitHub bot, website accounts etc.

Possible solution:
[passbolt](https://www.passbolt.com/) (e.g. on [Heroku](https://www.heroku.com/products))

**Comment by atilling** [comment]
I was on a project and the passwords were kept  encrypted in an md file, Contribs were given the decrypt key so there was only one password you needed to get when you were promoted.

**Comment by plata** [comment]
It's a possibility but also a bit dangerous in case that password gets corrupted.
