### ISSUE TITLE
Suggestion: Ability to rename container

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1439]
I think it would be good if we should be able to rename container, I don't think it is hard to implement.

Why? --> Convenience / User friendliness, for example if I change my mind in future.

**Comment by qparis** [comment]
As far as I know, PlayOnLinux 4 is not able to rename containers. The reason is that it would result on a broken container: all the shortcuts, external or internal absolute path relying on the container would no longer working.

**Comment by plata** [comment]
So this can be closed?

**Comment by t0msk** [comment]
Yes :)
