### ISSUE TITLE
Add button to open container in file manager

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1441]
Hello, It would be great if I select container then there was button for example "Open directory", and after click it would open directory of container in file manager :)

**Comment by plata** [comment]
In container tab, info panel.

**Comment by t0msk** [comment]
In container tab, info panel there is only button for deleting container :)

**Comment by plata** [comment]
The comment was only to state where it should be added 😉.

**Comment by t0msk** [comment]
Oh okey :smile:
