### ISSUE TITLE
hu (magyar - Hungarian) Crowdin translation

### ISSUE THREAD

**Issue by ovari** [PhoenicisOrg/phoenicis#1451]
@plata @madoar please accept and merge the hu localization into the master branch. Thank you

**Comment by ovari** [comment]
Updated the [Crowdin hu translations](http://crowdin.com/translate/phoenicis/all/en-hu#h=223e6aa73fe7e1ba886b7ba076e2cb0b143815) after the merged "Update English texts" #1449

**Comment by plata** [comment]
Thanks. I'd like to wait a bit before merging this so that also the other translations are updated in one rush.

**Comment by plata** [comment]
Translations are review in Crowdin. They will be merge with the translation pull request. We do not need a separate issue to track that.
