### ISSUE TITLE
Broken Apps tab, application info does not show up

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#1461]
### Expected behavior
Application description and it's installation options show up when clicking on the miniature
### Actual behavior
Nothing appears
### Steps to reproduce
Run the latest version of POL5 (from the zip file in `phoenicis-dist/target`)
### System information
* software version (git revision) of phoenicis and scripts repositories
git revision ddaf4fb91d45bd5b11775a747dd4662da8f01cf9 and scripts repo is 2dda629 
* used operating system
Ubuntu 18.10 x64
* used Java version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)

[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2560695/phoenicis.log)

**Comment by madoar** [comment]
> ### Actual behavior
> 
> Nothing appears

As in the right sidebar doesn't appear or it is empty?
Can you please add a screenshot?

**Comment by Zemogiter** [comment]
@madoar the sidebar dosen't appear
Because of that I can't add a screenshot because it wouldn't look like anything's wrong.

**Comment by plata** [comment]
There's nothing in the logs. How familiar are you with Java? Can you debug or add some log output to ?https://github.com/PhoenicisOrg/phoenicis/blob/ddaf4fb91d45bd5b11775a747dd4662da8f01cf9/phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ApplicationsView.java#L176

**Comment by Zemogiter** [comment]
I'm not good in Java.

**Comment by Zemogiter** [comment]
But line 176 in that file is part of a multi-line comment so it won't have any effect.

**Comment by Zemogiter** [comment]
OK so I've managed to get around this problem by simply replacing the `LOGGER` variable with the exact command on the other side of equation mark. Here is the new log file after I've compiled the code with changed `ApplicationsView.java`:
[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2569187/phoenicis.log)
Weirdly enough nothing referencing `ApplicationPanel` is there. I wonder if I have done something wrong.
Here is the modified java file:
[ApplicationsView.java.zip](https://github.com/PhoenicisOrg/phoenicis/files/2569191/ApplicationsView.java.zip)

**Comment by plata** [comment]
Try to move the logger call one line up so that it's the first command in the method. If the output still doesn't show up, the method is not called which would explain why you don't see the panel. If that's the case, you must dig into `CombinedListWidget` to figure out why the method is not called. Currently I cannot see how this could probably happen.

**Comment by Zemogiter** [comment]
[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2569884/phoenicis.log)
Did that and now there are two mentions of `ApplicationPanel` there. Both of them say there might be an error in `showAppDetails`.
[ApplicationsView.java.zip](https://github.com/PhoenicisOrg/phoenicis/files/2569919/ApplicationsView.java.zip)

**Comment by plata** [comment]
The `[ERROR]` is only because we used the error logger. It has no meaning at all. I would tend to agree to your suspicion. I also do not believe that this is leading anywhere without attaching a debugger. Can you try to reproduce this in e.g. a VM?

**Comment by Zemogiter** [comment]
@plata You mean like VisualVM?
https://visualvm.github.io/

**Comment by plata** [comment]
No. For example virtual box with a fresh Ubuntu 18.10 installation.

**Comment by Zemogiter** [comment]
lol when you said VM I thought you meant like JVM or something like that.
OK i'm gonna set up and try to reproduce this issue.

**Comment by Zemogiter** [comment]
I'm on the VM, fresh instalation, did everything like in the Build page expect for java version (11 instead of 8) and upon launching it (from the .zip file not deb package) I get errors regarding repository cache - the folder mentioned in error is empty.
[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2574115/phoenicis.log)

**Comment by plata** [comment]
To verify the Java 11 assumption: Can you try with Java 8?

**Comment by Zemogiter** [comment]
Purged java 11 and installed java 8. Using the `update-alternatives` command gave me this:
```
sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64
update-alternatives: error: no alternatives for jaotc
update-alternatives: error: no alternatives for jdeprscan
update-alternatives: error: no alternatives for jhsdb
update-alternatives: error: no alternatives for jimage
update-alternatives: error: no alternatives for jlink
update-alternatives: error: no alternatives for jmod
update-alternatives: error: no alternatives for jshell
update-alternatives: error: no alternatives for mozilla-javaplugin.so
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
```
The `IcedTeaPlugin.so` file does not exist in that directory and `mvn clean package` gave me the exact same error as #1435 

I suspect that in Ubuntu 18.10 it's either Java 11 or bust. Because before I updated POL5 was working with Java 8.

**Comment by plata** [comment]
I think I will have to try this myself in a VM. The whole situation with Java 11 is not quite satisfying yet. One problem is that e.g. proper Java modules would break compatibility with Java 8.

**Comment by plata** [comment]
@Zemogiter is this still valid?

**Comment by Zemogiter** [comment]
I've just removed the `phoenicis` folder and downloaded the latest source code with
`git clone https://github.com/PhoenicisOrg/phoenicis.git`
Application description now shows up and the .deb package works. POL5 is now fully operational.
Tried to do this earlier this week but cloudflare had some errors which resulted in maven not downloading some files.
