### ISSUE TITLE
Check French translations in Crowdin

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1462]

**Comment by Dratui** [comment]
Do you need some help ?

**Comment by qparis** [comment]
I’ll also help

**Comment by plata** [comment]
@Dratui I think most of the strings are translated currently and only are waiting for approval. You're very welcome to join on Crowdin though.

@qparis please contact me in Crowdin and I will give you admin access.

**Comment by plata** [comment]
@Dratui some of the texts have changed so if you're willing to help, it would be very appreciated.

**Comment by plata** [comment]
@qparis the translations have been updated. Can you please check and accept them?

**Comment by madoar** [comment]
@plata I don't think @qparis has manager rights on Crowdin for the projects.

**Comment by plata** [comment]
I gave him the rights now. At least I hope it's him :P He didn't PM me on Crowdin so I just searched for the username.

**Comment by plata** [comment]
@qparis can you check that you are admin in Crowdin?

**Comment by plata** [comment]
This is the last open topic before we can merge the updated translations.

**Comment by plata** [comment]
Finished.
