### ISSUE TITLE
Fedora >= 26 build not work please upgrade dependency on your doc

### ISSUE THREAD

**Issue by andykimpe** [PhoenicisOrg/phoenicis#1468]
Fedora >= 26

sudo dnf install git maven

git clone https://github.com/PhoenicisOrg/phoenicis.git

cd phoenicis

mvn clean package

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] phoenicis 5.0-SNAPSHOT ............................. SUCCESS [  5.680 s]
[INFO] phoenicis-configuration ............................ SUCCESS [ 27.981 s]
[INFO] phoenicis-entities ................................. SUCCESS [  0.639 s]
[INFO] phoenicis-multithreading ........................... SUCCESS [  6.393 s]
[INFO] phoenicis-win32 .................................... SUCCESS [  4.696 s]
[INFO] phoenicis-tools .................................... SUCCESS [ 31.047 s]
[INFO] phoenicis-repository ............................... SUCCESS [  9.022 s]
[INFO] phoenicis-scripts .................................. SUCCESS [  1.000 s]
[INFO] phoenicis-library .................................. SUCCESS [  0.698 s]
[INFO] phoenicis-engines .................................. SUCCESS [  0.461 s]
[INFO] phoenicis-settings ................................. SUCCESS [  0.219 s]
[INFO] phoenicis-containers ............................... SUCCESS [  0.347 s]
[INFO] phoenicis-javafx ................................... FAILURE [  5.718 s]
[INFO] phoenicis-cli ...................................... SKIPPED
[INFO] phoenicis-dist ..................................... SKIPPED
[INFO] phoenicis-tests 5.0-SNAPSHOT ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2018-11-16T20:02:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project phoenicis-javafx: Compilation failure
[ERROR] /home/andy2/phoenicis/phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/ListWidgetChooser.java:[3,20] cannot access javafx.event.ActionEvent
[ERROR]   bad class file: /home/andy2/.m2/repository/org/openjfx/javafx-base/11.0.1/javafx-base-11.0.1-linux.jar(javafx/event/ActionEvent.class)
[ERROR]     class file has wrong version 54.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :phoenicis-javafx

sudo dnf install git maven openjfx

mvn clean package

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] phoenicis 5.0-SNAPSHOT ............................. SUCCESS [  5.680 s]
[INFO] phoenicis-configuration ............................ SUCCESS [ 27.981 s]
[INFO] phoenicis-entities ................................. SUCCESS [  0.639 s]
[INFO] phoenicis-multithreading ........................... SUCCESS [  6.393 s]
[INFO] phoenicis-win32 .................................... SUCCESS [  4.696 s]
[INFO] phoenicis-tools .................................... SUCCESS [ 31.047 s]
[INFO] phoenicis-repository ............................... SUCCESS [  9.022 s]
[INFO] phoenicis-scripts .................................. SUCCESS [  1.000 s]
[INFO] phoenicis-library .................................. SUCCESS [  0.698 s]
[INFO] phoenicis-engines .................................. SUCCESS [  0.461 s]
[INFO] phoenicis-settings ................................. SUCCESS [  0.219 s]
[INFO] phoenicis-containers ............................... SUCCESS [  0.347 s]
[INFO] phoenicis-javafx ................................... FAILURE [  5.718 s]
[INFO] phoenicis-cli ...................................... SKIPPED
[INFO] phoenicis-dist ..................................... SKIPPED
[INFO] phoenicis-tests 5.0-SNAPSHOT ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2018-11-16T20:02:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project phoenicis-javafx: Compilation failure
[ERROR] /home/andy2/phoenicis/phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/ui/ListWidgetChooser.java:[3,20] cannot access javafx.event.ActionEvent
[ERROR]   bad class file: /home/andy2/.m2/repository/org/openjfx/javafx-base/11.0.1/javafx-base-11.0.1-linux.jar(javafx/event/ActionEvent.class)
[ERROR]     class file has wrong version 54.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :phoenicis-javafx

oenjdk openjfx installed and not working

please upgrade your documentation

**Comment by plata** [comment]
Which Java version do you use? The error message says that a class in JavaFX is not compatible with your version.

**Comment by andykimpe** [comment]
I simply use the commands you give on your documentation

if it's not the right version it's up to you to make sure that your

documentation be up to date me I have openjdk 1.8

it's the one that gets installed with the commands you specify

**Comment by plata** [comment]
I didn't provide this description and I do not use Fedora myself so I can only try to help you to my best knowledge.
You might want to try the changes from #1458.
