### ISSUE TITLE
Correct way to install & Update Phoenicis

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1511]
Hello,

I would like to ask you what is correct way to install Phoenicis via github and what is correct way to update it, so I don't want to install it via deb file. I just want to pull newest changes from github and rebuild it without losing any user settings / containers / apps.

Thank you

**Comment by plata** [comment]
The settings etc. will not be affected if you rebuild Phoenicis.

**Comment by t0msk** [comment]
Thanks
