### ISSUE TITLE
Lazy load repository

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1512]
The repository (and thus the apps and engines) shall only be loaded if they are required.

**Comment by plata** [comment]
@madoar any ideas how this should work together with the repository update callback?

**Comment by qparis** [comment]
I'm not sure than they shall be lazy loaded. However, I think that the loading should be non-blocking as possible. (i.e., use an old / local version as long as the loading process is not finished)

**Comment by plata** [comment]
That won't work. Especially if you have a slower PC, the background loading will block the rest of the application (e.g. because the git cloning is writing to the HDD). I can observe this behavior currently (which is why I did the preloading in the splash).

**Comment by qparis** [comment]
This seems weird. I mean, in general you can use your PC while you are cloning a git repository inside another process, can't you?

**Comment by plata** [comment]
Yes. I'm not saying it doesn't work. It's just really slow. This leads to effects like library doesn't show anything for 1-2 minutes.

**Comment by qparis** [comment]
Is the cloning stuff running in Platform.runLater by any chance?

**Comment by plata** [comment]
I don't think so. But I'm not sure. Would have to check it in the code.

**Comment by madoar** [comment]
I will need to take a look at the repository loading in more detail before I can give a suggestion/solution.

**Comment by plata** [comment]
@madoar that would be great!

In general, I see two options:
1. Preload everything such that the application is completely up and running.
2. Lazy load everything which is not needed immediately.

I prefer the 2. because:
- faster startup
- smaller memory footprint
- like @qparis said, most users only want to run a shortcut from their library (I agree with that)

**Comment by plata** [comment]
I just checked this again and it seems that we cannot do this: The translations for the categories (also in the library) are stored in the repository. The best I can do is create the widgets for apps, containers and engines only if required.

**Comment by madoar** [comment]
@plata should this issue be closed?

**Comment by plata** [comment]
Yes.
