### ISSUE TITLE
Breeze dark icons missing

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1519]
### Expected behavior
Breeze dark uses custom icons.

### Actual behavior
All icons except the default ones are missing.

### System information
* Java 10

**Comment by plata** [comment]
This does not happen with Java 8. I assume it's related to Java modules. What I do not understand is why the CSS can be found but not the icons.

**Comment by madoar** [comment]
Does this happen independent of the installation/execution method?

**Comment by plata** [comment]
Ok... It works if I add "opens" to `module-info.java` for all icon folders. See https://stackoverflow.com/questions/48768879/how-to-access-resource-using-class-loader-in-java-9. Probably also this should also be done for the default theme but it's not possible because "default" is not a valid module name...
