### ISSUE TITLE
Installing Phoenicis via deb file requires uninstalling Adwaita

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1524]
Cloned newest version of Phoenicis.

Just why?

![screenshot_20181202_223012](https://user-images.githubusercontent.com/7276200/49345344-d0db9400-f683-11e8-8aed-6b295865400f.png)

**Comment by qparis** [comment]
Probably because your awaita package has conflicts with a dependency of POL5

**Comment by t0msk** [comment]
@qparis How it could have a conflict? Why it just doesn't install another version of dependency?

**Comment by qparis** [comment]
Phoenicis has no conflicts. Therefore, your neon-awaita packages or one of its dependency must have a conflict with a Phoenicis dependency

**Comment by t0msk** [comment]
So I just uninstalled it, but is there any other way how to solve it?

**Comment by t0msk** [comment]
And can you help me how? Or should I rather ask on unix stackexchange?

**Comment by ImperatorS79** [comment]
I do not see where it can come from. You can note de .deb is "designed" to work on ubuntu 18.04. best you can do is checking the dependencies of `neon-adwaita` and reports us which one is conflicting.

**Comment by t0msk** [comment]
This is an output:
```
tomsk@tomsk-pc:~$ apt rdepends neon-adwaita 
neon-adwaita
Reverse Depends:
  Recommends: neon-desktop
  Recommends: neon-desktop
  Recommends: neon-desktop
  Recommends: neon-desktop
tomsk@tomsk-pc:~$ apt-cache rdepends neon-adwaita
neon-adwaita
Reverse Depends:
  neon-desktop
  neon-desktop
  neon-desktop
  neon-desktop
tomsk@tomsk-pc:~$ apt-cache rdepends neon-desktop
neon-desktop
Reverse Depends:
  neon-desktop-ko
  neon-desktop-ko
  neon-desktop-ko
  neon-desktop-ko
tomsk@tomsk-pc:~$ apt-cache rdepends neon-desktop-ko
neon-desktop-ko
Reverse Depends:
```
and I use KDE Neon and it is Ubuntu.

**Comment by ImperatorS79** [comment]
Strange, i do not have any problems on my ubuntu system. Could you try to install the .deb by command line to see with which deps it does not work ?

**Comment by t0msk** [comment]
I just uninstalled it, but if I try to install it again I will get:
```
The following packages will be REMOVED:
  adwaita-icon-theme humanity-icon-theme libgtk-3-0:i386 phoenicis-playonlinux ubuntu-mono
The following NEW packages will be installed:
  neon-adwaita
```

**Comment by plata** [comment]
Can you run `apt update` and `apt upgrade` before trying to install the deb? Just to be sure...

**Comment by qparis** [comment]
Any update on this?

**Comment by plata** [comment]
Closed due to inactivity.

@t0msk if you still have this issue, feel free to reopen.
