### ISSUE TITLE
Add libldap to flatpak

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1535]
### Expected behavior
ElsterFormular works

### Actual behavior
```
0030:err:module:load_builtin_dll failed to load .so lib for builtin L"WLDAP32.dll": libldap_r-2.4.so.2: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
0030:err:module:import_dll Loading library WLDAP32.dll (which is needed by L"C:\\Program Files\\ElsterFormular\\bin\\ericapi.dll") failed (error c000007a).
0030:err:module:import_dll Library ericapi.dll (which is needed by L"C:\\Program Files\\ElsterFormular\\bin\\ericprozess.exe") not found
0030:err:module:attach_dlls Importing dlls for L"C:\\Program Files\\ElsterFormular\\bin\\ericprozess.exe" failed, status c0000135
```

### Steps to reproduce
Run ElsterFormular in flatpak.

**Comment by plata** [comment]
The dll's are located in the same directory as the executable.

**Comment by plata** [comment]
I think the problem is a missing libldap.

@qparis can we add libldap to the the Wine package?

**Comment by qparis** [comment]
I guess we can

**Comment by plata** [comment]
Do we have a way to figure out if there are other dependencies we should provide? Also: do you want me to move this to the winebuild repository?

**Comment by ImperatorS79** [comment]
lib and lib64 normally contains only .dll.so and fakes dll. All other dependencies can be installed by the user using the distribution packaging system(it is automatically done it the .deb for example). This avoids multiple installations of the same dependency many times if you install multiple wine versions. Maybe you should look at adding those wine deps to the flatpak ?

**Comment by plata** [comment]
@ImperatorS79 I thought about this. Like I said, I'm not really sure about the concept but for me it doesn't make sense to ship libpng but not libldap. Either we ship both or none.

**Comment by ImperatorS79** [comment]
Normally the wine builds should not ship any other libs than .dll.so,

**Comment by plata** [comment]
We ship more than that already. It's really a question of what we want to achieve. I will leave the decision about this to @qparis.

**Comment by qparis** [comment]
On OSX, it is pretty clear that we **should** ship dependencies. Indeed, we are pretty sure that they will be compatible from one Mac to another.

On Linux, the question is a little more tough. We need to make sure that the dependencies will be compatible from a distribution to another. We had such problems before. The best we could do is to install VMs of the last most common distributions and make some test

**Comment by plata** [comment]
A different question is: Can we be sure that all Wine versions need the same version of the dependency and is that version even available on the target system?

**Comment by qparis** [comment]
I still believe that we need to provide deb packages at least to facilitate the adoption of Ubuntu users ...

**Comment by plata** [comment]
I'm not saying we should not provide deb at all. I'm just pointing out why I think we should go towards flatpak for the future. And one aspect of this is how to handle dependencies.

**Comment by qparis** [comment]
I guess that winebuild should work the same way, whatever the packaging system you are using. If we take that into account we have two options :
- Provide librairies inside the package. This is what we did with first winebuilds but it caused compatibility issue at the end
- Do not provide anything, and ask the user to install wine so that we are sure that dependencies are here

**Comment by ImperatorS79** [comment]
Why installing wine ? Just install the deps.

**Comment by plata** [comment]
So do we have any conclusion here?

**Comment by plata** [comment]
Not required anymore. Dependencies must be provided by the runtime.
