### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1539]
If I resize main window and then I close Phoenicis and reopen it, it will not remember my resized size.

I think if I resize window and then reopen it, it should remember size.

**Comment by plata** [comment]
This behavior is implemented already. I've just verified again and it's working for me. Of course, you must exit cleanly (i.e. if the process is just killed or you do not confirm the close dialog, it won't work).
Can you provide any more detail?

**Comment by t0msk** [comment]
Oh okey, it works, I may do something wrong.
