### ISSUE TITLE
Make buttons in Library like buttons

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1540]
As you can see on the screenshot below these buttons in Library looks like images and not like buttons, there is no feedback for user.

Some advice:

- It should have hover effect when I mouse over it.
- If I click on it, it should show some push effect like button.
- After clicking, there could be maybe change of mouse cursor to "working / loading" state.

![screenshot_20181205_134549](https://user-images.githubusercontent.com/7276200/49514450-6483af00-f894-11e8-92e4-d2110d35ded9.png)

**Comment by plata** [comment]
Agree to the first two points. The last one is a bit tricky because we do not know when to go out of the working/loading state.

**Comment by t0msk** [comment]
So then these first two points should be implemented :)
