### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1541]
We live in 21. century, so I would be happy if there was responsive design :)

As you can see on the screenshot below it just "cuts" content if window is too small, yes I can make window bigger, but I think for better **UX** there should be responsive design which adapts to window size.

![screenshot_20181205_135655](https://user-images.githubusercontent.com/7276200/49514945-d1e40f80-f895-11e8-9606-86ae8e49ebdc.png)

**Comment by plata** [comment]
This is pretty much the same as #1410.

**Comment by t0msk** [comment]
I don't know if scroll bar will solve this issue, because scroll bar is not good from the **UX** view, because it require another action from user. If it would be responsive, then icons could scale down automatically (they are big anyway in my opinion).
