### ISSUE TITLE
No Internet bug: No engine panels in Containers

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1548]
As you can see below on the screenshot when I don't have connection to the internet then I don't have Engine settings and Engine tools panels in selected container.

Using latest version of Phoenicis from git.

![screenshot_20181205_200638](https://user-images.githubusercontent.com/7276200/49537923-86982400-f8ca-11e8-84c9-adea85f065a1.png)

**Comment by plata** [comment]
That's normal. The engine settings and tools come from the repository so if you do not have the repository, you cannot have them.

**Comment by t0msk** [comment]
@plata So then it should be cached :)

**Comment by plata** [comment]
If the repository is cached/local, it should work.

**Comment by t0msk** [comment]
So it means that this is already implemented? Because I don't see these tabs when I don't have access to the internet.

**Comment by plata** [comment]
Yes. Are you sure that the cache exists? So if you first connect to the Internet, check that the tools are there and then restart Phoenicis, they are not displayed anymore?

**Comment by t0msk** [comment]
Yes, if I am connected to the internet, I see tools, but when I disconnect from the internet and restart Phoenicis, then they are not displayed anymore.

**Comment by plata** [comment]
Ok. That's a bug.
