### ISSUE TITLE
Installation of Notpad++ stalls during wine download

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1553]
The installation of Notepad++ stalls during the wine download.
Is it possible, that this is related to https://www.playonlinux.com/en/topic-16119-Problems_when_installing_Microsoft_Office_2010.html#m62764?

**Comment by plata** [comment]
I have experienced that sometimes downloading the json is really, really slow. Usually the installation will continue at some point in time.

**Comment by plata** [comment]
@madoar do you still have this? I cannot reproduce the issue.
