### ISSUE TITLE
Function for return boolean if File exist (true) or not (false)

### ISSUE THREAD

**Issue by ovari** [PhoenicisOrg/phoenicis#1558]
### Expected behavior
Write scripts that check if a file exists before assigning shortcuts, file associations, etc.

### Actual behavior
https://github.com/PhoenicisOrg/scripts/issues/704#issuecomment-445454908

### Steps to reproduce
Office 2010 script where only a subset of the programs are installed.
https://www.playonlinux.com/en/app-801.html

Please list the File_Exists function and an example
http://wiki.playonlinux.com/index.php/Scripting_-_Chapter_11:_List_of_Functions

Thank you

**Comment by plata** [comment]
We have this already: https://github.com/PhoenicisOrg/scripts/blob/da25af83aab78a99241ea0439cb27e83e8c6bfd4/Utils/Functions/Filesystem/Files/script.js#L27
