### ISSUE TITLE
Use LiveDirsFX to update library/container tab

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1559]
https://github.com/TomasMikula/LiveDirsFX

**Comment by madoar** [comment]
All in all I agree to use a library to help updating the library and container tabs.
My issue with the libraries by Tomas Mikula is that they don't seem to be maintained in the last 2 - 4 years (depending on which library you look).
Therefore it's possible that the library won't work with JavaFX 11 or future version of JavaFX.

**Comment by plata** [comment]
I didn't check that but you're right.

**Comment by qparis** [comment]
Also, Let’s not forget that JavaFX is only one kind of front end. Watching directory should be a task performed by the lowest layers
