### ISSUE TITLE
Change the code specification for the keyword `this`

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1564]
Currently we use the keyword `this` basically whenever we can.
I don't think that this is a good idea, because it distracts from the important lines in the code where it is absolutely required.
In addition it makes the code longer and therefore decreases the readability.

For more details see the discussion in #1556

**Comment by qparis** [comment]
I agree with @plata, this is generally a good practice to differentiate object scope and local scope.

The cases when you have more scope are rare.

**Comment by madoar** [comment]
@qparis are we talking about both variable access and method invocation?

**Comment by qparis** [comment]
Whatever we chose to do I think we should keep the same convention between  methods and variables access. What do you think?

**Comment by madoar** [comment]
I'm not sure, for methods there is no distinction between the narrowest scope and the second scope in my opinion, because you can't define a method inside another function without using a variable.

**Comment by plata** [comment]
You could argue that both member variables and methods are tied to an object and should therefore be prefixed with `this`.

**Comment by madoar** [comment]
Yes, but in some cases this would look really strange.
For example take a look at the previously mentioned `EnginesController` class.
The `EnginesController` class contains the following method:

```java
private void forceViewUpdate() {
    this.populateView(this.repositoryCache, this.enginesCache);
}
```

The single line inside the method contains three `this`, which in my opinion are at least two to many.

**Comment by plata** [comment]
Isn't there an official style guide somewhere which we can use?

**Comment by plata** [comment]
Can we take a decision here and close this?

In my opinion, `this` should always be used for member variables. For methods I don't really care (I cannot think of a case where adding `this` to a method would provide additional information).

**Comment by madoar** [comment]
I would like to use the IntelliJ auto generate codestyle, because truth be told it creates a lot of our trivial methods (getters and setters). The IntelliJ style only uses `this` for setter methods, i.e. for calls that change something.

**Comment by plata** [comment]
I don't understand the reasoning behind this behavior.

**Comment by plata** [comment]
To bring this to an end:
- Use `this` for all member variables.
- Do not use `this` for methods.

Are you ok with this regulation? Shall we add it somewhere in the documentation?

**Comment by madoar** [comment]
I'm ok with this. I think we should add it to the documentation.

**Comment by plata** [comment]
A new page in the developers section? How shall we name it? Coding rules?

**Comment by madoar** [comment]
Yes a new page in the developers section sounds good. `Coding rules` sounds good. Alternatively we could use `Coding style`
