### ISSUE TITLE
Remove `AdhocList` and `ExpandedList`

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1566]
This issue is blocked by #1565.

### AdhocList
`AdhocList` can be directly replaced by the new `ConcatenatingList` of #1565.

### ExpandedList
`ExpandedList` can be replaced by a combination of a `MappedList` and a `ConcatenatingList`, where the `MappedList` returns a list containing lists, which is then fed to the `ConcatenatingList`.

**Comment by plata** [comment]
@madoar is this still valid?
