### ISSUE TITLE
Tabs don't remember list widget selection

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1579]
### Expected behavior
![grafik](https://user-images.githubusercontent.com/18488086/50043539-53962300-0076-11e9-8c7c-8968db751c9a.png)

### Actual behavior
![grafik](https://user-images.githubusercontent.com/18488086/50043541-555fe680-0076-11e9-8bef-3611b10c6e60.png)

### Steps to reproduce
1. Open Phoenicis
2. Select engines tab
3. Select list view widget (the most right one)
4. Restart Phoenicis
5. Select engines tab

**Comment by plata** [comment]
This happens only for the engines tabs? Or do we have the same issue for apps etc?

**Comment by madoar** [comment]
I think it happens for all tabs, but I did only test it for the engines tab.
The most likely root of the problem is in the communication between the `ListWidgetSelector` and the list widgets.

I want to solve this long term by directly using an `ObjectProperty` with the selected list widget instead of a callback function.
