### ISSUE TITLE
POL 5.0 Does not launch

### ISSUE THREAD

**Issue by shag00** [PhoenicisOrg/phoenicis#1584]
Installed on Kubuntu 18.04.01.

When clicking on either the GUI or CLI icon that a window opens.

Nothing happens.

Install with Qapt package installer (included with distribution)

### System information
* software version (git revision) of phoenicis and scripts repositories=5.0
* used operating system=Kubuntu 18.04.01
* used Java version=
 java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
[directory.txt](https://github.com/PhoenicisOrg/phoenicis/files/2683391/directory.txt)
(this is the Phoenicis log)

**Comment by ImperatorS79** [comment]
Did you use the .deb or the .zip ?

**Comment by plata** [comment]
Please try the latest software and scripts from GitHub.

**Comment by shag00** [comment]
@ImperatorS79 
confirmed used phoenicis_5.0.0-alpha1.deb

`angel@angelpc:~$ phoenicis-javafx
Error: Could not find or load main class org.phoenicis.javafx.JavaFXApplication
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
angel@angelpc:~$ `

**Comment by shag00** [comment]
@plata 
looked at the downloads here and they appear to me to be exactly the same as what is available from the POL site.

**Comment by ImperatorS79** [comment]
@shag00 @plata means you need to follow this : [https://phoenicisorg.github.io/phoenicis/Users/build/](https://phoenicisorg.github.io/phoenicis/Users/build/)

**Comment by shag00** [comment]
Seems Build went ok:
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:17 min
[INFO] Finished at: 2018-12-19T17:24:39+08:00
[INFO] Final Memory: 267M/469M
[INFO] ------------------------------------------------------------------------

But Run did not:
angel@angelpc:~/phoenicis$ cd phoenicis/phoenicis-dist/target
bash: cd: phoenicis/phoenicis-dist/target: No such file or directory

So either the build was built incorrectly or the Run instructions are wrong?

**Comment by shag00** [comment]
OK, all sorted, thank you.

**Comment by ImperatorS79** [comment]
@shag00 Close the issue then ;-).
