### ISSUE TITLE
Phoenicis fails to launch after pulling the latest version from git

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#1615]
### Expected behavior
POL5 window shows up
### Actual behavior
nothing happens
### Steps to reproduce
Follow the build guide
### System information
* software version (git revision) of phoenicis and scripts repositories
POL5 commit 1b6d3eb, repo commit eba3def
* used operating system
Ubuntu 18.10 x64
* used Java version
```
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)
```
[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2705005/phoenicis.log)

**Comment by madoar** [comment]
Can you try again with the current master build (i.e. with 85ef51814def538d204ef31fba007e154db4c3fa merged)?

**Comment by Zemogiter** [comment]
I did and while the .deb package shows no difference, the version inside the .zip archive works. Here is the log file made when launching the .zip version:
[phoenicis.log](https://github.com/PhoenicisOrg/phoenicis/files/2705009/phoenicis.log)

**Comment by madoar** [comment]
With no difference you mean that the deb continues to throw the exception?
This is strange, @plata do you have an idea?

**Comment by Zemogiter** [comment]
@madoar that is correct
