### ISSUE TITLE
Problem when wine versions does not starts with wine-

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1634]
Currently, phoenicis removes PlayOnLinux-wine- prefix from any installed wine version. Example, 3.0.4 is stored in <Root>/wine/linux-x86/3.0.4

The problem is that cx does not start with wine. Therefore, the engine is stored in <Root>/wine/linux-x86/PlayOnLinux-winecx-18.xxx which causes inconsistency. 

I suggest we keep wine- prefix

**Comment by plata** [comment]
Isn't this more an issue of winebuild?

**Comment by qparis** [comment]
I don’t believe so... There is nothing we can do in winebuild except forcing the wine- prefix to all the builds

**Comment by plata** [comment]
But the name must be set somewhere?

**Comment by qparis** [comment]
I need to check something on the web service though

**Comment by qparis** [comment]
Problem cames from backend:

https://phoenicis.playonlinux.com/index.php/wine?os=darwin

Fixed
