### ISSUE TITLE
Provide on flathub

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1638]
How to: https://github.com/flathub/flathub/wiki/App-Submission

We must fulfill these requirements: https://github.com/flathub/flathub/wiki/App-Requirements

Which name do we want to use? Currently it is "org.phoenicis.javafx". It might be hard to change this later on.

**Comment by qparis** [comment]
javafx is not a good name. It is a technical library and the user does not really care about this.

We need to rename this pretty much everywhere where it is used.

**Comment by qparis** [comment]
Why not .org.phoenicis?

**Comment by plata** [comment]
Isn't that a bit too generic? How would you name cli? Or any other GUI (e.g. Qt) that someone might develop?

**Comment by qparis** [comment]
yes GUI is also nice

**Comment by plata** [comment]
So org.phoenicis.gui? What if there are other GUIs as well?

**Comment by plata** [comment]
Done: https://github.com/flathub/org.phoenicis.playonlinux
