### ISSUE TITLE
Re-add module-info.java

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1648]
IntelliJ should work with: https://www.jetbrains.com/help/idea/compiler-excludes.html

**Comment by qparis** [comment]
I'm not sure we should ignore IntelliJ errors if they are shown.

**Comment by plata** [comment]
The problem is: This "error" is caused because our dependencies are no proper modules. In maven we do not use modules so it doesn't matter. However, if the `module-info.java` exists, IntelliJ tries to use it internally.

**Comment by qparis** [comment]
This is exactly why I think we are not using modules properly...

**Comment by plata** [comment]
It's not our fault. The dependencies have to do it.

**Comment by qparis** [comment]
What is the point of using modules if we cannot use them properly?

**Comment by plata** [comment]
Currently none really. But like @madoar said, it's the way to go for the future. And as we have the module-info already, we should not simply throw it away.

**Comment by qparis** [comment]
I know, but this is not a sufficient argument when it creates more problems that it solves...

**Comment by plata** [comment]
So we keep it as it is and dig it out in the git history?

**Comment by qparis** [comment]
Maybe we can put the files somewhere so that we can having them. But updating these file will take time and I'm not sure it has a huge value
