### ISSUE TITLE
Container is unreadable if user.reg does not exist 

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1655]
### Steps to reproduce
* Create a container
* Remove user.reg 

An exception is thrown when trying to open the side panel

**Comment by qparis** [comment]
I agree, but sometimes is does not for some reason (prefix broken, bad user manipulation, etc...). In this case, we should handle it properly so that the user can at least delete or repair the prefix

**Comment by plata** [comment]
So show e.g. only info tab with delete button?

**Comment by qparis** [comment]
Or a message like "the prefix is broken, do you want to try to repair it?"
