### ISSUE TITLE
playonmac version number broken

### ISSUE THREAD

**Issue by core-code** [PhoenicisOrg/phoenicis#1665]
i've downloaded Version '4.3.4' but when selecting it in the Finder and using 'Get Info' it claims to be Version '4.1'

 the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are broken

**Comment by qparis** [comment]
It seems that you are correct. Is it a blocker for you?

**Comment by core-code** [comment]
its surely not a blocker but correct version information would be preferable for a number of reasons ;)

**Comment by qparis** [comment]
We will fix it :) Thanks a lot

**Comment by core-code** [comment]
thanks!

**Comment by qparis** [comment]
Fixed!

**Comment by core-code** [comment]
many thanks! i'll keep an eye on it. if the version numbers stay correct, i'll be able to keep playonmac up-to-date in Homebrew-Cask, which should be of help to some of your users and maybe attract a few new ones ;)

**Comment by qparis** [comment]
I was not aware of that! Many thanks
