### ISSUE TITLE
Decide on application names

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1666]
see also #1638

We need names for
- Phoenicis CLI
- Phoenicis JavaFX

Especially "JavaFX" shall not be used because it's implementation details which are not interesting for/should not be exposed to the user.

Suggestions so far:
- "Alpha" or "Ankaa" (see https://en.wikipedia.org/wiki/Alpha_Phoenicis)
- "App"
- "GUI"

Personally, I don't really like "App" or "GUI" because it is very generic. So e.g. what happens if other GUIs are developed?
On the other hand, we could argue that "Phoenicis JavaFX" is **the** Phoenicis application and then use the naming:
- "Phoenicis" (org.phoenicis.app)
- "Phoenicis CLI" (org.phoenicis.cli)

**Comment by qparis** [comment]
I’d like to have your opinion. 
I also think that JavaFX is not abstract enough. We could have one day a POLv6 with a completely different technology.

Maybe we could do something like


org.phoenicis => organisation 
org.phoenicis.app => app
org.phoenicis.app.cli
org.phoenicis.app.gui => prefered ui (JavaFX at the moment)
org.phoenicis.app.gui.javafx
org.phoenicis.app.gtk 

Etc...

**Comment by madoar** [comment]
I have always understood "Phoenicis" as the brand name for POL/POM 5.
This understanding includes, that a possible future POL/POM 6 will have a different brand name than Phoenicis.

About adding `app` to the application name/path:
I don't think that it is necessary, I mean we're only releasing applications, so we don't need it in my opinion.

I think we should use the suffix `gui` or `javafx` for the JavaFX client and `cli` for the CLI.

**Comment by qparis** [comment]
> I have always understood "Phoenicis" as the brand name for POL/POM 5.
> This understanding includes, that a possible future POL/POM 6 will have a different brand name than Phoenicis.
> 

Good point 

> About adding `app` to the application name/path:
> I don't think that it is necessary, I mean we're only releasing applications, so we don't need it in my opinion.
> 
> I think we should use the suffix `gui` or `javafx` for the JavaFX client and `cli` for the CLI.

What about winebuild and the website?

**Comment by madoar** [comment]
Are we talking about generic names we want to use as our package paths or for our releases on platforms like flathub?

For platforms like flathub I would suggest a simple scheme like I've suggested above.
For package paths you're right, we'll need a more complex scheme, here I agree to add `app` for user applications, but again is the website an application or something different? 
I mean you can't really execute the website, right?

**Comment by qparis** [comment]
Yes we need to clarify this first

**Comment by plata** [comment]
As we have discussed some time ago, we wanted a strong brand (Phoenicis) which makes it clear that all the parts (PoL, PoM, scripts, winebuild...) belong to the same ecosystem. With that respect I don't think it would be a good idea to use a different name for future versions. So in my opinion, Phoenicis is the organization/ecosystem.

**Comment by qparis** [comment]
Sounds good to me.
What is the name of the program then?

**Comment by plata** [comment]
Just "Phoenicis" (org.phoenicis.app) like I suggested in the description? So depending on the flavor "Phoenicis PoL 5.0", "Phoenicis PoM 7.3"...
This would imply a very strong linkage between the organization and what is currently called "Phoenicis JavaFX", i.e. the GUI is really in the center of what Phoenicis is all about and the rest is more or less "only" belonging to the ecosystem.

If we don't want this strong linkage, we need a separate name. Let's say we would use "Alpha". Then we get: "Phoenicis PlayOnLinux 5.0 Alpha". Might be a bit too long and complicated.

**Comment by qparis** [comment]
I like this.

**Comment by plata** [comment]
Ok. I will provide a PR which adjusts the flatpak accordingly.

@madoar is it also ok for you?

**Comment by madoar** [comment]
I'm fine with the suggestion.

**Comment by madoar** [comment]
I wouldn't suggest using the term Alpha in the name, because it could be associated with an alpha version, which isn't intended.

**Comment by plata** [comment]
Ok. @qparis can you consider this for the deb as well?

**Comment by plata** [comment]
I don't see any. Only the menu entry will be called "Phoenicis PlayOnLinux" instead of "Phoenicis JavaFX".

**Comment by qparis** [comment]
@plata Is this ticket done?

**Comment by plata** [comment]
Yes.
