### ISSUE TITLE
Provide screenshot without padding

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1667]
Currently I'm using https://phoenicis.org/ui/phoenicis_screenshot.png for the flatpak but `appstream-util` complains that it has padding.
If possible, it should not be bigger than 1600x900.

**Comment by qparis** [comment]
This is a macOS screenshot we should use a Linux screenshot

**Comment by plata** [comment]
Can you upload a screenshot (or multiple)? Preferably in English.

**Comment by qparis** [comment]
Yes. Maybe we can ask any people to upload some screenshots and decide which one we use

**Comment by plata** [comment]
Ok. Right now it's not that critical. I just need something to put in the appdata.xml for flatpak. If I can get that fixed while you're still working on the deb, I might really be able to get feedback for the alpha-2 flatpak on flathub.

**Comment by qparis** [comment]
Do you have any screenshot in the case? My Ubuntu installation is broken, I'm reinstalling it

**Comment by plata** [comment]
![apps standard](https://user-images.githubusercontent.com/3973260/50538511-29159100-0b71-11e9-8afc-2b22b8cf71d1.png)

![apps breeze dark](https://user-images.githubusercontent.com/3973260/50538506-169b5780-0b71-11e9-8852-2edce5aff25c.png)

![apps mint-x](https://user-images.githubusercontent.com/3973260/50538591-f029ec00-0b71-11e9-9f11-5c688772661c.png)

![apps unity](https://user-images.githubusercontent.com/3973260/50538651-abeb1b80-0b72-11e9-9126-f80260b47c3e.png)

![app details](https://user-images.githubusercontent.com/3973260/50538661-d9d06000-0b72-11e9-9552-1975e8768a87.png)

![engines](https://user-images.githubusercontent.com/3973260/50538635-86f6a880-0b72-11e9-808a-398c6d7b0511.png)

![installation](https://user-images.githubusercontent.com/3973260/50538665-f2407a80-0b72-11e9-90b4-da3f1a3041c2.png)

![settings](https://user-images.githubusercontent.com/3973260/50538637-95dd5b00-0b72-11e9-8912-ecda3baced97.png)

**Comment by qparis** [comment]
Seems perfect

**Comment by plata** [comment]
I've added a screenshot of the library.

**Comment by qparis** [comment]
@plata Can we close this issue?

**Comment by plata** [comment]
Yes.
