### ISSUE TITLE
Install app's verbs into existing container

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1671]
Imagine (real scenario) that you want to have for example StarCraft 1 and Warcraft 3 in same container. So then you will create custom container using local installer and you will install Battle net client, then you will install StarCraft 1 and then you will find that Phoenicis supports Warcraft 3, but you don't know which verbs to install to get it running.

So at the moment always if I want to install something I have to go to https://github.com/PhoenicisOrg/scripts and find that app and look which verbs it requires and then I have to install it manually.

It would be great if you had somewhere option like **Install these verbs for this container** button, and it would take required verbs for specific app and applies them into specific container.

I hope you understand me :)

**Comment by plata** [comment]
If you think about it, what you propose in the end is: Run a script installation without using the script. I don't think that makes much sense. If you want to have the benefits of a script installation, use the script.

To achieve what you want to do I think the better solution would be:
- clone the scripts repository
- change it such that Warcraft 3 uses the same container as StarCraft 1
- run the changed script

**Comment by qparis** [comment]
First thing: why do you need to have Starcraft and warcraft in the same container?

**Comment by t0msk** [comment]
@qparis Because I don't want to have container for every game, imagine that I want to install old games which have about 100MB, I don't want to create new container for every new 100MB game.

**Comment by qparis** [comment]
> @qparis Because I don't want to have container for every game, imagine that I want to install old games which have about 100MB, I don't want to create new container for every new 100MB game.

Then, you belongs to the of _advanced users_ and we estimate that you are totally able to use verbs. We really don't want to make the interface more complicated for the small amount of people that have advanced needs

**Comment by t0msk** [comment]
@qparis Yes, I know how to find and install verbs (I just look into installation script), but it is tedious.

**Comment by madoar** [comment]
@t0msk the main problem with your request is, that the scripts contain no section where the script developer specifies which verbs a script requires/uses.
Instead the developer specifies this information inside the script code using commands.
This makes it really hard for us to identify the used verbs without executing the script itself, which is not what you want I think.

**Comment by plata** [comment]
Won't fix.
