### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1673]
Resource repo:
- https://github.com/PhoenicisOrg/resources

Icons on GitHub:
- https://github.com/organizations/PhoenicisOrg/settings/profile
- https://github.com/PhoenicisBot

Crowdin

**Comment by madoar** [comment]
I must say that I like the different icon for @PhoenicisBot

**Comment by plata** [comment]
@qparis can you please do this (or at least the svg in the resources repo)?

**Comment by Kreyren** [comment]
if my opinion matter i don't like it.. it's too spherical limiting it's effective usecase to be used as a logo -> more likely as a icon.. We shouldn't focus on a frontend/presentation much when we are in alpha.. Things might change and this might end up as wasted effort.

**Comment by plata** [comment]
@Kreyren the problem is that the logo is currently used in several places but we do not have the SVG of it. This is not a good state.

**Comment by qparis** [comment]
I think we have it. It is inside Phoencis project though

**Comment by plata** [comment]
I cannot find it.

**Comment by qparis** [comment]
https://github.com/PhoenicisOrg/phoenicis/tree/master/phoenicis-dist/src/resources

**Comment by plata** [comment]
Ok. I will add it to the resources repo.

**Comment by plata** [comment]
Done.
