### ISSUE TITLE
[i18n] en source strings case style

### ISSUE THREAD

**Issue by ovari** [PhoenicisOrg/phoenicis#1680]
https://en.wikipedia.org/wiki/Letter_case#All_lowercase
**A comparison of various case styles (from most to least capitals used)**
![image](https://user-images.githubusercontent.com/17465872/50557407-f6b69000-0d38-11e9-845e-1b8d645414e5.png)

Strings used in Mozilla Applications
https://transvision.mozfr.org/

What do you think?

**Comment by plata** [comment]
So we have the same opinion.
