### ISSUE TITLE
Feedback: Build is failing

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1694]
https://pastebin.com/34KPmere - Release is failing
https://pastebin.com/HLN5qeW6 - Master is failing

Using `dev-java/maven-bin-3.6.0`

https://paste.pound-python.org/show/JCL0XAiAje79S3Tp9gjT/ - Release is failing 

Using `dev-java/maven-bin-3.3.3-r1`

*Give up*

Recommends adding expected maven version in readme.

**Comment by plata** [comment]
I'm using Maven 3.6.0 so that should be fine. Which JDK version do you use (you need at least 10)?

**Comment by Kreyren** [comment]
@plata `dev-java/maven-bin-3.6.0` fails on release.

https://paste.pound-python.org/show/xmoPvP7mq7urfqSxKWab/

**Comment by Kreyren** [comment]
Noticed #1695 redownloading source

**Comment by Kreyren** [comment]
Redownloaded master, fails on `dev-java/maven-bin3.6.0`

https://paste.pound-python.org/show/pgSaH7Mgg6gqMsbb15WI/

**Comment by qparis** [comment]
does the directory i18n exists?

**Comment by Kreyren** [comment]
@qparis it does https://paste.pound-python.org/show/RwT7Ac41VmBa6fnK65yY/

**Comment by madoar** [comment]
Can you please run `mvn clean package -X`?
This will add debug output

**Comment by Kreyren** [comment]
kreyren@dreamon ~/phoenicis $ wgetpaste -c "mvn clean packge -X"
https://paste.pound-python.org/show/UYW5tPxL5NzUDbZj3qLj/

**Comment by Kreyren** [comment]
List of installed packages: https://paste.pound-python.org/show/UEj3tdPWR6Ie3jLrb2xn/

**Comment by qparis** [comment]
You mispelled package

**Comment by madoar** [comment]
You have a typing error in the command, it must be `package` not `packge`

**Comment by Kreyren** [comment]
sorry new debug: https://paste.pound-python.org/show/buf9WgVQUUahNJJ813Zc/

redownloading master

**Comment by Kreyren** [comment]
debug on redownloaded https://paste.pound-python.org/show/lvkyxgQRZ3uphPEeAfEw/

**Comment by qparis** [comment]
Do you have the permission to write on keys.pot?

**Comment by Kreyren** [comment]
@qparis permission to write where? Is invoking as root sane?

**Comment by madoar** [comment]
`/home/kreyren/phoenicis/i18n/keys.pot`

**Comment by madoar** [comment]
Maven (`mvn`) needs write access on this file to update the translations

**Comment by qparis** [comment]
> Is invoking as root sane?

Avoid that. You'll just cause even more troubles

**Comment by Kreyren** [comment]
@madoar 
`kreyren@dreamon ~/phoenicis $ ls -la i18n/keys.pot 
-rw-r--r-- 1 root root 24816 Jan  1 22:08 i18n/keys.pot`

Seems that it's owned by root, `chown` it?

**Comment by Kreyren** [comment]
Note: `mvn`  wasn't invoked as root on this system

**Comment by madoar** [comment]
Yeah that's the problem.
The same user invoking `mvn` should own the file, even better the whole folder containing the project.

**Comment by qparis** [comment]
> @madoar
> 
> ```
> kreyren@dreamon ~/phoenicis $ ls -la i18n/keys.pot 
> 
> -rw-r--r-- 1 root root 24816 Jan  1 22:08 i18n/keys.pot
> ```
> 
> Seems that it's owned by root, `chown` it?

Seems that you extracted the archive as root

**Comment by Kreyren** [comment]
note: also git was invoked as non-root.

```
kreyren@dreamon ~ $ git clone git@github.com:PhoenicisOrg/phoenicis.git
Cloning into 'phoenicis'...
Enter passphrase for key '/root/.ssh/id_rsa': 
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 38675 (delta 20), reused 29 (delta 8), pack-reused 38585
Receiving objects: 100% (38675/38675), 16.12 MiB | 5.75 MiB/s, done.
Resolving deltas: 100% (18883/18883), done.
kreyren@dreamon ~ $ cd phoenicis/
kreyren@dreamon ~/phoenicis $ wgetpaste -c "mvn clean package -X"
https://paste.pound-python.org/show/lvkyxgQRZ3uphPEeAfEw/
kreyren@dreamon ~/phoenicis $ ls -la i18n/keys.pot 
-rw-r--r-- 1 root root 24816 Jan  1 22:08 i18n/keys.pot
```

**Comment by qparis** [comment]
`Enter passphrase for key '/root/.ssh/id_rsa': `

How is that possible?

**Comment by Kreyren** [comment]
sufficient? https://paste.pound-python.org/show/M49OChspRXnrFCNjeP69/

**Comment by Kreyren** [comment]
qparis: git clone from upstream it asked for ssh key

**Comment by qparis** [comment]
> sufficient? https://paste.pound-python.org/show/M49OChspRXnrFCNjeP69/

Should be

> qparis: git clone from upstream it asked for ssh key

Yes but it's taking the key inside root home's directory. It means that the git process is somehow running as root. You should really check what's happening here

**Comment by qparis** [comment]
(I'm just adding the invalid label so that we know that it has nothing to do with phoenicis)

**Comment by Kreyren** [comment]
will check, thanks for info

**Comment by qparis** [comment]
Is the problem solved?

**Comment by Kreyren** [comment]
There was power shortage (in a city) now will verify in +- 5 min (needs to re-launch deamons)

**Comment by Kreyren** [comment]
Still failing with chown https://paste.pound-python.org/show/u2hbIGj3L8R1I2rrqtfc/

i had alias for git to be invoked as sudo in .bashrc that i forgott about, sorry about that -> git was invoked using sudo. It is fixed in .bashrc now

forked phoenicis and git clone from local still results in root permission
https://paste.pound-python.org/show/iP7U7j7oTN4bmcPwnjHC/

checking

**Comment by qparis** [comment]
I think your workspace is messed up. Try to clean everything:
Delete .m2 directory inside your home directory
Clone phoenicis *not as root* 
Run mvn clean package

**Comment by Kreyren** [comment]
Sorry noticed that non-root ssh is outdated, recreated it:

https://paste.pound-python.org/show/3jSMNZsFtnhBMIo13AvE/

https://paste.pound-python.org/show/ntTAhlgdzluWq7CuquSI/

encountered same issue

**Comment by Kreyren** [comment]
debug: 

kreyren@dreamon ~/phoenicis $ wgetpaste -c "mvn clean package -X"
https://paste.pound-python.org/show/iV32tjNEsUnTIo0Lhrda/

**Comment by qparis** [comment]
.m2 dir does exist, it is just hidden I think. Or, maven has no permission to create a directory in your home, which could explain the problem

**Comment by Kreyren** [comment]
edit: i didn't re-cd to home -> `.m2` is present and contains repository.

**Comment by Kreyren** [comment]
Permission for `/home/$USER/.m2` is for non-root and it's group

```
kreyren@dreamon ~/.m2 $ ls -la
total 12
drwxr-xr-x  3 kreyren kreyren   24 Jan  1 21:57 .
drwxr-xr-x 46 kreyren kreyren 4096 Jan  1 23:00 ..
drwxr-xr-x 26 kreyren kreyren 4096 Jan  1 22:19 repository
```

**Comment by Kreyren** [comment]
removed .m2 and reinvoked maven in phoenicis, waiting for result

**Comment by qparis** [comment]
> Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /opt/icedtea-bin-3.9.0/jre

> invalid target release: 1.10 -> [Help 1]

You need at least JDK 10 (11 is better) to build the project.

- Download it here: https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz
- Extract it
- Set JAVA_HOME to the path where it is extracted with the command export JAVA_HOME="/path/to/java_11"
- Run maven again 

Should work then

**Comment by plata** [comment]
This is in the documentation and in my first comment...

**Comment by Kreyren** [comment]
@plata i know i've responded on it https://github.com/PhoenicisOrg/phoenicis/issues/1694#issuecomment-450760474 (virtual/JDK installed)

i've (re)emerged:
`dev-java/openjdk-11.0.1_p13` -> master failing 
`dev-java/openjdk-bin-11.0.1_p13` -> master failing
`dev-java/openjdk-bin-11_p28` -> master failing

```Download it here: https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz```

it seems that ebuilds provide the same file https://packages.gentoo.org/packages/dev-java/openjdk it's possible that i'm missing JVM.. emerged them and the build is still failing..

I would rather avoid installing java from precompiled source on my system. What distro did you use to compile it? I try it in VM

**Comment by qparis** [comment]
Set JAVA_HOME to the right Java Path (Java 11). You have java 8 installed on your system and it is currently used by default

**Comment by Kreyren** [comment]
Current packages: https://paste.pound-python.org/show/yYApkiBipNbcMrFaGgER/

ebuild is using `JDK_HOME` which points to `/etc/java-config-2/current-system-vm` https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-java/openjdk/openjdk-11.0.1_p13.ebuild#n126

Should i try seting `JAVA_HOME` for `/etc/java-config-2/current-system-vm` ?

Asking for clarification on #gentoo-java

**Comment by qparis** [comment]
What is inside /etc/java-config-2/current-system-vm?

**Comment by Kreyren** [comment]
![image](https://user-images.githubusercontent.com/11302521/50607469-390ad900-0ec1-11e9-9186-3e7aa1a1d570.png)

**Comment by qparis** [comment]
Binaries inside etc?

What does /etc/java-config-2/current-system-vm/bin/java -version do?

**Comment by Kreyren** [comment]
```
kreyren@dreamon ~ $ /etc/java-config-2/current-system-vm/bin/java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (IcedTea 3.9.0) (Gentoo icedtea-3.9.0)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

![image](https://user-images.githubusercontent.com/11302521/50607563-8e46ea80-0ec1-11e9-86d2-407912f54f96.png)

**Comment by qparis** [comment]
`kreyren@dreamon ~ $ /etc/java-config-2/current-system-vm/bin/java -version
openjdk version "1.8.0_181"`

So you are using Java 1.8, not Java 11

**Comment by Kreyren** [comment]
Solved:  invoking `export JAVA_HOME="/usr/lib64/openjdk-11"`

affected by https://bugs.gentoo.org/672330 

@plata @qparis Thanks for help, appreciated

**Comment by Kreyren** [comment]
btw. readme has wrong name? 

![image](https://user-images.githubusercontent.com/11302521/50608702-4fb32f00-0ec5-11e9-9285-80dfeb5422c2.png)

**Comment by qparis** [comment]
Hum no, flatpak is something else.. 
If you just want to run phoenicis, what you need to do is run mvn exec:java inside the module phoenicis-javafx. 
If you want, you can also create a package

**Comment by qparis** [comment]
You may need to run mvn install inside phoenicis/ before

**Comment by Kreyren** [comment]
trying, `mvn install` closed i3 GUI, closes terminal and hexchat?,

restarted I3, reopened terminal and reinvoked `mvn install` results in err, 

JAVA_HOME was wrong reinvoked `export JAVA_HOME="/usr/lib64/openjdk-11"`

redownloaded master, compiled, `#phoenicis_dir/phoenicis-dist/target/phoenicis-dist.zip` is not present.

![image](https://user-images.githubusercontent.com/11302521/50609528-da952900-0ec7-11e9-868b-2cf05a34c25b.png)

Executing `mvn exec:java`

Results in https://paste.pound-python.org/show/y1p24JAt6wK1UgZnU3GG/

Will invoke mvn install in root of phoenicis

**Comment by qparis** [comment]
Fell free to create a merge request :)

**Comment by Kreyren** [comment]
Recommends closing #1694
