### ISSUE TITLE
[i18n] string are cut-off

### ISSUE THREAD

**Issue by ovari** [PhoenicisOrg/phoenicis#1701]
### Expected behavior
![kep](https://user-images.githubusercontent.com/17465872/50585203-fac4e800-0ec7-11e9-976e-edb7e6e74db2.png)

### Actual behavior
![kep](https://user-images.githubusercontent.com/17465872/50585043-34e1ba00-0ec7-11e9-8ee5-500e2464f16b.png)

### Steps to reproduce
1. Set the DE language region to Hungarian
2. Open POL5
3. Click BeállÍtások
4. Click Adattárolók
5. Click Hozzáadás
6. Window opens as shown in the image below with the string cut-off
a) `Adattárolók tÍp...`
b) `Válassza ki az adattároló tÍpus amit syeretne hozzáa...`
POL5 should open the windows so that, if possible, the strings are shown entirely.

What do you think?

Thank you

### System information
Version: 5.0-alpha-2:unknown
Git: 84a508c68c2a48d24ae99fd09492be37badce66c:unknown
Linux Mint 19 CInnamon

**Comment by plata** [comment]
It's a general issue (not only for Hungarian).
