### ISSUE TITLE
Czech translate for phoenicis

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1709]
Requesitng to add Czech Translate in https://crowdin.com/project/phoenicis

Reference: https://www.playonlinux.com/en/topic-16037-Translate_in_to_Czech.html

**Comment by madoar** [comment]
Done :)

**Comment by Kreyren** [comment]
86% done 

![image](https://user-images.githubusercontent.com/11302521/50624124-cb889800-0f14-11e9-88ae-bada0325bac8.png)

**Comment by Kreyren** [comment]
@plata i've translated 3 pages on https://crowdin.com/project/phoenicis if there is some other repository please share a link since i'm unable to find it o.o

**Comment by plata** [comment]
https://crowdin.com/project/phoenicis-scripts/cs#
