### ISSUE TITLE
Abstract: Test script locally

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1711]
Suggesting to add a way for phoenis to allow **testing scripts locally** for a development ideally by using `phoenicis <path/to/script>` in terminal.

**Comment by madoar** [comment]
What do you mean by `testing`?
Do you mean executing the script or testing it for validity?

**Comment by Kreyren** [comment]
@madoar meaning to invoke the installer script in phoenicis after it was modified locally.

**Comment by madoar** [comment]
We previously had such a feature where you could directly select a script file and "execute" it.
The problem with this feature was, that required context information was missing.
For example the miniature image shown in the library after the installation has succeeded.
Therefore we disabled the feature for the moment.

Currently the suggested approach is to simply create your own local script repository.
For this you would normally fork the official script repository and then clone it.
Afterwards you can add it to your Phoenicis installation via `Settings -> Repositories -> Add -> Local Repository`.
Whenever you've done some changes to your local repository you then either need to restart Phoenicis or click on `Settings -> Repositories -> Refresh Repositories` to apply the changes to your local repository.

When adding your own repository to Phoenicis try to give it the highest priority in `Settings -> Repositories` by dragging it to the top of the list.

**Comment by plata** [comment]
Yes, local repository is the way to go (like described in https://phoenicisorg.github.io/scripts/General/best-practices/). Apparently, this is not clear enough. Should we point it out in the scripts README?

**Comment by madoar** [comment]
What I'm missing in the `best practices` section is the goal you achieve by following these steps.
I agree it may be a good idea to mention the approach in the README.

**Comment by madoar** [comment]
Maybe something like:

```
When writing your own script you'll need to test it.
To test a script Phoenicis doesn't only require the script, but also some context information.
For example a miniature image used in the library after the script has been installed.
Some other context information is extracted by Phoenicis via the directory structure, the script is located in.

Therefore to test a script it needs to be embedded inside a repository.
For this a local repository, which is based on the official script repository, is recommended.
To setup your own local repository follow the following steps:
...
```

**Comment by plata** [comment]
Can you make a PR (also with a link to this documentation page in the README)?

**Comment by plata** [comment]
Or maybe we should just add 2 steps to the README:
1. Clone scripts repo
2. set it as repository in software (link to respective Phoenicis documentation)

**Comment by madoar** [comment]
Ok, so I create a PR with the documentation update and you create another one for the README update?^^

**Comment by plata** [comment]
Deal ;)

**Comment by Kreyren** [comment]
That was fast :D thanks ^^
