### ISSUE TITLE
Phoenicis makes a blank dir/file while installing wineapps.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1714]
On https://youtu.be/Spr2jFWmhwU?t=265 bottom-left

Phoenicis makes a blank dir/file in `'/home/kreyren/.Phoenicis/containers//wineprefix//Overwatch//drive_c/windows/` 

Suspect missing variable

### Steps to reproduce
Install anything on phoenicis, check output for where is wineprefix created.

### Expected
To make a file/dir with a name.

### System information
https://paste.pound-python.org/show/eiOAOO1Ve7mDaflVl7ka/
*more info on demand*

**Comment by Kreyren** [comment]
Related: https://github.com/PhoenicisOrg/scripts/pull/783

**Comment by plata** [comment]
Can you verify that this is a general issue? Does it happen also for other scripts (e.g. Notepad++)?

**Comment by Kreyren** [comment]
@plata present on Notepad++ too https://youtu.be/09jyAl4WPAE

**Comment by plata** [comment]
Please, these videos do not help. Nobody will watch a 30min video to find an issue. What we need are logs/error messages. The image above is a normal Wine message.

**Comment by Kreyren** [comment]
@plata typo on video, added screenshot.

**Comment by plata** [comment]
Like I said, the screenshot is normal behavior. It might take some time but then the window should close and the installation should continue.

**Comment by Kreyren** [comment]
@plata Noted, i wanted to provide both, but decided just on screenshot.. 

the window closes and the installation proceeds, but it doesn't seem sane to me since it's trying to reach blank path?

**Comment by plata** [comment]
Can you show some logs or error messages which show what doesn't work?

**Comment by Kreyren** [comment]
@plata requesting instructions

**Comment by plata** [comment]
Just run Phoenicis from command line. If something goes wrong, you should get an error message.

**Comment by Kreyren** [comment]
More info to why is it expected behavior?

**Comment by plata** [comment]
The screenshot just shows that Wine is creating a prefix. You will get the same with plain Wine.

**Comment by Kreyren** [comment]
@plata My plain wine points to `/home/kreyren/.wine` usually i never notice any blank dirs/files..

**Comment by plata** [comment]
It should behave the same if you do something like
```
WINEPREFIX="$HOME/myprefix" wine wineboot
```

**Comment by Kreyren** [comment]
Results in 
![image](https://user-images.githubusercontent.com/11302521/50689687-a2eec400-1022-11e9-8a3a-652d6c8bf11f.png)

**Comment by plata** [comment]
Like I said, normal behavior.

**Comment by plata** [comment]
@Kreyren is this still valid? Otherwise we should close the issue.

**Comment by Kreyren** [comment]
@plata Well the output is still same which seems insane to me (not present in system wine), but it seems to work. 

I don't know how phoenicis handles wine so it's up to you to decide.

**Comment by plata** [comment]
If it's working, I don't see a reason to do anything about it.

**Comment by Kreyren** [comment]
meh, fair enough
