### ISSUE TITLE
Restore default repository is not working

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1717]
Restore default repository is not working

Expected to restart repositories in default, clicking does nothing.

Reference: #997

![image](https://user-images.githubusercontent.com/11302521/50688829-1a225900-101f-11e9-9e9b-4033f3659126.png)

EDIT: button does nothing, but if phoenicis is restarted the repositories are set to default, recommends adding some kind of feedback for the user to inform that it was restored to default?

**Comment by plata** [comment]
The button explicitly states "requires restart". So yes, you have to restart Phoenicis so that this takes effect.

**Comment by plata** [comment]
@madoar do we still require this or could it be replaced by `triggerRepositoryChange`?

**Comment by madoar** [comment]
I think we don't need it anymore, but I'm not 100% sure

**Comment by plata** [comment]
Could you have a look? I think you're more familiar with this than I am.

**Comment by madoar** [comment]
Yes, but it will take a while. I want to implement/fix some other stuff for Phoenicis first.

**Comment by plata** [comment]
Ok.

**Comment by Kreyren** [comment]
> The button explicitly states "requires restart". So yes, you have to restart Phoenicis so that this takes effect.

Noted, but i meant that the button seems to be doing nothing.. Some feedback to inform the user that something happened would be helpfull..

**Comment by Kreyren** [comment]
i'm not sure how.. i still have zero experience with java.. Someone more qualified should probably do that.. O.o
