### ISSUE TITLE
Minor: Description for organization.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1721]
Recommends adding a description for PhoenicisOrg: 
![image](https://user-images.githubusercontent.com/11302521/50715209-1cfb6900-1074-11e9-97cf-11385d9dd723.png)

### Expected behavior
New users to know what phoenicis is?

### Actual behavior
Probably missleading if you don't know the context from playonlinux.

**Comment by plata** [comment]
Suggestions?

@qparis @madoar what could we write?

**Comment by Kreyren** [comment]
`Compatibility layer manager written in java`

**Comment by madoar** [comment]
@plata hmmm, I'm not sure.
I think we should write something about the goals of the organization (PhoenicisOrg).
I don't think it is a good idea to concentrate too much on a single project maintained/developed by the organization.

I think our goals basically consist of the development of the following projects:
- Phoenicis POL/POM 5 (`phoenicis` + `scripts`)
- a build system for wine distributions (`phoenicis-winebuild`)
- and later on a set of support projects, which may develop to individual projects (basically discussed in #1101)

**Comment by plata** [comment]
I agree. How can we make a description out of that? Maybe we should come up with some motto? Like "Wine in a blink" (you know blink because of "Phoenicis" referring to stars :P).

@qparis what do you think about this?

**Comment by qparis** [comment]
I like the idea

**Comment by plata** [comment]
What exactly? Adding a description? Using a motto? Using the motto I suggested?

**Comment by qparis** [comment]
I like your suggestion

**Comment by plata** [comment]
Ok. @madoar what do you think?

**Comment by Kreyren** [comment]
`Wine in a blink` seems childish if you ask me :thinking:

**Comment by plata** [comment]
The inaccurate is true. However, any motto will probably be that. To be honest, I don't think it's childish. Maybe with a twinkle, yes.

**Comment by Kreyren** [comment]
@plata Well you can use something alike `Compatibility layer manager reborn from ashes` or something alike as a reference to phoenix which is on the logo.

**Comment by qparis** [comment]
Ashes... seriously

**Comment by Kreyren** [comment]
@qparis why not? O.o

**Comment by qparis** [comment]
Because you are just saying that the project were "ashes". In terms of communication, this is not the best idea. Even though we were not as active as in the past during the last years, POLv5 has been developed, we were continuing to provide wine builds for linux and macOS, we continuing to provide the hosting.

Wine in a blink is good for the moment

**Comment by Kreyren** [comment]
@qparis Well considering the nature of phoenix i would say that it's good idea :thinking: Meant no offence towards POL aldo i never made it to work on my system >.>

**Comment by madoar** [comment]
@qparis, @plata I'm fine with `Wine in a blink`.

**Comment by plata** [comment]
Done.
