### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1724]
https://i.imgur.com/tetbWny.png

### Actual behavior
Package Version == 5.0-alpha.2

### Expected behavior
Package Version == 5.0.2-alpha

please, make my life easier to provide compatibility for gentoo so that i could bump the version just by renaming file everytime it's updated which then i can greb from github using deamon and make the version bump automatic.. :<

**Comment by Kreyren** [comment]
5.0.2-alpha would be ideall..

5.0.2-alpha-rc2 is also good (i can greb the revision from the file name)

**Comment by qparis** [comment]
5.0.2-alpha means "first alpha version of 5.0.2" (so, after 5.0.0) 
5.0-alpha-2 means "second alpha version of 5.0.0", (so, before 5.0.0) 
5.0_alpha-rc2 would be "release candidate to of alpha", but alpha alone would never be released. 

So these proposition do not correspond to the same thing

**Comment by Kreyren** [comment]
ok.. i adapt the ebuild for it then

**Comment by qparis** [comment]
I think we can c’ose

**Comment by Kreyren** [comment]
Yep sorry, should close myself i found a solution already.
