### ISSUE TITLE
Directory Listing: Hidden directories should be ignored

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1733]
<img width="1313" alt="capture d ecran 2019-01-06 a 11 10 26" src="https://user-images.githubusercontent.com/373645/50734730-be350d00-11a3-11e9-84c2-f3e615e32f3f.png">

**Comment by plata** [comment]
Should we ignore all hidden directories?

**Comment by qparis** [comment]
Maybe yes

**Comment by madoar** [comment]
We can think about defining a set of illegal characters for container names.
If such a character is detected inside a container name it is ignored.
