### ISSUE TITLE
Deb file not generated

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/phoenicis#1737]
Hello, I just downloaded newest master from github and built it (build was success, no errors) using `mvn clean package` and deb file wasn't generated under `phoenicis-dist/target`.

**Comment by qparis** [comment]
Hello, You need to run phoencis_create_package script

**Comment by t0msk** [comment]
@qparis and where is that script?

**Comment by t0msk** [comment]
I have:
```
tomsk@tomsk-Ntb:/opt/Build/Phoenicis/phoenicis-dist/src/scripts$ sudo apt install openjdk-11-jre-headless 
[sudo] password for tomsk: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjdk-11-jre-headless is already the newest version (10.0.2+13-1ubuntu0.18.04.4).
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

**Comment by qparis** [comment]
This does not seem to be a java version

**Comment by t0msk** [comment]
There is nothing newer:
```
tomsk@tomsk-Ntb:/opt/Build/Phoenicis/phoenicis-dist/src/scripts$ sudo apt install openjdk-
openjdk-11-dbg           openjdk-11-jdk-headless  openjdk-11-source        openjdk-8-jdk            openjdk-8-jre-headless
openjdk-11-demo          openjdk-11-jre           openjdk-8-dbg            openjdk-8-jdk-headless   openjdk-8-jre-zero
openjdk-11-doc           openjdk-11-jre-headless  openjdk-8-demo           openjdk-8-jre            openjdk-8-source
openjdk-11-jdk           openjdk-11-jre-zero      openjdk-8-doc            openjdk-8-jre-dcevm      

```

**Comment by qparis** [comment]
Type java -version

**Comment by t0msk** [comment]
```
tomsk@tomsk-Ntb:/opt/Build/Phoenicis/phoenicis-dist/src/scripts$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```

**Comment by qparis** [comment]
This is a Java 10 version ^^

**Comment by t0msk** [comment]
But it is named in repo as version 11, and in my other notebook I had this version installed too and it worked.

**Comment by qparis** [comment]
In fact it is a java 10 binary (read the other ticket to get more info). It is sufficient enough to run Phoenicis, but not to build the standalone package

**Comment by t0msk** [comment]
So what should I do (because it is not in repo)? Because in the past I was able to build Phoenicis with this package `openjdk-11-jdk-headless`

**Comment by qparis** [comment]
Do you want to create the package or do you just need to run it?

**Comment by t0msk** [comment]
I just want to run `phoenicis-create-package.sh`, in the past I just run:
```
git pull
mvn clean package
rm -rf ~/.Phoenicis/cache/
```
with `openjdk-11-jdk-headless` and it worked and I had no issues.

**Comment by qparis** [comment]
Yes, but it caused other issues so we changed the packaging system

**Comment by qparis** [comment]
You can easily grab a prebuilt binary of OpenJDK 11

**Comment by t0msk** [comment]
I really would like to install it from repo. I will try to find ppa for it.

**Comment by qparis** [comment]
Once it is built, you do no longer need it

**Comment by t0msk** [comment]
I will need it, because I build it after every change in master, I want bleeding edge, and I should have java 11 because:
```
root@tomsk-Ntb:/opt/Build/Phoenicis/phoenicis-dist/src/scripts# cd /usr/lib/jvm/
default-java/                     .java-1.11.0-openjdk-amd64.jinfo  
java-1.11.0-openjdk-amd64/        java-11-openjdk-amd64/ 
```

**Comment by t0msk** [comment]
@qparis Here is that problem https://askubuntu.com/questions/1037646/why-is-openjdk-10-packaged-as-openjdk-11 so it looks like that I have to wait till Java 11 will be released for Ubuntu 18.04 LTS.

**Comment by qparis** [comment]
Maybe we could set-up an script that builds phoenicis-master everyday on our side. 
Can you make a ticket for this?

**Comment by t0msk** [comment]
Done :)
