### ISSUE TITLE
Verb tab: Make the UI more user friendly

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1738]

**Comment by madoar** [comment]
What do you suggest?

**Comment by qparis** [comment]
Hum, maybe more a list view, some filtering and the possibility to install multiple verbs at once

**Comment by Kreyren** [comment]
+1 .. Something alike using QT/GTK (if not used already) with the ability to change GUI from user-side would be cool. Current seems horrible >.>

**Comment by qparis** [comment]
> +1 .. Something alike using QT/GTK (if not used already) with the ability to change GUI from user-side would be cool. Current seems horrible >.>

??

**Comment by Kreyren** [comment]
@qparis Suggesting improvement of GUI..

Was told that QT/GTK is not supported in phoenicis due usage of java, suggesting to include it some otherway to make the GUI fully user customizable.

**Comment by qparis** [comment]
Nothing to do with this ticket...

**Comment by Kreyren** [comment]
i though you ware discussing UI for verbs tab? or is it feature from POL 4 that i'm not aware of? o.o

**Comment by madoar** [comment]
@Kreyren what do you mean by `user customizable`?

We can't really switch out the GUI implementation (even if we wanted to).
It would basically mean, that we need to reimplement at least 50% of Phoenicis.

**Comment by Kreyren** [comment]
@madoar afaik it's frontend should it be effective to rework in comparison to backend? o.o (zero knowledge in java take with care)

**Comment by madoar** [comment]
@qparis how about we change the verb tab in the container details panel to contain a grid, where each row consists of a single verb. For every verb three things are shown in the row:
- a selection `CheckBox`, which can be used to mark the verb for installation
- the name of the verb
- an install button, which can be used to install the verb directly

Directly underneath the grid, we can then put an `Install all selected verbs` and a `Reset` button.
What do you think?

**Comment by qparis** [comment]
Sounds great ! I’d also like to reserve some space to describe what does the verb do

**Comment by plata** [comment]
Would be nice to show which Verbs are installed already but I don't think that's possible.

**Comment by qparis** [comment]
I think it is if we decide to write in the config file when a verb is installed

**Comment by plata** [comment]
Shall we? Could also be misinterpreted (e.g. if you install a verb from winetricks, it obviously will not be shown as installed).

**Comment by madoar** [comment]
I also think this is a feature Phoenicis should have.
It helps the users understand how their containers are configured.

**Comment by plata** [comment]
I don't think that's possible. How do you want to figure out if a verb is installed or not?

**Comment by t0msk** [comment]
@plata If Phoenicis will have full support of installing and uninstalling verbs, then there will be no need of using winetricks.

**Comment by madoar** [comment]
@plata via a lookup in the configuration file.
Either the verb is marked as installed or not.

@t0msk I don't think we'll support uninstalling verbs.
The reason is, that we can't ensure that during the uninstallation of a verb other installed verbs don't break. We discussed this in another issue (can't remember which one)

**Comment by plata** [comment]
That works but it is not "independent of the way it has been installed by" (will only work for Verbs installed by Phoenicis).

**Comment by plata** [comment]
Yes. What I mean is: if you install the verb e.g. via winetricks, we will not know it. That's all ;)

**Comment by madoar** [comment]
Is this really a problem?
It will always be possible to change a container from outside Phoenicis, without us knowing neither that the container has been modified nor what exactly has been modified.

**Comment by qparis** [comment]
Sure, it is also possible to remove files randomly from outside phoencis. 
I think we better assume that the user won't have strange behavior like this when we design phoenicis :)

**Comment by madoar** [comment]
This has been implemented in #1815.
