### ISSUE TITLE
Abstract: Interactive GUI/(TUI?)

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1741]
Based on https://github.com/PhoenicisOrg/phoenicis/issues/1738#issuecomment-451785281 i'm suggesting to make phoenicis's GUI fully customizable from the user side.

+For gentoo and ricers making TUI version would be probably great too :thinking:

**Comment by plata** [comment]
Basically you suggest to implement a new GUI. It is possible and who ever wants to do so, is free do do it.

However, in my opinion, this is "won't fix" for us. @qparis @madoar do you agree?

**Comment by qparis** [comment]
Yes. In addition, the GUI is already customizable thanks to the different skins
