### ISSUE TITLE
Missing windows frame

### ISSUE THREAD

**Issue by giovannicaligaris** [PhoenicisOrg/phoenicis#1745]
5.0 Alpha 2
Elementary OS Juno

Missing the windows frame, can't even click on anything.

![wine](https://user-images.githubusercontent.com/26255347/50831488-dee79900-1342-11e9-9b7d-f8bb105c3469.png)

**Comment by giovannicaligaris** [comment]
I haven't tried. Do you know any other apps that I can test?

**Comment by plata** [comment]
https://www.quora.com/What-are-some-popular-or-famous-desktop-applications-made-with-javafx

**Comment by giovannicaligaris** [comment]
I installed Skedpal and it ran fine. I have java 11 and maven installed.

**Comment by plata** [comment]
Can you try
```Java
primaryStage.initStyle(StageStyle.DECORATED);
```
in
https://github.com/PhoenicisOrg/phoenicis/blob/15ee51837d61805f30905b17dd5c888096b2aa75/phoenicis-javafx/src/main/java/org/phoenicis/javafx/JavaFXApplication.java#L42

**Comment by plata** [comment]
@giovannicaligaris please try if #2094 fixes the issue for you.

**Comment by Zemogiter** [comment]
@giovannicaligaris please retest with the latest commit

**Comment by plata** [comment]
According to @lehnertz85: 
> Replacing the `Exec=phoenicis %F` in `Phoenicis.desktop` with `Exec=env GTK_CSD=0 phoenicis %F` will allow the window to display correctly in Elementary OS 5.1

We should validate that this option does not have any negative effects on other OSs and then implement it.
