### ISSUE TITLE
Abstract: Github Wiki

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1746]
Suggesting to allow `wiki` on github for phoenicis that could be updated with relevant info, some people (me included) preferes it to external documentation. 

Willing to contribute.

**Comment by madoar** [comment]
What would you like to add to a Wiki, that doesn't need to be contained in the documentation?

**Comment by Kreyren** [comment]
@madoar Personally i'm rather for https://github.com/PhoenicisOrg/phoenicis/issues/1748#issuecomment-452701271 "Changing the approach to render the documentation".

Expected more effective way for contributors to maintain the documentation. 

Closing the issue as Obsolete/Duplicate. 

*Created this issue prior to #1748*
