### ISSUE TITLE
PR: Discord, Zulip, IRC, Slack

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1747]
Recommends creating Discord, Zulip, IRC and mirror them with a slack.

### Expected: 
If message on discord is sent in #support -> show on Zulip, IRC, Slack in support channel and vice-versa.

### Concept: 
Discord, Zulip and IRC supports external bots to include this feature. These bots usually have a working base that outputs ping in selected programming language to add functions.

### Suggestion: 
Recommends creating an ethical codex on those servers with expected, acceptable and unacceptable behavior of it's members without admins, based on my experience it's best approach for linux community that generally self-regulates itself.

### Reasoning: 
I believe that it would allow building a community in comparison to Slack which is not preffered in general (based on my experience) + it would allow more contribs in general to phoenicisorg.

**Comment by ImperatorS79** [comment]
I agree with you, but I must say something: in comparison of discord, nobody uses slack...

**Comment by madoar** [comment]
I'm fine with anything, but I agree with @plata that too many communication tools are a whole lot of work to moderate.

**Comment by Kreyren** [comment]
@plata The concept is that we don't need moderators there assuming using the ethical codex since linux community is used to self-regulate itself + Moderators can use the service of choice to see all message. 

Also we can recruit community moderators to enforce the ethical codex i would be willing to semi-moderate it myself.

**Comment by Kreyren** [comment]
@plata Simmilar approach could be used on the forum, but note communication software != forum the implementation is very different. Can file an issue on demand with suggestions.

**Comment by plata** [comment]
No matter what, we will need moderators in the different systems.

**Comment by Kreyren** [comment]
@plata There are approaches to avoid using moderators too, but having moderators is sanest. Note that the management of moderators doesn't have to be hard to maintain. Usually forums are self-regulating based on stated rules.

**Comment by plata** [comment]
Well, usually doesn't help. Look at the forum and you will see how reality is.

**Comment by plata** [comment]
Fine.

**Comment by plata** [comment]
@qparis what do you think about the arguments above to prefer Discord over Slack (actually nobody is active in our Slack either so we could really close that).

**Comment by Kreyren** [comment]
So what is the decision? The chat would help a lot now..

**Comment by Kreyren** [comment]
Refference: https://github.com/PhoenicisOrg/scripts/issues/829

**Comment by plata** [comment]
@qparis please decide what we want to do about this.

**Comment by Kreyren** [comment]
Any ETA?

**Comment by qparis** [comment]
We will decide about that once the website is ready to host phoenicis support. Having a working and secure forum is my priority

**Comment by Kreyren** [comment]
@qparis ETA for that? Recommend creating a discord now since it's creation is fast and we can organize work on phoenicis better.

**Comment by qparis** [comment]
I think that the work is pretty well organized isn’t it?

**Comment by Kreyren** [comment]
@qparis upstream maybe, but we lack contributors and community which is mandatory and takes long to build.

**Comment by madoar** [comment]
@Kreyren Phoenicis is still in alpha. I don't think that a large community would benefit us at the current time, contrary it is even possible that it would obstruct our current development. 

There are still large parts in Phoenicis which are either an interim solution, which we know we need to replace later on. Other parts need larger improvements before they should be used by a huge number of users, like the verb and application installer scripts. If we don't improve such parts now while we still have a small script developer and user base, we will have a much harder time later on. In addition Phoenicis is not stable enough at the moment, which could leave behind a bad impression of the software to users that expect it to be more stable/complete.

**Comment by Kreyren** [comment]
@madoar Community will grow based on software's stage we can build infrastructure and make sure that it's going to work as expected..

+ assuming productive environment it can generate contributors.. 

> In addition Phoenicis is not stable enough at the moment

sufficient for me.. Can expect more people with same opinion..

> which could leave behind a bad impression of the software to users that expect it to be more stable/complete

Write ALPHA VERSION in big font and red color everywhere then and don't push it in beta unless you have a working concept or don't do anything stupid like Schtefan from Argent Linux did and it's going to be fine..

**Comment by Kreyren** [comment]
Created unofficial discord server on https://discord.gg/WTbRQW based on anarchy concept.

**Comment by plata** [comment]
Maintaining anything additional to the forums and GitHub will add too much work for us. Moreover, it doesn't really make sense to split the community to multiple services.

**Comment by Kreyren** [comment]
> Moreover, it doesn't really make sense to split the community to multiple services.

Disagree
