### ISSUE TITLE
Abstract: GUI wizard installer

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1751]
Recommends making a GUI wizard that is able to create a new scripts alike setting engine from a dropdown menu, dependencies, etc..

I believe that it would make creating the installers more effective for contributors that doesn't know javascript and/or phoenicis's functions.

**Comment by madoar** [comment]
We already have the `Local Installer` for this purpose.
It is not perfect yet, for example it doesn't contain a step to select some verbs during the installation phase yet. So if you have some improvement ideas feel free to recommend them :)

**Comment by Kreyren** [comment]
@madoar more info on local installer?

**Comment by Kreyren** [comment]
@madoar Found it, thanks

should be probably more visible :thinking:

**Comment by plata** [comment]
We cannot make a dedicated button because the script comes from the repository. So if you use a different repository, you might not have it.

**Comment by madoar** [comment]
@plata can we maybe add something like `Favorites` or `Suggestions by Phoenicis`?

**Comment by plata** [comment]
I see two options:
1. Show a button if the script is found.
2. Add "showInFavorites" to script.json.

**Comment by madoar** [comment]
> Show a button if the script is found.

This looks like a hardcoded solution right?

**Comment by plata** [comment]
Yes.

**Comment by qparis** [comment]
I'd like also to see if we could create a new container from the container tab

**Comment by madoar** [comment]
@plata I would then suggest to solve this via option 2. I think we should split this in two parts:
1. Add a field/option to the applications through which you can specify that an application is a `favorite`
2. Mark all `favorite` applications somehow (maybe with a small star on the right bottom of the application miniature?) and display them in front of all non-favorite applications (it should be possible to disable this behavior through a filter checkbox in the sidebar)

@qparis didn't we have a separate issue for this (I can't find it...)

**Comment by Kreyren** [comment]
I'm for show the button if script is found too. Seems sane and effective

**Comment by madoar** [comment]
@Kreyren like I mentioned above the solution, to show the `Local Installer` button in front when it's found, has the problem that it needs to be hardcoded in Phoenicis.
This in turn can lead to strange behavior if a user doesn't require/use the official script repository but still adds a script called `Local Installer`. In this case he/she will ask himself/herself why the `Local Installer` in shown in the front.

This is the reason why I would prefer option two, where the script itself can specify, whether it should be added to the favorites or not.

**Comment by plata** [comment]
New field in the json or shall we make the category an array so that you can select multiple categories for an app (might have some severe consequences for the repository DTO)?

**Comment by madoar** [comment]
How does allowing an application to be contained in multiple categories solve the problem?
I think we should do both, i.e. add a new `isFavorite` field to the json and allow for applications to be part of multiple categories.

**Comment by Kreyren** [comment]
I'm leaving the conversation since i don't think that i'm clarified to resolve the technical implementation.

**Comment by plata** [comment]
@madoar it could be a category "Favorites" instead of a json filed `isFavorite`. Depends a bit on how we would like to present this to the users in the GUI. If we want a dedicated button (which probably makes sense), we should go for the json field.

**Comment by madoar** [comment]
Ah, I think we spoke about different things.
My `isFavorite` field suggestion only changes the order of the applications in a single category.
It wouldn't be responsible for showing an application in other categories.

**Comment by plata** [comment]
I don't think that makes too much sense to be honest. Also, it doesn't solve the problem. What we need is some kind of dedicated menu/button like in PoLv4.

**Comment by Kreyren** [comment]
Obsolete by https://github.com/PhoenicisOrg/phoenicis/issues/1788 probably?

**Comment by plata** [comment]
Yes and know. @madoar what do you think, shall we open a new issue for the favorites and close this one?

**Comment by madoar** [comment]
@plata yes a new issue would be good I think
