### ISSUE TITLE
Alternative build instructions (Gentoo compatibility)

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1757]
so far i'm unable to make ebuild for gentoo working using maven (requires making new eclass -> +- few hours of work for someone who is not familiar with java).

Reference + reasons to maven:
https://wiki.gentoo.org/wiki/Gentoo_Java_Packing_Policy#Java_Build_Systems

Example of java ebuild:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-java/icedtea/icedtea-3.9.0.ebuild

Can you provide alternative instructions for compilation phoenicis?

**Comment by madoar** [comment]
What do you mean with `alternative instructions`?
We use `maven` to build our applications, because it makes the task easy for us.
`maven` does among others the following tasks for us:
- run our unit tests
- manage our dependencies
- build the application into an "executable" `jar` file

There are a lot of different ways to possibly build/create an executable `jar` file, the issue is, that they are often more complex and harder to maintain. If we choose to switch to such a solution it would also mean that we have less time to concentrate on developing Phoenicis, because we need to maintain the build-system, which is not something we want to do in my opinion.

**Comment by Kreyren** [comment]
@madoar I'm rather asking for recommendation to compile phoenicis excluding using maven.

**Comment by plata** [comment]
We will not support this. You are free to do so of course but the officially supported way is maven.

**Comment by Kreyren** [comment]
@plata noted and understood, thanks for info.

If i can ask can you recommend me a way for alternative compilation to make my work easier?

**Comment by plata** [comment]
I have no clue about gentoo. I think you're better of asking in their forums directly.

**Comment by plata** [comment]
I don't think it will be possible easily. E.g. you need all the dependencies.

**Comment by Kreyren** [comment]
@plata Assuming that all the dependencies are met?

**Comment by plata** [comment]
I don't know. Maybe you can make it work with another build system. However, it will be a pain because you would need to constantly maintain it. I'm pretty sure it's not worth the effort.

**Comment by Kreyren** [comment]
@plata maintainance is not a problem it self-maintains practically..

The compilation method is the issue :/

**Comment by plata** [comment]
I don't know how you can compile for Gentoo. Apparently neither Gradle nor Maven is supported, so you should ask them how they want to do it.

**Comment by Kreyren** [comment]
@madoar Helpful, will try, thanks!

**Comment by Kreyren** [comment]
@madoar / @plata Do i need to compile release?

**Comment by Kreyren** [comment]
UPDATE: Maven is not supported by gentoo since it is not respecting sandbox -> is security risk.

> maven has a buildsystem that touches your filesystem directly. maven building will always need the system itself

ant is integrated -> To compile phoenicis on gentoo ant has to be integrated.

**Comment by qparis** [comment]
Ant is really out of date. It is lacking essential feature like download of dependencies.
It is very unlikely that we switch from maven to ant.

**Comment by Kreyren** [comment]
@qparis i'm not asking you to switch from maven, but to help me to make an ebuild for phoenicis since i lack the required info.

**Comment by qparis** [comment]
Every info you need to have is basically described in the Maven pom.xml file. There are some feature that are not supported by ant (the most impacting one is probably the download of dependencies...). So you'll quickly see that if you want to sort that out, you'll need to rewrite Maven features at some point
