### ISSUE TITLE
Shall we use FXML?

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1763]
Concerning @madoar's quest to improve the MVC, would it make sense to define the GUI in FXML?

**Comment by Kreyren** [comment]
Shall we use <any new format for scripts> ?

My answer is always yes.

**Comment by Kreyren** [comment]
@madoar Sorry i though that it's relevant from the context >.>  Noted explanation

**Comment by plata** [comment]
Ok then. I will trust you with this. Was just a question.
