### ISSUE TITLE
Crowdin commits, include credits

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1770]
### Expected behavior
Include credits on translators in commits alike https://github.com/PhoenicisOrg/phoenicis/pull/1552/files/1a9948139eab36b20bc732abb4ae4b29a84e633d..bb7f20313ac0dccc390892aeddd7bf4ba71475c4

### Actual behavior
Only approver is mensioned

### Reasoning
Practically the only reasons for free translators is to be mensioned on the project or to have translate to a thing that they are using -> This would encourage more people ~~and satisfy my narcissism :D~~

**Comment by plata** [comment]
Do you know how to do it? Is it even possible in Crowdin?

**Comment by Kreyren** [comment]
@plata i was cooperation on some project that did it, but i think they did it manually? I was told that there is a such a feature tho..

**Comment by plata** [comment]
Doing it manually is not an option. I can ask Crowdin support if it is possible if you want.

**Comment by Kreyren** [comment]
@plata Asking on support is sane 

Doing it manually for the most active contributors maybe? (i don't care about my mensioning thinking about PR implementation)

**Comment by plata** [comment]
Actually I don't think adding anyone to the translation files makes a lot of sense because none of the users will ever read them.

**Comment by Kreyren** [comment]
@plata Well something alike is efficient enough any credit on translators is a good motivation to contribute.

**Comment by madoar** [comment]
@Kreyren isn't it enough to see the translator of a string on Crowdin?
I think the code repository is the wrong place to save this information

**Comment by Kreyren** [comment]
@madoar Like ideally translators would have it's names mensioned in the software itself.. alike in about section. 

Crowdin is not enough for expected usecase assuming that translators are hidden in each string and not visible to the end-user.

**Comment by plata** [comment]
I've talked to the Crowdin support: Adding names to the .po doesn't make much sense. Crowdin offers a list of [top members](https://support.crowdin.com/project-reports/#top-members) inside Crowdin. That's probably the best you will get (I'm not going to extract this and add it to the software manually).

**Comment by plata** [comment]
Just got an update from Crowdin:

> As possible alternative you may use Top Members API to parse the response and represent a leaderboard on your website.

If we want to do so, we should open a new issue for phoenicis-backend.

They also told:

> In general our team has some plans to improve management of open projects in order to encourage translators to contribute, so stay tuned :)

**Comment by plata** [comment]
@Kreyren I suggest to close this for now and wait for the official Crowdin improvements. After all, anything we could do can never be as integrated as their official solutions.
Would that be ok for you?

**Comment by plata** [comment]
No response, assuming yes.
