### ISSUE TITLE
Question: Why is Phoenicis/Script in separate repository?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1784]
Why is Phoenicis/Script in separate repository?

**Comment by plata** [comment]
It is simply the default scripts repository for Phoenicis. It's perfectly possible to use a different scripts repository. Also, it doesn't make sense to mix the Javascript scripts and the Java application in one huge repository. Additionally, it allows us to have script maintainers which can review and merge scripts PRs.

**Comment by qparis** [comment]
And in addition, scripts can be updated without updating phoenicis

**Comment by Kreyren** [comment]
What about implementing something like `git clone --filter` (https://askubuntu.com/a/1074185)?

In theory we could merge scripts into a phoenicis repository and then phoenicis would clone just a directory from a master branch? (not tested, needs research)

Assuming that git specified directory from repository is possible: i believe that merging PhoenicisOrg/scripts into PhoenicisOrg/phoenicis since it would make the work on phoenicis more encouraging to contributors and more effective to review all changes intead of checking multiple repositories.

**Comment by Kreyren** [comment]
in theory for making a versioned release we need to provide phoenicis-javafx, phoenicis-scrips does not need to be merged in release? Master can have both since if `git clone --filter` is sufficient the contributor would only downloaded that for it's local repository?

Assuming that phoenicis would have community of script maintainers and contributors the implementation of updating multiple things would be beneficial this way i believe.

**Comment by qparis** [comment]
As I said, it creates more problem that it solves

**Comment by Kreyren** [comment]
@qparis elaborate?

**Comment by qparis** [comment]
I don't know how elaborate more, I think my statements are pretty clear. You are suggesting to change a (deep) aspect of the architecture of phoenicis to solve a problem that does not exist

**Comment by Kreyren** [comment]
understood, probably not relevant at this moment.

My expected outcome was to make one CONTRIBUTING.md file that woudn't change for both repositories making it easier to understand for new contributors.
