### ISSUE TITLE
Implement notification system

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1786]
Trigger notification on:
- installation started
- app install finished
- container created

The notification could be shown like:
![notification](https://user-images.githubusercontent.com/3973260/51433022-00e5f300-1c42-11e9-9a9f-c765142d99d5.png)

Is this something for JavaFX only or can we implement it in the respective modules directly?

see also #1781

**Comment by madoar** [comment]
What do you mean by `implement it in the respective modules directly`?
I think this issues can be split into two parts:
- the implementation of a JavaFX component to visualize the `1`
- the implementation of logic supplying the `1` to the UI

About the JavaFX component:
What information do we want to show in the circle? Only a single digit number? Or any kind of `String` with a maximum length?

**Comment by plata** [comment]
I mean the logic, e.g. does it make sense to implement notifications in the containers module or is it something which is a GUI thing only.

We can show either the number of notifications or just a notification (could be a "!"). I think the second would be sufficient and easier to implement.
