### ISSUE TITLE
Abstract: Bash/Shell scripts?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1787]
Using Shell/Bash for making configuration for compatibility layer managers is my preffered way could this be implemented from POL 4 or have some kind of frontend?

### Expected behavior
If user is using OS A -> Check for compatibility reported for OS A and warn the user if there is a missmatch e.i: LLVM-7.0.1 on OS A causes issued because of provided dependencies -> OS A has to use LLVM-7.0.0 OR recommends temporary symlinking problematic dependencies downloaded from source. (abstract situation)

if user is using GPU Driver A -> perform compatibility checks for version, vulkan and it's implementation, etc.. if missmatch warn the user.

### Actual behavior
Specify installation method, engine, dependencies

### Reasoning
More methods to make a scripts -> more methods of contribution and compatibility.

**Comment by Kreyren** [comment]
@plata Well i believe that in linux there are way more people knowing shell/bash then those who know how to use javascript.. 

Shell/bash is practically the first thing that power user on linux learns

**Comment by plata** [comment]
So what? We're not Linux.

**Comment by Kreyren** [comment]
@plata Well we can expect that there would be lots of linux users using phoenicis assuming that it's supperior to alternatives which it has potential to + more people contributing to scripts to add compatibility the better..

**Comment by plata** [comment]
That's simply not true. We had bash scripts for PoL4 and if you compare them to our scripts now, they are *way* more complicated.

**Comment by Kreyren** [comment]
@plata the complexity is expected..

**Comment by plata** [comment]
So what's the advantage then?

**Comment by Kreyren** [comment]
@plata The ability to ask for user input and using if statements and other shell/bash elements to allow better optimization for used system on cases where system components are causing instability. 

e.i: for cases where wine, dependencies and installation method is not enough alike different configuration for two different graphics cards.

**Comment by plata** [comment]
Everything you mentioned can be done in our scripts as well.

**Comment by Kreyren** [comment]
@plata How? For example if Dishonored 2 needs different version of LLVM on AMDGPU?

**Comment by ImperatorS79** [comment]
You can use vulkaninfo and glxinfo (eglinfo also, but less intersting) to guess what drivers and OpenGL/Vulkan version are installed, then simply warn the user if something is not efficient in his config. See #836 .

**Comment by Kreyren** [comment]
Well everything is possible in theory, but that doesn't mean that it's sufficient for the usecase and more options to make a script the better for contributors who doesn't know anything about java (me included) Bash/shell is widely used and most of the linux users know how to use it. 

Practically we could greb the configuration that javascript makes and define it in universal definition for phoenicis then adding more script same way would result in same instructions for the phoenicis to make a engine configuration.

For exampel:

 in javascript
```
.wineVersion("3.16")
.wineDistribution("upstream")
```

in bash/shell
```
WINE_VERSION="3.16"
WINE_DISTRIBUTION="upstream"
```

Those can be used to define same variable for phoenicis to use assuming that phoenicis expects `.wineVersion` and `.wineDistribution` we can say that

 `if script is a bash and use `WINE_VERSION` greb it's variable and use it for .wineVersion'

**Comment by Kreyren** [comment]
Practically we can introduce support for more programming languages the same way -> more contributors updating script in their preffered language.

**Comment by plata** [comment]
You're free to add support for whatever language you like. After all it's open source. I'm just saying that we will not support this officially because it's only additional work with no added value.

So this is "won't fix".

**Comment by ImperatorS79** [comment]
And more work to be done to support those languages, and their respective bugs. 

As I began to contribute to some scripts, I simply copied the script from the repo and modified the needed values, then from the doc. From my experience POL5 scripts in JS are really easier to use than POL4 ones in bash.  Most people do not have any knowledge in programming, and .js scripts are really good for that in phoenicis.

Users will not stop to contribute because "Hey, you do not support my favourite language xhelejhd, sorry".

**Comment by Kreyren** [comment]
> Users will not stop to contribute because "Hey, you do not support my favourite language xhelejhd, sorry".

But i believe that it would encourage more people if we supported bash/shell.

> You're free to add support for whatever language you like. After all it's open source. I'm just saying that we will not support this officially because it's only additional work with no added value.

Well in theory making the source for the bash/shell to be used is not a problem assuming you can make a support to invoke that script in phoenicis/POL console from repository?

**Comment by qparis** [comment]
> Well in theory making the source for the bash/shell to be used is not a problem assuming you can make a support to invoke that script in phoenicis/POL console from repository?

Try to do it, and observe by yourself what is the problem with maintening several script language at the same time.

Also, bash does not support object oriented programing and does not have code abstraction features. For this reason, it is responsible for the problem we have with POLv4, ie. broken scripts that are not up to date. It we had chosen any other language from the begining, we would not have tons of out to date scripts today

**Comment by Kreyren** [comment]
I see :thinking:
