### ISSUE TITLE
SUGGESTION: Emerging steam into phoenicis?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1794]
### Expected behavior
Avoid using closed-source steam which is causing issues that i can't fix + lacks customization and use phoenicis instead.

### Actual behavior
Phoenicis supports only engines like WINE and lacks steam functions. 

### Theory
Practically steam is web-browser with wine, chat and file manager with downloader (and chat). 

* For web-browser we can adapt browser in phoenicis.
* Wine we already have + we can add more engines
* Chat well in theory? Seems like good idea
* File manager and downloaded.. probably the hardest to implement afaik steam client generates hash string that is used for downloading from a remote server if hash matches. In theory steamdb can help with it.

* There are also achivements that can be grabbed from steamAPI based on how uplay works.

**Comment by plata** [comment]
What you suggest here is a completely different application (in fact Lutris is a bit in this direction). It is possible to implement this based on Phoenicis but it's not the direction we want to go.

Therefore it's a "wont fix" for us.

**Comment by Kreyren** [comment]
> It is possible to implement this based on Phoenicis but it's not the direction we want to go.

Why not? It would be cool and lutris is useless to be used alike

**Comment by plata** [comment]
Let's take chat: There are a whole bunch of chats available already (e.g. discord). What's the point to implement it in Phoenicis again?

In general: How should we implement stuff like cloud sync or even game downloads without the Steam client?

**Comment by Kreyren** [comment]
> Let's take chat: There are a whole bunch of chats available already (e.g. discord). What's the point to implement it in Phoenicis again?

I'm not sure about implementing chat i realized it once i write the issue and it seemed like good idea, but i would implement something alike once phoenicis has a community. 

Something like minds using encrypted chat would be amazing come to think of it..

> In general: How should we implement stuff like cloud sync or even game downloads without the Steam client?

There are methods to make it work steamless it would require research and reverse-engineering of steam to implement but in theory steam is a web-browser that uses it's own UI to download games and listen from SteamAPI which is available to public. 

Shoudn't be impossible nor hard to implement once we understand the concept. Based on available informations it's equvivalent of password protected download, but steam is using hash since games can't be downloaded without steam client (tried that +-2 years ago).

**Comment by Kreyren** [comment]
@plata Assuming that we could run Steam Games steamless on phoenicis i would also implement other features and introduce them once phoenicis is in gold. Seems sane assuming that people would use it instead of steam-for-linux.

**Comment by qparis** [comment]
> @plata Assuming that we could run Steam Games steamless on phoenicis

Very unlikely that we are able to do this

**Comment by Kreyren** [comment]
@qparis I think it's possible, will investigate and report back once i have the time.
