### ISSUE TITLE
Restructure `DetailsPanel` implementations similar to `Tab` 

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1804]
When thinking about our usage of the `DetailsPanel` implementations I see similarities to the usage of the `Tab` class from JavaFX. The `Tab` class is used as a container for other components. In addition the `Tab` class provides a set of utility fields/functions (e.g. a title and a close button/listener). This functionality is very similar to our `DetailsPanel`.

For that reason I suggest we restructure our `DetailsPanel` implementations similar to the `Tab` class.
In detail I suggest we provide a single non extendable `DetailsPanel` class, which takes a second component as its content. All our current `DetailsPanel` implementations would then be changed to normal JavaFX components and be added to a `DetailsPanel` component as its content.

**Comment by plata** [comment]
We need a prototype to this how this works out (or not).
