### ISSUE TITLE
Delete GitHub project

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1812]
see https://github.com/PhoenicisOrg/phoenicis/projects/1

We do not maintain it. The only think it might do is confuse people. Therefore I suggest to delete it.

**Comment by madoar** [comment]
I agree with deleting our currently existing GitHub project.

Instead we require a tool to track our currently most important open tasks. With currently ~120 open issues it is quite hard to track for which problems/suggestions we have an issue and what issue should be fixed when (both in which order and for which release version).

**Comment by plata** [comment]
You can filter the milestone.

**Comment by plata** [comment]
Done.

**Comment by madoar** [comment]
But what does the milestone tell us? Only the release in which the Issue/PR should be fixed/included. It doesn't provide any for context information about possible relations to other Issues/PRs.

For example it makes sense to provide every issue targeting the GUI with a dedicated tag.
The same applies to issues targeting the repository structure and management.

**Comment by plata** [comment]
We can add additional labels for this, so we would get "bug, repository" or "new feature, gui".

**Comment by Kreyren** [comment]
>  what does the milestone tell us?

What needs to be done untill software can be pushed in beta, gold? from my experience project-like GUI always slow things done in coding.

Assuming that my feedback is welcomed

**Comment by plata** [comment]
What do you mean by

> assuming that more 'dynamic workflow' is beneficial

?

**Comment by Kreyren** [comment]
@plata Dynamic workflow = none has to maintain todos since they are made in github issues by contributors/testers and there is no fixed solution which usually results in more issues since there is no quality controll for chosed solutions + you have the ability to approach the issue from more points of views.

**Comment by plata** [comment]
In the end, this is exactly what we do.
