### ISSUE TITLE
Suggestion: edit button for shortcuts near to run, etc.

### ISSUE THREAD

**Issue by SanZamoyski** [PhoenicisOrg/phoenicis#1814]
It is just sugestion to remove right-click menu in shortcuts list and move it to right column.

> edit button in "right column" as Run, Close, Uninstall.

**Comment by Kreyren** [comment]
I don't understand the suggestion can you visualize it?

**Comment by SanZamoyski** [comment]
Move this menu:

![image](https://user-images.githubusercontent.com/17430346/52051518-1c130580-2554-11e9-9069-1cfa93f1fead.png)

Somewhere here:

![image](https://user-images.githubusercontent.com/17430346/52051564-3baa2e00-2554-11e9-91d7-f4d7e9beacd3.png)

Something like this:

![image](https://user-images.githubusercontent.com/17430346/52051756-be32ed80-2554-11e9-95fe-c3d39f75c176.png)

**Comment by madoar** [comment]
I think showing an `Edit shortcut` button inside the shortcut details panel may be a good idea.
@plata what do you think?

**Comment by plata** [comment]
Yes, we should do this.

**Comment by Kreyren** [comment]
Agreed, edit in dropdown is terrible..

**Comment by madoar** [comment]
Has someone an image for an `Edit` button, we can use?

**Comment by plata** [comment]
The icon should be actions/document-edit.

**Comment by madoar** [comment]
Which icon set do we use again?

**Comment by plata** [comment]
Faenza. I also had to search to figure this out again. We should write it down somewhere.

**Comment by madoar** [comment]
`actions/document-edit` doesn't seem to exist. At least I can't find it on https://github.com/shlinux/faenza-icon-theme

**Comment by plata** [comment]
You're right. I searched in Breeze.

**Comment by plata** [comment]
Maybe gtk-edit?
