### ISSUE TITLE
Show confirm dialog when installing verbs via the container details panel

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1822]
It would be useful to show a confirmation dialog when the user wants to install one or multiple verbs in the container tab. This dialog should contain the following information/components:
- a textual list containing the names of all verbs the user has selected
- a confirm button
- a cancel button

For more details see https://github.com/PhoenicisOrg/phoenicis/pull/1815#issuecomment-460035106

**Comment by plata** [comment]
Do we already have a dialog which would be capable to do so or do we need a new one? It should have a scroll pane to show the list.

**Comment by madoar** [comment]
No we do not currently. I think we can copy most of the code from the `ConfirmDialog` class.
