### ISSUE TITLE
Audio not working in flatpak installation

### ISSUE THREAD

**Issue by seijikun** [PhoenicisOrg/phoenicis#1840]
### Expected behavior
Audio should work.

### Actual behavior
Audio of any kind does not work.

### Steps to reproduce
1. Install Phoenicis using flatpak
2. Install a new application / create a new container
3. Engine Tools / Configure Wine
4. Go to Audio-Tab

Wine shows:
```
Selected driver: winealsa.drv
```
but sound (Test Sound) isn't working.
I tried changing the backend by setting the corresponding registry-key to pulse, but now wine shows:
```
Selected driver: (None)
```
Do you maybe need to include libpulse in flatpak somehow?

### Comments
When running Phoenicis 5.0-alpha.2 directly, outside of flatpak, audio works just fine (It is automatically choosing the pulse backend).

### System information
* software version (git revision) of phoenicis and scripts repositories
> Newest from flathub
* used operating system
> openSUSE Tumbleweed
* Engine version
> Wine Staging 64bit 4.0-rc4 & 4.1

**Comment by plata** [comment]
Thanks for the report. I've actually never tried to use audio in the flatpak. Based on your description I would also assume that we're missing some permission. Maybe we can compare to the Steam flatpak to figure this out.

**Comment by seijikun** [comment]
I've got absolutely no idea of flatpak, but a short comparision of permissions shows:

```
com.valvesoftware.Steam/x86_64/stable flathub 3b8b2cdc2eb9
  permissions: ipc, network, pulseaudio, wayland, x11, devices, devel, multiarch
  file access: xdg-music:ro, xdg-pictures:ro
  dbus access: org.freedesktop.PowerManagement, org.freedesktop.ScreenSaver, org.gnome.SettingsDaemon, org.gnome.SettingsDaemon.MediaKeys, org.kde.StatusNotifierWatcher
  system dbus access: org.freedesktop.NetworkManager, org.freedesktop.UPower
  tags: proprietary

========================================================================

org.phoenicis.playonlinux/x86_64/stable flathub 95e86572d1f4
  permissions: ipc, network, x11, dri, multiarch
  file access: xdg-documents, xdg-download
```

So I would guess the permission pulseaudio (for pulse) and devices (for alsa) is missing?

**Comment by plata** [comment]
Can you try?

Relevant:
- https://github.com/PhoenicisOrg/phoenicis/blob/master/phoenicis-dist/src/flatpak/org.phoenicis.playonlinux.yml
- https://phoenicisorg.github.io/phoenicis/Developers/packages/

**Comment by seijikun** [comment]
I am already at it, but it's extremely annoying because openSUSE does have neither maven nor a jdk that supports JavaFX.

**Comment by seijikun** [comment]
Got it working! Will create a PR.
