### ISSUE TITLE
Abstract: ETA for gold?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1848]
Can we get some milestone of things that needs to be done for phoenicis to be pushed in gold state?

**Reasoning:** Based on my experience software development should be done as follows:
- Alpha = Working on general concept, abstract and base for functions.
- Beta = Interpreting those functions into a working software
- Gold = Once all milestones in beta are done we can push in gold

From my point of view Phoenicis is still in alpha even it's listed as beta. Maybe we should push this into a alpha again?

Reasoning:
- website which i believe is mandatory is not released nor working as expected
- there are no communities for contributors and users
- documentation needs still some work + is not user-friendly to be updated (expected wiki-like documentation to which anyone can contribute without making PR on github.)
- current script maintainance is unable to update all scripts and keep them updated (working on solution in https://github.com/PhoenicisOrg/phoenicis/issues/1846)

Based on my experience i would rather switch software back to alpha if there are things that can be reworked and done better instead of trying to finish beta stage.

I believe that milestones are mandatory to improve productivity.

**Comment by plata** [comment]
We have a milestone already. It's called "release".

**Comment by Kreyren** [comment]
@plata Noted, but It does not seems to have all required MRs from my POV..

**Comment by plata** [comment]
That's possible. I just said that we have the milestone. Doesn't mean that it is complete. In any case, it doesn't make too much sense to think about this before even having released beta.

**Comment by Kreyren** [comment]
@plata 
> too much sense to think about this before even having released beta.

Disagree alpha should state those thing since they are based on my experience critical..
