### ISSUE TITLE
Abstract: MR description

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1850]
Recommends standartizing merge request description for PhoenicisOrg/scripts as follow:

```markdown
<CATEGORY>/<GAME> : <SUMMARY>

### STATUS: <TESTING/HELP_WANTED/LVIE>

Description if needed.
- Info what was changed in commit.

---

## <WHAT NEEDS TO BE DONE/TODO>

TODO: Lorem ipsum..
- Info
- Info

TODO: Lorem impus..
- Info
- Info

---

## <RESEARCH/IMPROVEMENTS>

#### Game X needs Y
- Game X needs Y because it doesn't work with Z based on ABC.

---

Some info about maintained beeing responsible for updating initial commit message on github and stuff + Signed-off-by.
```

I believe that this improves productivity of Merge Requests to scripts so that contributors and members of phoenicis woudn't have to read all comments in commits.

**Comment by Kreyren** [comment]
Requesting moving in PhoenicisOrg/scripts.. though i'm filing that in there.. :man_facepalming:

**Comment by plata** [comment]
We should not use these status tags. GitHub introduced draft pull requests recently. So if the PR is not ready, you should use that.
The other stuff you suggest is very dependent on every single case in my opinion.

**Comment by Kreyren** [comment]
@plata Assuming that since case use scenario is for MR to PhoenicisOrg/Scripts that require changes i would say that it's beneficial?

**Comment by plata** [comment]
I don't see how adding "lorem ipsum" in a template helps anybody to be honest. What you've listed below "research" is "TODO" as well in the end if you think about it.

**Comment by Kreyren** [comment]
> I don't see how adding "lorem ipsum"

Is present for a sake of an example..

Is made to be changes trying to provide concept.

**Comment by plata** [comment]
I know but what remains in the template if you remove this? Not so much in my opinion. In the end, the template pretty much boils down to "add description here".

**Comment by Kreyren** [comment]
@plata Expected to be explained in contributing.md + inform contributor to update based on instruction to start working on it not sufficient?

**Comment by plata** [comment]
Sorry, I don't get that sentence. What I'm saying basically is: If we make a pull request template, it should be a helpful guideline for people wanting to commit something. With the current proposal, I don't see that this is the case because:
- status: like I said, use PR draft option if it's not finished
- description: it's obvious that there should be a description if you want to describe something
- research/improvements: this is a part of TODO and very dependent on the special case

**Comment by Kreyren** [comment]
@plata > Sorry, I don't get that sentence.

I meant that template should be explained in `contributing.md` since pull request is going to be overwritten by a commit message if one commit is used unless we can overwrite this. 

If we can overwrite this behavior we can make the important bits present and comment out the rest that can be uncommented if not needed or leave it with default message.

example
```md
### STATUS: <TESTING/HELP_WANTED/LVIE>

<!-- Description if needed. -->

---

## WHAT NEEDS TO BE DONE

<!-- TODO: Lorem ipsum..
- Info -->

---

Some info about maintained beeing responsible for updating initial commit message on github and stuff + Signed-off-by.
````

**Comment by Kreyren** [comment]
### STATUS: <TESTING/HELP_WANTED/LVIE>



---

## WHAT NEEDS TO BE DONE



---

Some info about maintained beeing responsible for updating initial commit message on github and stuff + Signed-off-by.

**Comment by Kreyren** [comment]
### STATUS: <TESTING/HELP_WANTED/LVIE>


- Changed A
- Changed B
- Changec C because of B

---

## WHAT NEEDS TO BE DONE


Nothing

---

Some info about maintained beeing responsible for updating initial commit message on github and stuff + Signed-off-by.

**Comment by plata** [comment]
Like I said before: the status should be covered by the PR type already in my opinion (so if it's not finished, use draft PR).

We could use:
```
- change a
- change b

# TODO (if applicable)
- open topic
```

**Comment by Kreyren** [comment]
Let's close this for now then we can re-open if the issue appears.
