### ISSUE TITLE
Abstract: Allow 3rd party wine

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1856]
### Expected behavior
Have working WINE engine in phoenicis + provide franken-wine for scripts. 

### Actual behavior
League Of Legends is not working and i have to help ppl from EndlessOS install lutris -- OR -- make custom wineprefix using portage on slaveOS.

I have to use custom wineprefix to play league of legends or use lutris.

### Why?
I can compile and provide wine with esync, pba, tkg and other patches in like 15 mins with multiple versions faster and more effective then phoenicis or lutris..

**Comment by plata** [comment]
It is possible already. All you have to do is to provide a json file. See e.g. https://github.com/PhoenicisOrg/wine-sources.

**Comment by Kreyren** [comment]
Perfect, checking..

**Comment by Kreyren** [comment]
@plata it seems to be able to use lutris's wine, how do i use it in a script?

**Comment by plata** [comment]
Like every other Wine. You might have to set `wineDistribution` according your json. If you replace the default json by a different one and call the distribution "upstream", you can use all existing scripts as they are.

**Comment by qparis** [comment]
We won’t merge any script that contains third party wine sources

**Comment by plata** [comment]
Sure but that's a different point. If @Kreyren wants to use different Wine sources, he can do so.

**Comment by Kreyren** [comment]
@qparis Noted, will be hotfix untill phoenicis wine is usable.. 

For franken-wine.. depends assuming that wine can't be provided in phoenicis alike there are wines that are fork of proton and wine combined with black magic codeblocks to make something working etc.. but these are usually staged..

**Comment by qparis** [comment]
Phoenicis wine are usable...

**Comment by Kreyren** [comment]
@qparis disagree assuming that issue https://github.com/PhoenicisOrg/scripts/issues/841 is roadblock to https://github.com/PhoenicisOrg/scripts/pull/797..

**Comment by Kreyren** [comment]
@plata any way to use lutris's wine without changing .json for Engine?

**Comment by qparis** [comment]
This is not a valid point. Not being able to install easily (because it is still possible) ONE dependency required for ONE game on ONE particular distribution does not mean that is is totally unusable. You are exaggerating. 

Does not mean that we should not address the issue.

**Comment by qparis** [comment]
By the way, using an alternative wine source is not easier that fixing this dependency issue

**Comment by Kreyren** [comment]
@plata Can i fix this problem using script that can be merged into phoenicis script repository? If not phoenicis wine is unusable for league of legends.. 

if you provide info i will update the MR.

**Comment by qparis** [comment]
As said before:

> We won’t merge any script that contains third party wine sources

**Comment by plata** [comment]
@Kreyren I'm don't fully understand what you need to get LoL running currently.

**Comment by Kreyren** [comment]
@qparis provide me a way to use phoenicis wine to resolve https://github.com/PhoenicisOrg/scripts/issues/841 and i can update MR.. otherwise phoenicis wine is unusable for league of legends -> need to use different wine.

@plata LoL fails with DirectX 9 error as explained on https://github.com/PhoenicisOrg/scripts/issues/841 i need a way to fix it so that install would pass.

**Comment by qparis** [comment]
> @qparis provide me a way to use phoenicis wine to resolve [PhoenicisOrg/scripts#841](https://github.com/PhoenicisOrg/scripts/issues/841) and i can update MR.. otherwise phoenicis wine is unusable for league of legends -> need to use different wine.

Keep in mind that Phoenicis is still alpha. We are not going to implement bad pattern to make things work on a short term

**Comment by qparis** [comment]
And also, keep in my that it is unusable on your particular configuration

**Comment by plata** [comment]
Ok, in this case, like @qparis said, you will have to wait until the linked winebuild issue is resolved if you want an official solution. Btw: @qparis any progress with that regard? Will we provide the required dependencies as part of the Wine package or do you see a better solution?

**Comment by Kreyren** [comment]
@qparis > Keep in mind that Phoenicis is still alpha. We are not going to implement bad pattern to make things work on a short term

Noted that's why am i looking for hotfix.. 

> And also, keep in my that it is unusable on your particular configuration

Afaik this can be reproduced for all scripts that are using same configuration? (wasn't told what is this caused by)

@plata Noted, is there any way to provide lutris wine without changing Engines? ideally something like `.wineDistribution("lutris")`

**Comment by Kreyren** [comment]
Based on https://github.com/PhoenicisOrg/wine-sources#how-to-use-it

Created `config.properties` with `webservice.wine.url = https://raw.githubusercontent.com/PhoenicisOrg/wine-sources/master/lutris-linux.json` in `~/.Phoenicsi`.

Found error in Engines 
![image](https://user-images.githubusercontent.com/11302521/53286982-35cff300-3776-11e9-988d-cffdbd4dd262.png)
- Removed changes in `config.properties` -> issue still present
- Nuked .Phoenicis -> issue still present

Maybe different issue? Or am i doing something wrong?

**Comment by qparis** [comment]
> Ok, in this case, like @qparis said, you will have to wait until the linked winebuild issue is resolved if you want an official solution. Btw: @qparis any progress with that regard? Will we provide the required dependencies as part of the Wine package or do you see a better solution?

I think we'd better to think about runtime solution. We could also imagine providing different versions of a given runtime 

> Afaik this can be reproduced for all scripts that are using same configuration? (wasn't told what is this caused by)

On <u>**_your_**</u> system. For example, the scripts will perfectly work on debian and Ubuntu. This is perfectly acceptable for an alpha version. 

> @plata Noted, is there any way to provide lutris wine without changing Engines? ideally something like `.wineDistribution("lutris")`

I don't know why you are trying to pass by force. @plata and I are perfectly aligned

**Comment by Kreyren** [comment]
> On **_your_** system. For example, the scripts will perfectly work on debian and Ubuntu. This is perfectly acceptable for an alpha version.

@qparis Good thing i'm using ubuntu 18.04 as backup OS to which i can boot to..

**Not on MY system!!**

This is no where near "works perfectly on ubuntu".. 

https://www.youtube.com/watch?v=mqrFQUCI4Vo&feature=youtu.be
- 3:33+ Relevant
- 3:44 - Removes source of phoenicis and downloads new from github on Ubuntu
- 7:09 - Tries to install things,
- 7:15 ~ 24:29 - Age Of Empires, Hangs and won't install.
- 24:37 ~ 24:45 - Assassin's Creed III, results in fatal.
- 25:03 ~ 25:11 - League Of Legends, results in fatal.
- 25:24 ~ 39:32 - Civilization V, hangs and won't install.
- 39:55 ~ 40:04 - STAR WARS The old republic, results in fatal.
- 40:22 ~ - Mafia II, with helping hand is able to run Mafia II that is working on garbage/silver..﻿

https://github.com/PhoenicisOrg/scripts/pull/797#issuecomment-454341965 - Doesn't work on mint either

On ubuntu results in:
![image](https://user-images.githubusercontent.com/11302521/53288385-548ab580-3787-11e9-88cf-29b3d4047131.png)

Yes it's alpha. it's acceptable, but still i can make 5 working scripts using KUWAC in the time that i've tried to install one game on phoenicis..

> I don't know why you are trying to pass by force. @plata and I are perfectly aligned

No asking for info since i don't understand how to use it for hotfix to use lutris wine since wine-sources doesn't seem to work based on instructions on readme..

It's unethical for me to try to pass by force in anything OSS.. 

I want a way for endlessOS users to play league of legends without installing portage and phoenicis is currently the only option excluding using gentoo as slave OS.
- Lutris not present
- Wine not present
- Relevant: https://community.endlessos.com/t/how-do-i-get-lutris-or-wine-on-endless-os-3/5885/12?u=kreyren

**Comment by qparis** [comment]
The screenshot you are showing here is not related to the discussion, so I really don't know how to handle this discussion in a rational way.

* ... of course you'll encounter problem when running the latest snapshot. 

* Wine works perfectly providing you have the required dependencies ... Wine is not present, so it's likely that you don't have the dependencies. So it's perfectly normal if it does not work. 

* We need to handle the problem of the runtime so that installation of dependencies is no longer required. **We are aware of it**, this has already been discussed before. There are no need to pour oil on the fire. If you want to help the project to improve, you can send a merge request on phoenicis-winebuild so that it can generate runtimes. 

* At this point, our priority is to make the software usable. The alpha stage is only meant for people that: 
 - Can report problem _we have not seen before_ (this is not the case here as we are perfectly aware if it) 
 - Want to install games. However, at this point of the developement we cannot guarantee that it will work and people may require some hacking skills in some situation. (Like manually installing dependencies as long as runtime is not supported). To that matter, be aware that we are not going to deviate the product from its trajectory just so that people can install game at all cost. Not at this stage. We are trying to build something stable and it takes time. KUWAC is not stable in time, I can guarantee you. 

* By the way KUWAC is a 50 line bash script, this is nothing comparable to what phoenicis is. It is more comparable from the very first version of POL. We are perfectly aware that running wine from a bash script is simple. This is absolutely not the point.

Please be patient.

**Comment by Kreyren** [comment]
> The screenshot you are showing here is not related to the discussion, so I really don't know how to handle this discussion in a rational way.

Elaborate? I don't understand the error. 

btw. didn't meant to be offensive.. meant to provide reasoning to why i want to use different wine and why making MR for script repo is not possible.

> * Wine works perfectly providing you have the required dependencies ... Wine is not present, so it's likely that you don't have the dependencies. So it's perfectly normal if it does not work.

I believe i have all deps? http://ix.io/1BQP

> * We need to handle the problem of the runtime so that installation of dependencies is no longer required. **We are aware of it**, this has already been discussed before. There are no need to pour oil on the fire. If you want to help the project to improve, you can send a merge request on phoenicis-winebuild so that it can generate runtimes.

Noted, learning java because of phoenicis.. I'm not confident enough to contribute yet but i will.. For now i want to use hotfix can you provide more info for me to make it work?

> * Want to install games. However, at this point of the developement we cannot guarantee that it will work and people may require some hacking skills in some situation.

Thats why i want to use lutris's wine or custom.. 

> * KUWAC is not stable in time, I can guarantee you.

Stop baiting me :D 

> * By the way KUWAC is a 50 line bash script, this is nothing comparable to what phoenicis is. It is more comparable from the very first version of POL. We are perfectly aware that running wine from a bash script is simple. This is absolutely not the point.

Noted, i recommended KUWAC to be invoked in POL console to be supported since i would like to make some scripts in it for phoenicis otherwise i wanted to provide it for comparison to provide system wine option since i don't want precompiled bloat on my system >.>

**Comment by qparis** [comment]
> > The screenshot you are showing here is not related to the discussion, so I really don't know how to handle this discussion in a rational way.
> 
> Elaborate? I don't understand the error.
> 
> btw. didn't meant to be offensive.. meant to provide reasoning to why i want to use different wine and why making MR for script repo is not possible.
> 
> > * Wine works perfectly providing you have the required dependencies ... Wine is not present, so it's likely that you don't have the dependencies. So it's perfectly normal if it does not work.
> 
> I believe i have all deps? http://ix.io/1BQP

Even 32bits one? 

> 
> > * We need to handle the problem of the runtime so that installation of dependencies is no longer required. **We are aware of it**, this has already been discussed before. There are no need to pour oil on the fire. If you want to help the project to improve, you can send a merge request on phoenicis-winebuild so that it can generate runtimes.
> 
> Noted, learning java because of phoenicis.. I'm not confident enough to contribute yet but i will.. For now i want to use hotfix can you provide more info for me to make it work?

Phoenicis winebuild is written in python, not Java. We can of course provide hotfixes, but keep in mind that we are doing this in best effort and that the amount of time spent on supporting not definitive workaround is less time spent on creating a permanent and clean fix. We need to find the right balance

> 
> > * Want to install games. However, at this point of the developement we cannot guarantee that it will work and people may require some hacking skills in some situation.
> 
> Thats why i want to use lutris's wine or custom..
> 
> > * KUWAC is not stable in time, I can guarantee you.
> 
> Stop baiting me :D

That's fine. I'm not baiting, I'm just trying to provide the hindsight I have because of POLv4 which has been build exactly the way you are describing (a bash kernel and a UI on top of this) 


> > * By the way KUWAC is a 50 line bash script, this is nothing comparable to what phoenicis is. It is more comparable from the very first version of POL. We are perfectly aware that running wine from a bash script is simple. This is absolutely not the point.
> 
> Noted, i recommended KUWAC to be invoked in POL console to be supported since i would like to make some scripts in it for phoenicis otherwise i wanted to provide it for comparison to provide system wine option since i don't want precompiled bloat on my system >.>

Most of our user do not care about having precompiled wine on their system as long as it works well. Keep this in mind

**Comment by Kreyren** [comment]
> Even 32bits one? 

I believe so.. you can check installed packages list
```wine-staging-amd64/testing,now 4.2~buster amd64 [installed,automatic]
wine-staging-i386/testing,now 4.2~buster i386 [installed,automatic]```

> Phoenicis winebuild is written in python, not Java. We can of course provide hotfixes, but keep in mind that we are doing this in best effort and that the amount of time spent on supporting not definitive workaround is less time spent on creating a permanent and clean fix. We need to find the right balance

Focus on the development then.. I can make hotfixes myself untill there is a permanent fix.

> That's fine. I'm not baiting, I'm just trying to provide the hindsight I have because of POLv4 which has been build exactly the way you are describing (a bash kernel and a UI on top of this)

Noted

> Most of our user do not care about having precompiled wine on their system as long as it works well. Keep this in mind

Noted, but still prefers compiled.
