### ISSUE TITLE
Build instructions for Ubuntu 18.04 fail because of non-working JDK download URL

### ISSUE THREAD

**Issue by PJaros** [PhoenicisOrg/phoenicis#1858]
### Expected behavior
After following the build instructions on https://phoenicisorg.github.io/phoenicis/Developers/build/ for Ubuntu 18.04  I expected to get a build version of phoenicis. 

### Actual behavior
The instructions doesn't work on the step for downloading openjdk-11+28_linux-x64, the tar.gz files doesn't get downloaded. Thus one can't build phoenicis.

### Steps to reproduce
Run the instruction `wget https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz -O /tmp/openjdk-11+28_linux-x64_bin.tar.gz` and see for yourself.

### Suggestion to get a workable build
```
wget https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz -O /tmp/openjdk-11.0.1_linux-x64_bin.tar.gz
sudo tar xfvz /tmp/openjdk-11.0.1_linux-x64_bin.tar.gz --directory /usr/lib/jvm
mkdir ~/src
cd ~/src
git clone https://github.com/PhoenicisOrg/phoenicis.git
export JAVA_HOME=/usr/lib/jvm/jdk-11.0.1
cd phoenicis
mvn clean package
cd phoenicis-dist/src/scripts
bash phoenicis-create-package.sh
cd ~/src/phoenicis/phoenicis-dist/target/
sudo dpkg -i Phoenicis_5.0-SNAPSHOT.deb

```

**Comment by Kreyren** [comment]
```kreyren@kreyren:~$ wget https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz -O /tmp/openjdk-11+28_linux-x64_bin.tar.gz
--2019-02-24 10:07:16--  https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz
Resolving download.java.net (download.java.net)... 2.17.14.47
Connecting to download.java.net (download.java.net)|2.17.14.47|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-24 10:07:20 ERROR 404: Not Found.
```

Ubuntu 18.10

**Comment by Kreyren** [comment]
Found new source on https://jdk.java.net/11/

**Comment by Kreyren** [comment]
@PJaros Recommends compiling master using:

```cd &HOME && git clone https://github.com/PhoenicisOrg/phoenicis.git && cd phoenicis && mvn clean pacakge && mvn install && sudo echo "#!/bin/bash
if [[ -e $HOME/phoenicis ]];then
cd phoenicis-javafx/ && mvn exec:java
fi" >> /usr/bin/phoenicis && sudo chmod +x /usr/bin/phoenicis && phoenicis
```

**Comment by PJaros** [comment]
@Kreyren Thank you for the compile recommendation, I've adapted it since this didn't work out of the box for me:

* switch `>>` to `>` to replace the file instead of adding to it
* Escaped the newlines for the echo-step and switched from `"` to `'`

# My own stuff
* moved the `$HOME` to `~/src`
* also I need to export JAVA_HOME

mkdir ~/src && cd ~/src/phoenicis && export JAVA_HOME=/usr/lib/jvm/jdk-11.0.1 && mvn clean package && mvn install && sudo echo -e '#!/bin/bash\n
if [[ -e ~/src/phoenicis ]];then\n
cd ~/src/phoenicis/phoenicis-javafx/ && mvn exec:java\n
else\n
echo "FATAL: ~/src/phoenicis is not present"\n
fi' > /usr/bin/phoenicis && sudo chmod +x /usr/bin/phoenicis && phoenicis

**Comment by Kreyren** [comment]
> * switch `>>` to `>` to replace the file instead of adding to it
> * Escaped the newlines for the echo-step and switched from `"` to `'`

I've made that script for you on this usecase feel free to change it, but it's not meant to be used officially. otherwise it's expected to follow provided readme.md. 

> * also I need to export JAVA_HOME
This should be done automatically by apt on ubuntu based on my experience. Can you confirm?

**Comment by plata** [comment]
Sorry, I got a bit lost in the discussion. What is the real issue in the end? The link is wrong or something else?

**Comment by PJaros** [comment]
Yeah, the link is wrong.
Current: https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz
Fix: https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz

**Comment by Kreyren** [comment]
@plata Should i include https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz in  #1860 ?

**Comment by plata** [comment]
@Kreyren I would prefer to have a separate PR only fixing this specific issue.

**Comment by Kreyren** [comment]
@plata created fix just for URL
