### ISSUE TITLE
The container panel in the container tab sometimes doesn't contain all expected tabs

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1865]
Sometimes when opening the container panel it doesn't show all expected tabs.
For me this happens when I directly open the `Containers` tab and select a container.
If I afterwards go to the `Engines` tab, wait until it is completely loaded, then go back to the `Containers` tab and then reselect the container, the container panel shows all expected tabs.

This effect is much more visible in #1864 for me. I believe the reason for this issue to be a timing issue.
Where the verbs, engine settings and engine tools are not loaded at the moment when the container panel is shown.

Screenshot (missing the engine settings):
![grafik](https://user-images.githubusercontent.com/18488086/53445799-b3fbf600-3a11-11e9-9a69-0cf4fc62f595.png)

**Comment by madoar** [comment]
I did also observe this effect with the alpha-2 build.

**Comment by plata** [comment]
There's a missing dependency to the repository somewhere. If you ensure that the repository has been loaded (e.g. by opening the apps tab), this does not happen.

**Comment by madoar** [comment]
What do you mean by missing dependency to the repository?
The `AppsController` only adds a callback to the `RepositoryManager` and triggers the callbacks, which the `ContainerController` does as well. I don't see anything missing when loading the `Controller` tab?

**Comment by plata** [comment]
It seems to me that the repository must already be loaded before creating the tabs in the container panel. So the callback doesn't seem to be able to create the engine tools tab etc. if the container panel is already open.
