### ISSUE TITLE
BUG: Settings/Repository : Doesn't works as expected.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1875]
### Expected behavior
Move priority of repositories, ~and not ripping my hair off my head~

### Actual behavior
https://youtu.be/gC8lazCn4nM?t=62

### Steps to reproduce
Try to change repository priority in settings

### System information
![image](https://user-images.githubusercontent.com/11302521/53686090-4f97aa00-3d23-11e9-82e4-e6d0dce156c9.png)

**Comment by Kreyren** [comment]
Blocker for https://github.com/PhoenicisOrg/scripts/pull/854#issuecomment-468943109

**Comment by plata** [comment]
Please use a title and description which is a bit more explanatory.

**Comment by Kreyren** [comment]
@plata sorry didn't realize that i had wrong resolution on obs, will reupload

**Comment by Kreyren** [comment]
@plata Actuall behavior reuploaded, notice that phoenicis hard freezes when repository is dragged

**Comment by plata** [comment]
Closed because issue is not described in a way that the observed problem can be reproduced or understood which makes it impossible to handle this.

**Comment by Kreyren** [comment]
@plata https://youtu.be/gC8lazCn4nM?t=65 

What else do you want? The issue is that it's pita to change the priority order of provided source for scripts

**Comment by plata** [comment]
We need a textual description of the behavior, what you do not like about it and how you think it should be improved.

**Comment by Kreyren** [comment]
## Actuall
I try to move repository and it sticks to my pointer without me beeing able to escape it moving it everywhere else then expected in the process + Is not intuitive.

**Comment by plata** [comment]
So issue should be: Selected item cannot be released when trying to re-order repositories. Is this correct?

**Comment by Kreyren** [comment]
it rather seems to be moving priority on random when end-user tries to change it's position and it's confusing and infuriating to use..

**Comment by plata** [comment]
Can you come up with a title and textual descriptions which describes this properly? Like I stated above, we need something which is clearly understandable for everybody. If so, I would be willing to re-open the issue.

**Comment by Kreyren** [comment]
i see what i can do

**Comment by madoar** [comment]
The issue sounds familiar to me. @plata didn't I have this issue before I forces JavaFX to use GTK 2 instead of GTK 3?

@Kreyren are you using GTK 2 or 3?

**Comment by plata** [comment]
Can't quite remember.

**Comment by madoar** [comment]
@Kreyren see also https://github.com/PhoenicisOrg/phoenicis/pull/1778#issuecomment-459106374

**Comment by Kreyren** [comment]
@madoar if it would work this way i would be happy, recommends also release the change once MOUSE1 is release so that you woudn't have to click, drag, click again -> click, drag, release MOUSE1 expected.
