### ISSUE TITLE
Abstract: Make a roadmap

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1898]
Suggesting to make a roadmap as refferenced in https://github.com/PhoenicisOrg/phoenicis/issues/328 so that contribution to phoenicis are possible + to direct workflow.

**Comment by plata** [comment]
We had a GitHub project some time ago. We deleted it because it was only additional work. It's our free time so everybody just picks tasks he is interested in. We have some order based on the milestones but that's it.

**Comment by Kreyren** [comment]
@plata I mean something like this https://github.com/kamranahmedse/developer-roadmap

Could be done in .md file as

- Feature
-- Do this
-- Do this
--- Needs this
--- Needs that
etc..

I feel like current development of phoenicis is chaotic and that the software is ready to be used for script maintainers so this would help a lot based on available info..

i believe that lutris has much worse core then phoenicis has atm based on my personal experience..

**Comment by Kreyren** [comment]
Obsolete
