### ISSUE TITLE
Abstract: Labeling system

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1900]
I've noticed that alacritty is using system to assign:
- Priority
- Affected Component
- Difficulty of the issue to be resolved
- etc..

https://github.com/jwilm/alacritty/issues

I recommend adapting simmilar system here.

**Comment by plata** [comment]
Can you explain how this labeling system is superior to the one we use?

**Comment by plata** [comment]
Apparently not.

**Comment by Kreyren** [comment]
@plata Seems to me that the development is chaotic and this would help focusing on important issues over minors.
