### ISSUE TITLE
Abstract: Rolling Release!

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1905]
As referenced on https://github.com/PhoenicisOrg/scripts/issues/893 most application on Alpha/Beta are not working  (if any) making phoenicis unusable garbage on most distros where compiling master is not an option or user is incompetent to do so..

Why don't we make rolling release?
- More applications would work on phoenicis
- Way less bugs
- DIstros would always have a new version
- More effective release
- Compiling new release should be painless assuming that maven is used
- Would allow me to enslave testers to make more scripts working.
- Would permanently solve:
  - https://github.com/PhoenicisOrg/phoenicis/issues/1858
  - https://github.com/PhoenicisOrg/phoenicis/issues/1757
  - https://github.com/PhoenicisOrg/scripts/issues/893
  - https://github.com/PhoenicisOrg/phoenicis/issues/1584 (and issues alike)
  - And other Alpha/Beta problems caused by using outdated version. 

In theory make some way to auto-patch phoenicis to make sure that users always have latest version?

**Comment by plata** [comment]
This is not possible. Rolling release would require that we are able to synchronize scripts and software. As you can add your own scripts repository, this does not work.

**Comment by Kreyren** [comment]
@plata why woudn't it

**Comment by madoar** [comment]
@Kreyren depending on how you think about it we already support rolling releases.
The question is which repository you add to Phoenicis.
If you add the master branch of the script repository to your Phoenicis installation you will always receive the most current script versions.

The issue you're possibly facing then is that the scripts are too new for your Phoenicis installation.
You will stumble over this if you try to add the script repository master branch to an `alpha-2` or `alpha-1` installation.

**Comment by Kreyren** [comment]
> depending on how you think about it we already support rolling releases.

Not true assuming that lots of distros have beta version ONLY. 

> The question is which repository you add to Phoenicis.

> The issue you're possibly facing then is that the scripts are too new for your Phoenicis installation.
You will stumble over this if you try to add the script repository master branch to an alpha-2 or alpha-1 installation.

What about changes to client itself? it should have some autoupdate feature + packaging is not acceptable since phoenicis is unusable in any downstream compatibility due release.

> If you add the master branch of the script repository to your Phoenicis installation you will always receive the most current script versions.

Doesn't seem to be true look for https://github.com/PhoenicisOrg/scripts/issues/893 where script doesn't work with master repository.
