### ISSUE TITLE
Integrate gitpod?

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1915]
It might potentially make it easier for people to get started/contribute. However, in a first quick try I wasn't able to compile.

What do you think? Shall we consider this or not?

**Comment by plata** [comment]
Ok, you need to set `JAVA_HOME` to compile:
```
export JAVA_HOME=/home/gitpod/.sdkman/candidates/java/11.0.2-open/

**Comment by plata** [comment]
Running JavaFX doesn't work right away but it looks like it's possible to work around that limitation:
https://medium.com/gitpod/developing-native-ui-applications-in-gitpod-15af2967c24e

**Comment by madoar** [comment]
`gitpod` integration sounds like an interesting idea. In addition to running JavaFX I see another possible issue. A core part when playing around with the Phoenicis code is running scripts. Is this possible (allowed) with `gitpod`?

**Comment by plata** [comment]
@madoar I just tried installing Notepad++. Worked until the shortcut creation (it cannot find the exe). Maybe we should debug that.

**Comment by Kreyren** [comment]
QA: Assuming gitpot beeing already integrated based on project README.md -> close issue?

**Comment by plata** [comment]
Yes, can be closed.
