### ISSUE TITLE
[Questions before install as flatpak] Please your kind help

### ISSUE THREAD

**Issue by Nokia808** [PhoenicisOrg/phoenicis#1920]
Hi. I have no other place to ask other than here. 
I'm thinking to install Phoenicis from Flathub as flatpak because it will be sandbox by default (security).

However, I have following questions before installation:
1) does sandbox feature of flatpak is enough to protect against possible virus run or other dangerous program ? Is this sandbox feature of flathub is equal to that od Firejail ?
2) there are many Windows applications not officially supported by Phoenicis I need to run them under Wine. So, does Phoenicis allow manual installation of such Windows applications that officially not supported ?
3) does Phoenicis make different (separated) Wine for each Windows application installed, like PlayOnLinux ? If yes, then
4) does Phoenicis allow user to select which Wine version used for each application ?

Please, kindly, to address these points one by one.

**Comment by plata** [comment]
1. You should ask the flatpak developers about this.
2. Yes. Apart from that it's quite easy to write your own installtion scripts for unsupported apps.
3. Yes, every app gets a separate prefix.
4. Yes. Currently, it's not yet possible to switch the Wine version from the GUI but there's a config file.

**Comment by Nokia808** [comment]
Thank you for response. 

Only about point (3) I need further explanation: does this mean that Phoenicis will download new wine for each new application that installed or it has already pre-build wine versions ? If it has only pre-build wine versions then how many they are ?

**Comment by plata** [comment]
It will download the required Wine version if not installed already. So e.g. if two apps use the same Wine version, it will only be installed once (the apps will be in different prefixes so).

**Comment by Kreyren** [comment]
@Nokia808 Depending on what do you expect from security you might want to consider making custom kernel with security patches and harden your provided distro, rolling distros are usually the most effective for this usecase assuming that you don't have to wait for patches weeks or months like ubuntu and simmilar.

You might even consider some antivirus with updated definitions for linux malware, but that depends on system used assuming that Linux is actively maintained without hotfixes for issues (like windows, thus the need for antiviruses) which is making antivirus useless, but it might be helpful for pebcak to invoke something that would cause possible harm like `rm` assuming application that specifically requires root or is build to cause a damage using builtin linux functions alike:

```bash
[$UID == 0] && rm everything
```

**Comment by Artem12570** [comment]
I do not start the installation and rather it starts, but the download goes and goes and does not show anything please help

**Comment by Kreyren** [comment]
> I do not start the installation and rather it starts, but the download goes and goes and does not show anything please help

I don't see how is this issue relevant to issue presented -> **FILE A NEW ISSUE!**

**Comment by plata** [comment]
Could be https://github.com/PhoenicisOrg/phoenicis/issues/1807. Do you see the same behavior described there?

**Comment by Artem12570** [comment]
Not. When I launch Phoenicis playonlinux, then I have a download in the "Applications" menu, but it does not load. I have an Acer laptop, OP Endless




>Четверг, 18 апреля 2019, 13:33 +04:00 от plata <notifications@github.com>:
>
>Could be  #1807 . Do you see the same behavior described there?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Aртём Жевлаков

**Comment by plata** [comment]
What do you mean by "it does not load"? What exactly is "it"? Can you share a screenshot?

**Comment by Artem12570** [comment]
--
Отправлено из Mail.Ru для Android четверг, 18 апреля 2019г., 13:15 +03:00 от plata  notifications@github.com :

**Comment by Artem12570** [comment]
I'm sorry, I just live in Russia, so everything is in Russian.




>Четверг, 18 апреля 2019, 14:21 +04:00 от Aртём Жевлаков <gevlakovar@mail.ru>:
>
>--
>Отправлено из Mail.Ru для Android четверг, 18 апреля 2019г., 13:15 +03:00 от plata  notifications@github.com :
>
>>What do you mean by "it does not load"? What exactly is "it"? Can you share a screenshot?
>>—
>>You are receiving this because you were mentioned.
>>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Aртём Жевлаков

**Comment by plata** [comment]
> I'm sorry, I just live in Russia, so everything is in Russian.

I'm assuming you are referring to a screenshot which should be uploaded here? (It's not visible anywhere).

**Comment by Artem12570** [comment]
--
Отправлено из Mail.Ru для Android четверг, 18 апреля 2019г., 15:22 +03:00 от plata  notifications@github.com :

**Comment by plata** [comment]
It's not visible. I guess you must login on GitHub to upload the image.

**Comment by Artem12570** [comment]
But I went to your site a long time ago. How can I find you there to take a screenshot?



>Четверг, 18 апреля 2019, 19:45 +04:00 от plata <notifications@github.com>:
>
>It's not visible. I guess you must login on GitHub to upload the image.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Aртём Жевлаков

**Comment by plata** [comment]
You can copy+paste the screenshot in this issue directly (see https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests). I think it just doesn't work if you reply to the email.

**Comment by plata** [comment]
I think the original questions of this issue have been answered. Feel free to open a new issue if something is still open.
