### ISSUE TITLE
Question: When will phoenicis be usable?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1921]
So far i wasn't able to make anything working on phoenicis excluding Mafia II with performance issue that was huge PITA to set up..

Any ETA on whatever you are doing with phoenicis core (for 3 years or so based on commits) so that development can be focused on scripts and based around games working on phoenicis?

Or can you partially restore development on PlayOnLinux 4 assuming that phoenicis is **NOT USABLE** ?

**Comment by plata** [comment]
I cannot share the impression that Phoenicis is not usable. If you have any particular problem, feel free to open an issue for it. This general remark is not helpful for anybody. Same for anything that might stop you from developing scripts.
Apart from that: As development happens in our spare time, there will not be an ETA.

**Comment by Kreyren** [comment]
@plata issues ware filed 
https://github.com/PhoenicisOrg/phoenicis/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AKreyren+
https://github.com/PhoenicisOrg/scripts/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AKreyren+

i'm aware the this issue is not helpful generally, but i believe that it's neccesary assuming that phoenicis is in development since 2016 and that it still can't be used to manage any wineapp (excluding hearthstone maybe) and PlayOnLinux 4 is seemingly not actively maintained assuming that scripts are not reviewed and updated..

So i'm proposing focus development on scripts over core -- or -- restore development on PlayOnLinux 4 with expected result to have working lutris alternative. 

if development of PlayOnLinux 4 is restored requesting to make repository on github for script to make maintainance easier..

**Comment by plata** [comment]
Which of these issues prevent you from using Phoenicis or writing the scripts you need?

I cannot agree to this statement (unless you prove it to be true):
> it still can't be used to manage any wineapp

**Comment by ImperatorS79** [comment]
The only issue that is really a pain is the runtime one IMHO, because it prevents potentially any apps from working.

**Comment by plata** [comment]
I can agree to that point. But apart from that?

**Comment by Kreyren** [comment]
From https://github.com/PhoenicisOrg/phoenicis/issues/1924#issuecomment-488840563

> provide good services with good quality code even if it takes time.

That would mean to make something that is sanitized and has a good base to work from.. so far you can't even make wine working and refusing my proposed solutions which would be the most effective for all parties meaning:
- Modular patches for engines 
- verbs that can be installed/removed on demand.
- Support everything in the name of GNU, alike mods and native games + winetricks + wiki, discord, etc..
~~ - java is shit ~~ 

I'm contributing all the time in installers and research + i'm willing to help with engines since i can compile everything with required functions on gentoo/exherbo..

if this is your qualification to provide good quality code then please rather rush it.. From my experience you usually want to make something that gets the job done based on **provided abstract** and then improve it.. 

So far i didn't see any abstract nor any milestones resulting in so far pointless software that can't handle most of it's scripts without issues.. So far i was able to get ONLY hearthstone (with issues) and mafia II (with issues) working.. Rest are totally unusable based on my tests and experience.

Or what are you exactly doing on the phoenicis? Why can't we focus development around working scripts and then focus on improving the core? Practically just something that executes javascript installers from CLI would be sufficient at this point..

**Comment by qparis** [comment]
@kreyren, I will just close this issue. The tone you are employing is not acceptable. 

We have no obligation on rushing. If you think you can do better, please do so.

**Comment by Kreyren** [comment]
@qparis i dont meant to be insulting i want to have working lutris alternative to which i can contribute scripts to and assuming that phoenicis is beeing work on for 4 years which is still not usable for any wineapp i don't really know where to contribute to..

**Comment by qparis** [comment]
If it takes 4 years, its not about the choice we are making, it’s all about the time we want to devote to the project.

Lutris’ owner has many more time than I have, and do not have the same targets (games / apps, all emulators / wine, Linux only / multiplateforme)

Assuming that I have little time to devote, I had two alternatives: stop working and close POL, or giving everything I can while making things as much open as possible so that people can contribute. I chose the second plan. 

If you are not happy by the planning, you can either:
- contribute ;
- do as I did 13 years ago, I.e build a new wine based project from scratch.

If you can’t, then I really thing that you have no rights to complain.

**Comment by Kreyren** [comment]
> contribute ;

So can i make a MR on a wine that would be specific to league of legends or any other app that has wine issues before you fix it? Or where can i contribute? It seems to me that you are overengineering it without adding new functions.. Make some abstract and milestones for Alpha, Beta and Release.. 

> do as I did 13 years ago, I.e build a new wine based project from scratch.

Done https://github.com/Kreyren/KreyOverlay/tree/master/games-moba/.leagueoflegends, done https://github.com/RXT067/KREYROCK and done https://github.com/RXT067/Scripts/tree/master/KUWAC 

meaning that i can make portage and paludis to make the configuration for me and everyone using those two distros in theory for other package managers as well + KUWAC.. 

Just to clarify: My abstract was to contribute in phoenicis with scripts and research only so that other ppl can use more apps on linux painlessly..  if you can provide modular verbs and patches i can contribute more + make more wineapps working..  if you provide GUI to make all the configuration needed i can mentor community to make and maintain scripts.
