### ISSUE TITLE
Request: Allow winetricks as alternative to verbs

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1924]
Requesting adding compatibility for winetricks as alternative to verbs in scenario where required verb is not present.

**Comment by plata** [comment]
@qparis we talked about this already, right? What was the final decision again?

**Comment by qparis** [comment]
The decision was not to use winetricks.

**Comment by plata** [comment]
So @Kreyren missing Verbs must be implemented in Javascript.

**Comment by Kreyren** [comment]
agree with not using winetricks, phoenicis verbs are supperior, but it woudn't hurt to have a compatibility.

**Comment by madoar** [comment]
If you want to support for winetricks you could in theory write a Verb, which functions as a wrapper for winetricks. This verb could take the winetricks command as an argument and then execute the command on the applied wine prefix.

**Comment by Kreyren** [comment]
> If you want to support for winetricks you could in theory write a Verb, which functions as a wrapper for winetricks. This verb could take the winetricks command as an argument and then execute the command on the applied wine prefix.

That would be cool for cases where we dont have verbs for said workarounds to be used as hotfix..

**Comment by qparis** [comment]
Don’t agree. This would cause problems and encourage people not to write scripts

**Comment by Kreyren** [comment]
@qparis well assuming that you expect the scripts to provide modular workarounds then that is already a very good encouragement over using winetricks..

**Comment by qparis** [comment]
I don’t get your point sorry

**Comment by Kreyren** [comment]
@qparis i was told that phoenicis verbs are expected to be modular alike: if DXVK is installed it can be removed on demand and vice versa.. 

Which is HUGE advantage over winetricks

**Comment by qparis** [comment]
First of all, as said before, it is almost impossible to make verbs uninstallable.

Second, using winetricks:
- make us depend on another component and it is hard to track its change. 
- can be though to make it work on other platform like android 
- needs us to ensure that the right wine version with the right path are executed. It will force us to rewrite some wine logic in bash, and we don’t want to do that

On top of that, expect nobody to write a verb once winetricks is used. In addition, writing a verb is a mater of 10 minutes, so I see more problems than solutions here

**Comment by Kreyren** [comment]
>  it is almost impossible to make verbs uninstallable.

Disagree it's simple to perform

> make us depend on another component and it is hard to track its change.

Not really assuming that we are interacting with same wineprefix using same tools like we would on wine without phoenicis..

> needs us to ensure that the right wine version with the right path are executed. It will force us to rewrite some wine logic in bash, and we don’t want to do that

True probably, but that is not hard to do afaik.. 

In general i agree with NOT providing winetricks, but since you said that development of phoenicis is done in your freetime then this would be a good hotfix untill the script is able to be pushed in official release.. untill then they can stay in testing.

**Comment by qparis** [comment]
It’s not simple at all to perform. Really far from being simple. You just cannot assert that without having tried by yourself.

Let be clear about the philosophy of phoenicis : if we want to create a software that is usable without taking care about the quality, we can come out very quickly with something.

However, we do not want (as far as I am concerned at least) to race to release something. We are just people that like coding and provide good services with good quality code even if it takes time. 

If you want to make it quicker, do not try to decrease the quality. Instead, I encourage you to contribute

**Comment by Kreyren** [comment]
> It’s not simple at all to perform. Really far from being simple. You just cannot assert that without having tried by yourself.

it is simple i'm doing that everyday.. 
![image](https://user-images.githubusercontent.com/11302521/57114805-ed6b1d80-6d42-11e9-9339-190b10183858.png)

You can just sandbox them and apply the changes once the changes are requested to be removed we can just remove the files installed and redo the changes.. (basics of sandbox)

Rest is refferenced on https://github.com/PhoenicisOrg/phoenicis/issues/1921

**Comment by plata** [comment]
I think this has been discussed as much as possible. We will not support winetricks officially. However, you are of course free to create your own scripts repository which does so (maybe in the way @madoar suggested).
