### ISSUE TITLE
QA: Timer for Wine download.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1929]
Downloading of wine takes forever (+- 8 mins on 500mb/s download).

Recommends adding timer to be used as fixme to remind improvement. 

![image](https://user-images.githubusercontent.com/11302521/56562924-785d5280-65a2-11e9-95b3-05a375e1f644.png)

**Comment by plata** [comment]
8min for the download is not normal. I guess you are suffering from #1807.

**Comment by Kreyren** [comment]
Would still argue to add the timer to the operations with some summary at the end to QA the setup process speed.

**Comment by plata** [comment]
Once the download is started, you get a progress. Not sure if a timer (which can only be a rough estimation) would add more information here.

**Comment by Kreyren** [comment]
@plata not estimation i want time that shows how long it takes for phoenicis to start a wineapp from pushing an installation button for QA.

**Comment by plata** [comment]
If there's no bug, it should start instantaneously.

**Comment by Kreyren** [comment]
still suggesting the timer for QA.. like installation took X seconds after it's finished and before opening the wineapp. it's great way to improve something overtime.

**Comment by plata** [comment]
I have no idea how this time could be determined.

**Comment by Kreyren** [comment]
@plata you press a button -> it starts timer, it opens expected executable -> you stop the timer and output the time.

**Comment by plata** [comment]
What's the point of showing a time when it's already over?

**Comment by Kreyren** [comment]
@plata Quality Assurance

**Comment by madoar** [comment]
I agree with @plata that showing the runtime doesn't seem to be very helpful. Additionally it is difficult to estimate how long a download will take. 

If we are willing to rewrite the whole downloading part we could theoretically add an expectation by averaging the download "speed" over the last x seconds. This average download "speed" (kb/s) could then be used to calculate how long the download would take according to this measurement.

**Comment by Kreyren** [comment]
Outputing how long download will take is not relevant to this issue. I wanted to time the installation process from pressing install button to playing the game so that it can be QA and improved overtime

**Comment by plata** [comment]
Implementing the requested timer would mean adding functionality which is only interesting for developers to the user interface. We will not support this.

**Comment by Kreyren** [comment]
fair enough
