### ISSUE TITLE
REQUEST: Custom wine patches!

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1930]
As referenced on https://github.com/PhoenicisOrg/phoenicis/issues/1876#issuecomment-485898179 

**Requesting new feature** which allows patching wine using script from approved list assuming method to track what wine has which patches applied.

Reason: Would allow way more options to make scripts assuming that not all scripts are working as expected with one standartized build (like lutris's wine which sucks).

Improvement: Some patches should be applied by default with the option to be remove them using scripts.

Sanity check: There should be a method to **VERIFY** that patches ware applied sucessfully.

**Comment by qparis** [comment]
This does already exists. This is exactly the concept of winebuild...

**Comment by Kreyren** [comment]
@qparis This does already exists.

Elaborate afaik there is only upstream and staging branches of wine engine..

**Comment by qparis** [comment]
Nothing prevents us from creating others

**Comment by Kreyren** [comment]
@qparis You missunderstood then i'm requesting it to be user-friendly to apply on demand.

**Comment by qparis** [comment]
It is. You just need to make a merge request on this repository

**Comment by Kreyren** [comment]
@qparis again..

i'm talking **about function in script that would allow modular patches to wine** that can be applied and removed on demand for example:

```
Game A needs patch_1
Game B doesn't work with patch_1

if Game A is started and patch_1 is not present -> Apply it on demand
If Game B is started and patch_1 is present -> Remove it on demand
```

What are you proposing would mean making around 800 wine builds to cover all configurations.

This would mean that we would have ONLY one wine engine -> WINE upstream

To which we can add other patches like staging to get `wine-staging`.

or apply proton patches to get proton.

This means much better maintainance for phoenicis engines since all you need to do is compile **ONE BUILD FOR EACH VERSION** and way more power.. 

This also means that end-user doesn't have to download multiple wine builds for same version.

**Comment by Kreyren** [comment]
Note that we can already do this using javascript, but it needs standartization otherwise it will generate tons of hard to reproduce issues..

**Comment by qparis** [comment]
Nothing prevents us for compiling only one build for a given distribution. I don't see any problem with the current implementation, just more order than what you are suggesting

**Comment by Kreyren** [comment]
@qparis For example league of legends:

Using wine upstream won't work cause of anti-cheat -> Additional patches are required for it to work.

If those patches are present in wine it's possible that they would conflict with other wine apps thats why ppl are making one wineprefix for each app.. 

iiuc your solution is to have multiple winebuilds which is insane.. 

I'm suggesting to make verbs for all required patches and make them modular so that they can be removed and applied for demand.

**Comment by qparis** [comment]
This is not possible. It would require the user to have all dev dependencies installed on their machine

**Comment by Kreyren** [comment]
@qparis 

> It would require the user to have all dev dependencies installed on their machine

No just cherrypicked patches in .Phoenicis dir for the wineapp that utilize them, rest can be on remote -- OR -- you can fetch them from remote all together.
