### ISSUE TITLE
Request: stage release

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1931]
Based on my experience there is lots of problems on alpha_2 which are resolved in master.

~~Assuming that you are not cool enough on rolling release which would solve everything~~ requesting new release + assuming wine issues resolved.

**Comment by plata** [comment]
We have an issue for nightly builds and a milestone for alpha-3 so this issue is duplicate.

**Comment by Kreyren** [comment]
@plata reference the issue plz

**Comment by plata** [comment]
#1739
