### ISSUE TITLE
QUESTION: What is required for runtime?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1932]
-- Noob question warning --

What is required for phoenicis runtime? Can i just compile it and grab .jar from phoenicis-javafx/target/*.jar and point to class or?

**Comment by ImperatorS79** [comment]
What do you mean ?

**Comment by Kreyren** [comment]
@ImperatorS79 If i compile phoenicis using maven how can i just cherrypick pathname required for runtime? meaning what is required for binarry release of phoenicis.

Expected ideally one .jar file to download and run.

**Comment by plata** [comment]
Packaging is described here: https://phoenicisorg.github.io/phoenicis/Developers/packages/

@qparis I just realize that the packaging script is not explained there. Could you add it?

**Comment by Kreyren** [comment]
![image](https://user-images.githubusercontent.com/11302521/56648137-aa41e800-667a-11e9-977e-090605d95454.png)

@plata not sufficient

**Comment by plata** [comment]
```
mvn clean package
cd phoenicis-dist/src/scripts
./phoenicis-create-package.sh
```
Should give you a standalone jar or deb if you are on Debian/Ubuntu.

**Comment by Kreyren** [comment]
Closed, since it's no longer relevant assuming phoenicis considering nightly builds.
