### ISSUE TITLE
Add property to (not) use Wine runtime

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#1940]

**Comment by madoar** [comment]
I don't understand this issue.

What do we achieve by adding such a property?
When/where is it used?

**Comment by plata** [comment]
If we install the Wine runtime to provide all possibly required libraries, this might potentially cause issues on some systems. By adding a property to disable using the runtime (i.e. not adding it to `LD_LIBRARY_PATH`) we can handle those cases.
