### ISSUE TITLE
SUGGESTION: Fetch miniatures online

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1943]
We are using copyrighted material under fair use on miniatures at the moment and since some developers are doing they best to not make linux/mac support this might prove problematic in the future assuming it beeing easily abusable. (Example youtube copyright claims)

I'm proposing to make phoenicis to fetch those miniatures from URL and show them as embedded URL, never download or redistribute, if phoenicis is unable to fetch required miniatures -> Output default or make custom one (Like my hitman absolution and magic the gathering arena)

**Comment by plata** [comment]
I don't think this is a good idea because it will mean that
- users with slow Internet connection have to wait very long
- Phoenicis cannot be used offline (at least if you want to see miniatures)
- miniature cannot be used as shortcut icon/in the library

**Comment by Kreyren** [comment]
> users with slow Internet connection have to wait very long

Not really assuming optimized miniatures.

> Phoenicis cannot be used offline (at least if you want to see miniatures)

I recommended custom miniatures for offline mode as solution or pixelated original..

> miniature cannot be used as shortcut icon/in the library

why not?

**Comment by plata** [comment]
> I recommended custom miniatures for offline mode as solution or pixelated original..

If there is a copyright issue, we still have it with that approach. Where are the custom miniatures supposed to come from?

**Comment by Kreyren** [comment]
@plata What i was using is:
![main](https://user-images.githubusercontent.com/11302521/57815930-b3a20a00-7779-11e9-8a7a-96f8ded7776f.png)

Where original is:
![image](https://user-images.githubusercontent.com/11302521/57815967-c7e60700-7779-11e9-8e30-981d1748d18c.png)

afaik this could have multiple outcomes:
1) I'm original author of said piece which was inspired by original logo
2) This is missrepresenting original brand and is not covered by fair use
3) Is considered as fan art based on original which would be depending on the scenario covered by fair use.
4) using original is under fair use, but abused by developer who doesn't like linux

**Comment by Kreyren** [comment]
So i don't know what would be the most effective approach, but using URL that points to remote file and displaying something default or simmilar is not present might be more sane.

**Comment by plata** [comment]
Honestly I don't believe that changing the logo in this way make it any more legal.

**Comment by Kreyren** [comment]
@plata Based on my experience it depends on many factors not saying that this is best idea that should be interpreted. 

Suggesting fetching them as embeds from URL.

**Comment by madoar** [comment]
I agree with @plata that the main problem will be the time required to fetch each image individually. The current solution has the benefit that everything is downloaded in a single bundle.

Imagine you would download the images separately using embedded URLs and a single URL can't be fetched or you have a slow connection and you can watch the images appearing individually I don't think the users would want that. Another problem would be dead links which would need to be found and removed.

About the idea of having two image sets (one being part of the repository and one downloaded on the fly): I don't think this is a good idea. If we would to that we would need to maintain two images sets. In addition this could lead to changes to images after you've opened the applications page, which would most likely lead to false positive bug reports.

**Comment by Kreyren** [comment]
@madoar 

> I agree with @plata that the main problem will be the time required to fetch each image individually. 

Disagree with the time required to fetch assuming optimized images for this usecase.. it will be slower, but not significantly for example steam, origin etc. are fetching miniatures this way.

> The current solution has the benefit that everything is downloaded in a single bundle.

Making the repository bigger for size of those images and possible copyright problem as presented.. 

> Imagine you would download the images separately using embedded URLs 

No downloading, just viewing them on remote server.

> you have a slow connection and you can watch the images appearing individually I don't think the users would want that. 

Possible scenario, but we can work around this by fetching those in teporary directory if needed or implement a graphical solution which is going to download the image in terrible quality and apply blur untill it's downloaded (uplay does this iirc)

> Another problem would be dead links which would need to be found and removed.

Agree that this is a problem, but in theory we can fetch images from reliable source like wikipedia and force them to be displayed in our expected quality. 

> About the idea of having two image sets (one being part of the repository 

I'm proposing removing all miniatures as i said above we can fetch those from reliable source and force our quality, if there is a connection issue or problem with loading we can display default design with blur that will be replaced with the image as it's beeing downloaded alike:

End-user doesn't have internet connection -> Fetch default miniatures and apply blur on them, once phoenicis client is able to fetch miniatures then show them with blur once we can display them correctly -> Show full version without blur..

Or we can use this blur and forced low quality and display those miniatures on hover.

**Comment by plata** [comment]
As discussed above, we will not implement this request.

**Comment by Kreyren** [comment]
Fair enough, recommends making statement for contributors to contrib miniatures on their own risk.

**Comment by plata** [comment]
I understand your point but I doubt that it's possible to state this in a legally relevant manner.

**Comment by Kreyren** [comment]
fair enough
