### ISSUE TITLE
Please improve sandbox & block it's holes to make Phoenicis safe !

### ISSUE THREAD

**Issue by Nokia808** [PhoenicisOrg/phoenicis#1958]
Hi. Please look to this thread opened by me:

https://github.com/flathub/flathub/issues/960

As you see, one "TingPing" discover big holes in sandbox feature of your flatpak package.

Please take look for this & fix this risks & block all holes in your sandbox. WineHQ now is cleaver enough to run many viruses & spy-wares ..........

**Comment by barthalion** [comment]
It should be closed, no reason to spread the FUD.

**Comment by qparis** [comment]
Thank youu @barthalion
