### ISSUE TITLE
Java 12 support

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1960]

**Comment by plata** [comment]
I guess this requires the GraalVM pr to be merged, right?

**Comment by qparis** [comment]
Actually maybe not... However, it requires we use jpackage from here: https://jdk.java.net/jpackage/

Ironically, I could not make it work with graalvm yet: I'm getting this error at runtime java.lang.module.FindException: Module org.graalvm.truffle not found, required by jdk.internal.vm.compiler

**Comment by qparis** [comment]
Oh I see, nashorn is no longer available... So yeah you are right

**Comment by qparis** [comment]
In fact it seems that it is still supported

**Comment by madoar** [comment]
@qparis on https://jdk.java.net/jpackage/ it is mentioned that the build is based on an incomplete version of JDK 13. Does this mean that the built installer contains a Java 13 JRE?

**Comment by qparis** [comment]
Yep, I have tried to bundle a Java 12 JRE and it does not seem to work. With Java 13, it seems to work great though. I suggest we keep the two scripts (Java 11 and Java 13) to anticipate the future release of Jpackage

**Comment by plata** [comment]
Travis is building with OpenJDK 12, so this issue is fixed. If something else should be done (e.g. regarding packaging with Java 12), please open a new issue for that.
