### ISSUE TITLE
Change shortcut display and edit to deal with new environment variables setup

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis#1962]
If you to edit a shortcut with the new shortcut code in https://github.com/PhoenicisOrg/scripts/pull/956, it will messed up the string stored in the shortcut file (deleting the " and replacing : by =) and then the shortcut will be unreadable. 

![envVar](https://user-images.githubusercontent.com/19779882/58946670-ba270e80-8786-11e9-81f1-493745c073db.png)

**Comment by ImperatorS79** [comment]
@madoar @plata I need you on this ^^.

**Comment by plata** [comment]
I do not have time to check this currently. If you need a starting point, have a look at: https://github.com/PhoenicisOrg/phoenicis/blob/15bc8a0f15afca5556cb332ee64b718ddd39155f/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/ShortcutEditingPanelSkin.java#L55
I could imagine that the issue is somehow related to the `ObjectMapper`. Note that the `.shortcut` file in `~/.Phoenicis/shortcuts` is a json file. I'm assuming that at some point you have to store a list of environment variable in the json.
Can you post the content of the `.shortcut` before and after editing it?

**Comment by ImperatorS79** [comment]
Before:
```json
{"type":"WINE","environment":{"WINEDEBUG":"-all", "COUCOU":"27"},"winePrefix":"7-zip","arguments":"","workingDirectory":"/home/test/.Phoenicis/containers/wineprefix/7-zip/drive_c/Program Files/7-Zip","executable":"/home/test/.Phoenicis/containers/wineprefix/7-zip/drive_c/Program Files/7-Zip/7zFM.exe"}
```
After:
```json
{"environment":"{WINEDEBUG=-all, COUCOU=25}","workingDirectory":"/home/test/.Phoenicis/containers/wineprefix/7-zip/drive_c/Program Files/7-Zip","arguments":"","type":"WINE","winePrefix":"7-zip","executable":"/home/test/.Phoenicis/containers/wineprefix/7-zip/drive_c/Program Files/7-Zip/7zFM.exe"}
```

**Comment by plata** [comment]
I think the problem occurs in:
https://github.com/PhoenicisOrg/phoenicis/blob/15bc8a0f15afca5556cb332ee64b718ddd39155f/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/ShortcutEditingPanelSkin.java#L179

**Comment by ImperatorS79** [comment]
Even the reading seems bad if you look at the screenshot I provided.

**Comment by plata** [comment]
Probably we should not have a line edit but a table with key value pairs for each environment.

**Comment by madoar** [comment]
@plata isn't `shortcutProperties` such a map?

**Comment by plata** [comment]
Not quite sure. Would have to debug and really see what's in there.

**Comment by madoar** [comment]
I've just taken a look at the code regarding this feature request.The `shortcutProperties` contains all the information shown inside the shortcut details and shortcut edit information grids. 

When adding an entry to your `.shortcut` file the entry should automatically be added to the shortcut details and shortcut edit grids, can you please show us how the content is visualized. Even more useful would be to know as what kind of object your `environment` property is loaded.

Can you please add the following line
```java
System.out.println(row.getKey() + ": " + row.getValue().toString() + " | " + row.getValue().getClass().getSimpleName());
```

to line

https://github.com/PhoenicisOrg/phoenicis/blob/15bc8a0f15afca5556cb332ee64b718ddd39155f/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/library/skin/ShortcutEditingPanelSkin.java#L171

and print the result here?

**Comment by ImperatorS79** [comment]
Environment is just define like:
```js
...
var myEnv = {WINEDEBUG: "-all"};
    if (typeof this._environment !== 'undefined') {
        var envJSON = JSON.parse(this._environment);
        Object.keys(envJSON).forEach(function (key){
            myEnv[key] = envJSON[key];
        });
    }

    var trustLevel;
    if (typeof this._trustLevel !== 'undefined') {
        trustLevel = this._trustLevel;
    }
    else {
        trustLevel = "0"; //dummy value
    }

    var ShortcutDTOBuilderClass = Java.type('org.phoenicis.library.dto.ShortcutDTO.Builder');
    var builder = new ShortcutDTOBuilderClass()
        .withId(this._name)
        .withInfo(info)
        .withScript(JSON.stringify({
            type: "WINE",
            environment: myEnv,
            trustLevel: trustLevel,
            winePrefix: this._prefix,
            arguments: this._arguments,
            workingDirectory:executables[0].getParentFile().getAbsolutePath(),
            executable: executables[0].getAbsolutePath()
        }));
...
```

**Comment by madoar** [comment]
@ImperatorS79 yes but this doesn't tell us how the serialized String is afterwards deserialized, i.e. converted back into a "complex" object.

**Comment by ImperatorS79** [comment]
@madoar
```
environment: {WINDEBUG=-all, COUCOU=27} | LinkedHashMap
workingDirectory: /home/test/.Phoenicis/containers/wineprefix/7-zip/drive_c/Program Files/7-Zip | String
arguments:  | String
type: WINE | String
winePrefix: 7-zip | String
executable: /home/test/.Phoenicis/containers/wineprefix/7-zip/drive_c/Program Files/7-Zip/7zFM.exe | String
```

**Comment by madoar** [comment]
Ok, then we need to decide how the UI to set the environment parameters should look like.
As @plata mentioned I believe a table would be best. In addition we will need an `Add` and maybe even a `Remove` button that add and remove environment rows from the table. This would make the logic behind the table quite difficult.

**Comment by plata** [comment]
That's true. Maybe we can first implement an intermediate solution which works with the String like now?

**Comment by madoar** [comment]
Alternatively we could add a read-only solution for now, which only displays the environment variable defined in the code. @ImperatorS79 would such a solution be enough for now or do you require modification support?

**Comment by ImperatorS79** [comment]
The only problem I had was that the configuration messed up when editing the shortcut (as stated in the issue first comment). Why not just fix that part ? (no need to change the interface, just that the string displayed and then edited is {"WINEDEBUG":"-all"} and not {WINEDEBUG=-all} )

**Comment by madoar** [comment]
That is not so easy. The issue is that the `environment` content is not loaded as a String but as a `LinkedHashMap` object. It is just a coincidence that it is converted to a String similar to a JSON object.
Therefore we need to handle it like a `Map` which consists of key-value pairs.

**Comment by ImperatorS79** [comment]
@madoar That would be great if you could put this in your to-do list, because anyone that try to use its shortcut GUI will destroy its shortcut ^^.

**Comment by madoar** [comment]
I will see what I can do. The initial idea is to simply add a `ListView` containing two `TextFields` in each row and two buttons underneath (one used to add a new row to the `ListView` and one used to delete the selected row).

In `view` mode the buttons underneath would be hidden while the `ListView` would be uneditable. In `edit` mode the component would be fully usable. 

@ImperatorS79 would that help?

**Comment by ImperatorS79** [comment]
Seems like a good idea.
