### ISSUE TITLE
HIGH_PRIO: Flatpak security issues

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1965]
Referencing https://github.com/flathub/flathub/issues/960 there are apparently some serious security issues with flatpak provided by phoenicis.

Assuming that flatpak maintainers (namely @TingPing) are too incompetent to resolve them as refferenced on closed issue as "too heated" which is hugging stupid and malpractice we should resolve them here or deprecate flatpak for affected parts of phoenicis.

No usefull info ware provided that i can see to know what the situation is.

**Comment by qparis** [comment]
Sorry but I will stand with flatpak team at this point. There are no such security issue. 

Flatpak is just one chanel of distribution and saying that Phoenicis security relies on it is non sense. 
For example, .deb are not sandboxed at all and have never been. Same for POLv4, same for many many many programs. 

Now, if we want to add a sandbox feature on top of Phoencis, this is another story

**Comment by Kreyren** [comment]
afaik `.deb` is irelevant since apt is not sandboxing tool it's just a way to export packages to live system.. :man_facepalming: 

POLv4 is deprecated why is that relevant. 

What is the issue anyway?
