### ISSUE TITLE
Automatic json-align

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1977]
Please check Travis. There's an issue with json-align. See the [docs](https://phoenicisorg.github.io/scripts/General/tools/#json-align). Note: this requirement is described in the pull request how-to in the README.

_Originally posted by @plata in https://github.com/PhoenicisOrg/scripts/pull/984#issuecomment-499940869_

Can't we make this automatic? it's annoying o.o

**Comment by plata** [comment]
Travis could probably do that. However, it could only do so on our master. So we could not check the alignment in a pull request. Not sure if that's a good idea because it might hide other issues in the json.

**Comment by Kreyren** [comment]
>  Not sure if that's a good idea because it might hide other issues in the json.

elaborate

**Comment by plata** [comment]
I'm not 100% sure right now but I think json-align also checks that the json is valid.

**Comment by Kreyren** [comment]
@plata why is that relevant assuming that QA would fail for the json if it's not valid

**Comment by qparis** [comment]
Travis already checks that json is correctly aligned.

**Comment by Kreyren** [comment]
> Travis already checks that json is correctly aligned.

it is expected to align it if it's not aligned..

**Comment by qparis** [comment]
Nope, a CI hook never modify a merge request. The author remains responsible of its code.

**Comment by Kreyren** [comment]
> Nope, a CI hook never modifies a merge request. The author remains responsible of its code.

it's presented so that it would do it -> so that we don't have to align it for MR

**Comment by qparis** [comment]
It does if you manually type the commands. I don’t see any issue here

**Comment by Kreyren** [comment]
@qparis Why can't we make it automatically
