### ISSUE TITLE
Provide DXVK in phoenicis wine?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1978]
We can in theory load DXVK only for tenfoot (Big Picture) or depending on the implementation i was thinking about providing latest minus one version DXVK in phoenicis wine that can be overwritten by script on demand if game depends on different version.

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/995_

**Comment by ImperatorS79** [comment]
I do not understand. DXVK is already provided by a verb :thinking: .

**Comment by Kreyren** [comment]
@ImperatorS79 This is a discussion about it beeing present by default.

**Comment by plata** [comment]
What's the advantage of having it by default?

**Comment by Kreyren** [comment]
@plata more things working ootb on phoenicis without the need to install DXVK manually to provide d3dx10+ libs. 

There a conflict on game specific scripts for example if game doesn't work on DXVK 1.0, but works on DXVK 0.80 or is expected to use DXV9 etc.. Not sure if this is the best idea so i'm performing sanity check.. We probably want to load standalone DXVK libs for steam tho

**Comment by plata** [comment]
> more things working ootb on phoenicis without the need to install DXVK manually to provide d3dx10+ libs

but probably also a lot of things not working anymore. In my opinion it's much safer to use DXVK only when you are sure that it makes sense.

**Comment by Kreyren** [comment]
agree
