### ISSUE TITLE
Gitpod: install libfreetype amd64 and i386

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis#1983]
When libfreetype is not installed, wine can not rune. This would allow to run small wine apps inside gitpod

**Comment by plata** [comment]
Can you try this?

**Comment by qparis** [comment]
<img width="1437" alt="Capture d’écran 2019-06-10 à 13 18 38" src="https://user-images.githubusercontent.com/373645/59192348-67809480-8b82-11e9-8e81-3bc88f492c25.png">

Seems to work

**Comment by plata** [comment]
That's pretty cool.
