### ISSUE TITLE
PR: Mattermost > Slack

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#2013]
Recommending Mattermost (https://github.com/mattermost) over Slack.

Mattermost is OSS alternative to Slack which is released under MIT licence

Could be probably self-hosted by Phoenicis.

**Comment by plata** [comment]
Looking at our current Slack usage (which mainly does not exist), I have the feeling that we will rather stick to our forums than introducing anything else.

**Comment by qparis** [comment]
Yep
