### ISSUE TITLE
PC Building Simulator script crashes

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#2021]
### Expected behavior
After the `.preInstall` step the script should launch steam with the game ID argument and start the game installation
### Actual behavior
Somewhere in that step I get this error:
```
java.lang.IllegalAccessException: access to public member failed: sun.awt.SunToolkit.getScreenSize[Ljava.lang.Object;@2dcb37ed/invokeVirtual, from public Lookup
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MethodMHImpl.makeMethodHandle(HostMethodDesc.java:318)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MHBase.invoke(HostMethodDesc.java:258)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostExecuteNode$1.executeImpl(HostExecuteNode.java:776)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.GuestToHostRootNode.execute(GuestToHostRootNode.java:87)
	at <js> :anonymous(Unnamed:23:998-1049)
	at <js> go(engines.wine.quick_script.steam_script:145:7919-7953)
	at <js> run(Unnamed:12-27:353-1192)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:358)
	at org.phoenicis.scripts.Installer$$JSJavaAdapter.run(Unknown Source)
	at <js> :program(Unnamed:34:1318-1338)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:367)
	at org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.eval(PolyglotScriptEngine.java:63)
	at org.phoenicis.scripts.interpreter.PhoenicisScriptInterpreter.runScript(PhoenicisScriptInterpreter.java:36)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.lang.IllegalStateException: java.lang.IllegalAccessException: access to public member failed: sun.awt.SunToolkit.getScreenSize[Ljava.lang.Object;@2dcb37ed/invokeVirtual, from public Lookup
```
### Steps to reproduce
Run PC Building Simulator script. I'll see if this issue affects other scripts to see any common treads.
### System information
* software version (git revision) of phoenicis and scripts repositories
https://github.com/PhoenicisOrg/phoenicis/commit/3e7dbda6e208b4506a7219d47d6c7c4519df2bc4
repo commit 
https://github.com/PhoenicisOrg/scripts/commit/99abb1267b1978e0008c1b0177cdb0d2d92a4294
* used operating system
Ubuntu 19.04 x64 5.0.0-17-generic
* used Java version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)

**Comment by ImperatorS79** [comment]
So this is the `java.awt.Toolkit.getDefaultToolkit().getScreenSize()` function which does not work.

@madoar Since you want to get rid of java call in the scripts, maybe you can add a dedicated function for this ?

**Comment by Zemogiter** [comment]
Why java calls in javascripts are undesirable now?

**Comment by ImperatorS79** [comment]
From @qparis :

> IMHO, Ideally, we should avoid calling directly java objects and use beans whenever it is possible.
This would make the scripts more agnostic of the main application

**Comment by Zemogiter** [comment]
Should we then add something like `var defaultToolkit = Bean("getDefaultToolkit");` to the `engines.wine.plugins.virtual_desktop'?

**Comment by ImperatorS79** [comment]
With the java counterpart in phoenicis, I would assume yes, something like that (I do not know how those Beans work ^^).

**Comment by Zemogiter** [comment]
This is what I made based on `utils.functions.filesystem.files`:
```
var defaultToolkit = Bean("getDefaultToolkit");

/**
 * sets Virtual Desktop with window resolution
 * @param {number} width width of virtual desktop (in px)
 * @param {number} height height of virtual desktop (in px)
 * @returns {Wine} Wine object
 */

function setVirtualDesktop (width, height) {
        defaultToolkit.getScreenSize();
}
```
Would this work?

**Comment by ImperatorS79** [comment]
I do not see why you would call this function in `setVirtualDesktop`, but you also need a class in phoenicis for the bean (like `fileUtilities `for the function like `cp`, ...).

**Comment by Zemogiter** [comment]
Shouldn't `getDefaultToolkit` be builtin into java?

**Comment by ImperatorS79** [comment]
You can test ^^ (I am not a java expert).

**Comment by Zemogiter** [comment]
Me neither

**Comment by madoar** [comment]
Where exactly is the `sun.awt.SunToolkit.getScreenSize` call done? I agree such calls shouldn't made directly from the scripts.

**Comment by Zemogiter** [comment]
I don't know. I wasn't able to find it in POL5 repo.

**Comment by plata** [comment]
https://github.com/PhoenicisOrg/scripts/blob/af101cdc524439845a80e7c17506c6e557620985/Applications/Games/PC%20Building%20Simulator/Steam/script.js#L19

**Comment by plata** [comment]
Maybe this must be something like:
```Javascript
var screenSize = Java.type('java.awt.Toolkit').getDefaultToolkit().getScreenSize();
```

**Comment by madoar** [comment]
@plata maybe we should change this to something similar to http://www.java2s.com/Code/Java/JavaFX/GetScreensize.htm (i.e. a JavaFX only solution). Ideally we implement a new `Bean` which does the call in Java and then returns the screen dimensions using an array or a map like @ImperatorS79 suggested. What do you think?

**Comment by qparis** [comment]
I think we should declare a bean ScreenManager maybe

**Comment by Zemogiter** [comment]
Ok but where?

**Comment by plata** [comment]
Probably somewhere in https://github.com/PhoenicisOrg/phoenicis/tree/master/phoenicis-tools/src/main/java/org/phoenicis/tools.

**Comment by Zemogiter** [comment]
Closing because https://github.com/PhoenicisOrg/scripts/pull/1073 solves this issue.
