### ISSUE TITLE
CONCEPT: Support all scripting langs

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#2027]
I was working on this concept that i think could be adapted in phoenicis.

- Simple to adapt
- Self-Sufficient -> No additional maintainance

## Current
Currently we support only javascript with plan to support lutris scripts(https://github.com/PhoenicisOrg/phoenicis/issues/1716).

## Expected
Support all scripting langs

## How?
1) Make phoenicis execute all scripts (core functionality)
2) Adapt sandbox

**Reasoning:** We can make sandbox with a `work` and `image` directory where all the work would be done in `work` directory (What is currently beeing done using javascript) and then moved to `image` where `image` would have files alike: `/home/$USER/Games/somegame` which would be merged in live system if `work` was successful. 

I believe that if we base scripts around making final configuration in `image` directory that we could use all scripting langs since we would expect from all these to provide this final configuration in `image` directory assuming that the work could be done in `work` directory.

Theoretically we would only have to adapt sandbox (which we are currently using anyway in a form of containers) and change javascript to output scripts in `image` from where they would be merged into a live system.

---

Inspired by paludis/portage concept.

**Comment by plata** [comment]
What's the advantage for our users?

**Comment by Kreyren** [comment]
@plata Users would be able to use any scripting lang to install phoenicisapp for contribution without additional maintainance.

**Comment by plata** [comment]
So? (I still do not see the benefit)

**Comment by Kreyren** [comment]
@plata Meaning that we could use any script to install phoenicisapp which is huge benefit.

**Comment by plata** [comment]
Why is it a benefit?
- Does it provide support for any additional app? - No.
- Does it increase maintenance effort? - Yes.
- Does it increase the complexity and thus the potential for errors? - Yes.

**Comment by Kreyren** [comment]
> Does it provide support for any additional app? 

Yes, because i prefer making bash/ion script instead of depending on provided imports + We can use POL4 and lutris scripts.

> Does it increase maintenance effort? 

Not really since you maintain javascript scripts and rest can be community maintained or built from scratch or used in separate repositories.

> Does it increase the complexity and thus the potential for errors?

Depends on the script where my scripts are always perfect -> no errors

**Comment by madoar** [comment]
@Kreyren you're free to provide support for other scripting languages. Our focus is on providing support for JavaScript based scripts. This doesn't mean that we won't agree to adding support for other scripting languages, we just won't add them ourselves. 

Feel free to provide a PR, if the extension is good and it fits inside Phoenicis I see no reason why we shouldn't merge it.

**Comment by Kreyren** [comment]
@madoar Making MR from me is not an option since i would probably have to change a way how phoenicis handles scripts which would be pita to agree on + i suck at java.

I will probably make the MR if none else wants to do it, but i would maintain it in my fork probably..

Currently willing to provide simple javascripts scripts and bash/shell code.

**Comment by Toadfield** [comment]
I would find that feature cool,cause it would be nice to use Lutris installers,cause that's the mainstreaming platform people make scripts for.

**Comment by plata** [comment]
See https://github.com/PhoenicisOrg/scripts/pull/788.
