### ISSUE TITLE
Engine settings are loaded at startup

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#2037]
This should not be required. The engines and engine settings should be loaded only if required (container tab).

**Comment by plata** [comment]
The problem is that `ContainerController` registers the update in the `RepositoryManager`. Maybe we can only mark that something has changed and then load on demand?

**Comment by madoar** [comment]
That should work

**Comment by plata** [comment]
I'm not really sure how this could be implemented with the bindings for the `Skin` classes (it's not only engine settings but also verbs etc.).

**Comment by madoar** [comment]
We would need some kind of trigger `Observable` implementation
