### ISSUE TITLE
Add a new blocking "create" Method to UiQuestionFactory

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#2062]
Currently there is only a non-blocking way to create a `question` dialog. After the user has provided an input (either yes or no), either the yesCallback or the noCallback is invoked.
This approach makes it hard to write sequential scripts. 

Therefore I propose we add a blocking `create` method to the `UiQuestionFactory` implementations. This new method should have the following signature:

```java
/**
 * Asks the user a question where he/she can answer either yes or no
 *
 * @param questionText The question text
 * @return True if the user answered yes and false if he answered no
 */
boolean create(String questionText);
```

See also https://github.com/PhoenicisOrg/scripts/pull/1040 for a use-case

**Comment by plata** [comment]
Is this still relevant after #2067 has been closed?
