### ISSUE TITLE
Java 13

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#2089]
Now that Java 13 has been released we should test against it :)

**Comment by plata** [comment]
Is it available in Travis already?

General question: do we want to go with every release or should we better concentrate on the LTS versions?

**Comment by madoar** [comment]
> Is it available in Travis already?

 I don't know

> General question: do we want to go with every release or should we better concentrate on the LTS versions?

I think it is a good idea to test Phoenicis against every major and minor Java release. The reason is that this will minimize the effort we need to invest in updating compared to doing multiple updates at once (between the major versions).

**Comment by madoar** [comment]
As a sidenote:
It seems like Java 13 doesn't come with the new packager tool, see also https://mail.openjdk.java.net/pipermail/core-libs-dev/2019-June/060701.html
