### ISSUE TITLE
FreeBSD compilation problem javafx

### ISSUE THREAD

**Issue by unwillexist** [PhoenicisOrg/phoenicis#2114]
### Expected behavior
succesful compilation when
mvn clean package -DskipTests
### Actual behavior
[INFO] phoenicis-multithreading ........................... SUCCESS [  6.447 s]
[INFO] phoenicis-win32 .................................... SUCCESS [  8.197 s]
[INFO] phoenicis-tools .................................... SUCCESS [ 15.760 s]
[INFO] phoenicis-repository ............................... SUCCESS [ 11.718 s]
[INFO] phoenicis-scripts .................................. SUCCESS [  5.371 s]
[INFO] phoenicis-library .................................. SUCCESS [  3.944 s]
[INFO] phoenicis-engines .................................. SUCCESS [  4.152 s]
[INFO] phoenicis-settings ................................. SUCCESS [  2.386 s]
[INFO] phoenicis-containers ............................... SUCCESS [  2.810 s]
[INFO] phoenicis-javafx ................................... FAILURE [  0.684 s]
[INFO] phoenicis-cli ...................................... SKIPPED
[INFO] phoenicis-dist ..................................... SKIPPED
[INFO] phoenicis-tests .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:56 min
[INFO] Finished at: 2019-10-27T18:11:56+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project phoenicis-javafx: Could not resolve dependencies for project org.phoenicis:phoenicis-javafx:jar:5.0-SNAPSHOT: The following artifacts could not be resolved: org.openjfx:javafx-controls:jar:${javafx.platform}:13, org.openjfx:javafx-graphics:jar:${javafx.platform}:13, org.openjfx:javafx-web:jar:${javafx.platform}:13, org.openjfx:javafx-media:jar:${javafx.platform}:13, org.openjfx:javafx-base:jar:${javafx.platform}:12.0.1: Failure to find org.openjfx:javafx-controls:jar:${javafx.platform}:13 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :phoenicis-javafx
### System information
Java version: 11.0.5, vendor: Oracle Corporation, runtime: /usr/local/openjdk11
Default locale: en_US, platform encoding: UTF-8
OS name: "freebsd", version: "12.0-release-p10", arch: "amd64", family: "unix"

I created FreeBSD.properties file like described in docs. here it is:

application.name                            =           Phoenicis PlayOnBSD

application.user.root                       =           ${user.home}/.Phoenicis
application.user.desktopShortcuts           =           ${user.home}/.local/share/applications
application.user.tmp                        =           ${application.user.root}/tmp
application.user.containers                 =           ${application.user.root}/containers/
application.user.shortcuts                  =           ${application.user.root}/shortcuts/
application.user.logs                       =           ${application.user.root}/logs
application.user.engines                    =           ${application.user.root}/engines/
application.user.resources                  =           ${application.user.root}/resources/
application.user.settings                   =           ${application.user.root}/config.properties
application.user.repository                 =           ${application.user.root}/repository/
application.user.cache                      =           ${application.user.root}/cache/

application.repository.list                 =           ${application.user.root}/repositories.json
application.repository.default.git.url      =           https://github.com/PhoenicisOrg/scripts
application.repository.default.git.branch   =           master
application.repository.default.classpath    =           /org/phoenicis/repository

application.root                            =           ${user.dir}
application.macosx.tools                    =
application.environment.path                =
application.environment.ld                  =
application.environment.dyld                =

webservice.wine.url                         =           https://phoenicis.playonlinux.com/index.php/wine?os=linux

#tools.linux-terminal                        =           x-terminal-emulator

**Comment by unwillexist** [comment]
There is no jfx for java 11 in FreeBSD there is only openjfx8-devel.

**Comment by madoar** [comment]
@unwillexist sadly there is nothing we can do in this case. I believe this is something the FreeBSD community or the JavaFX team needs to look into.
