### ISSUE TITLE
Package creation failure

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis#2115]
### Expected behavior
Correct package creation
### Actual behavior
I get the .deb file that is 73.6 kilobytes which can't be right. Here is the output of the bash file:
```
Warning: Version not specified. Reading from pom.xml
Using 5.0-SNAPSHOT
--2019-10-29 11:48:53--  http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip
Translacja download2.gluonhq.com (download2.gluonhq.com)... 178.128.135.159
Łączenie się z download2.gluonhq.com (download2.gluonhq.com)|178.128.135.159|:80... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 674385 (659K) [application/zip]
Zapis do: `jdk.packager-linux.zip'

jdk.packager-linux.zip                                                                                   100%[===============================================================================================================================================================================================================================================================================>] 658,58K   939KB/s    w 0,7s     

2019-10-29 11:48:54 (939 KB/s) - zapisano `jdk.packager-linux.zip' [674385/674385]

Archive:  jdk.packager-linux.zip
  inflating: jdk.packager.jar        
  inflating: jpackager               
WARNING: argument [linux-bundle-name] is not supported for current configuration.
Creating app bundle: /home/jonasz/Pobrane/phoenicis-master/phoenicis-dist/src/scripts/../../target/packages/PhoenicisPlayOnLinux
Module org.graalvm.truffle does not exist.
Module javafx.web does not exist.
Module javafx.base does not exist.
Module javafx.graphics does not exist.
Module javafx.controls does not exist.
Module javafx.media does not exist.
"Adding modules: [jdk.crypto.ec, java.base, javafx.base, javafx.web, javafx.media, javafx.graphics, javafx.controls, java.naming, java.sql, java.scripting, jdk.scripting.nashorn, jdk.internal.vm.ci, org.graalvm.truffle, java.management] to runtime image."
Exception: jdk.tools.jlink.plugin.PluginException: java.lang.module.FindException: Hash of java.xml (46fd019860d97f5811ffc5b51eb9de95a713c64000856d637727c495cdc7678c) differs to expected hash (12a209d077d43c90a5ce65d64027cc8468fe5de54e9b1b56138ce9f58aebef28) recorded in java.base
Error: Bundler "Linux Application Image" (linux.app) failed to produce a bundle.
dpkg-deb: budowanie pakietu "phoenicis-playonlinux" w "Phoenicis_5.0-SNAPSHOT.deb".
```
### Steps to reproduce
Download the latest master and compile. Dosen't matter if you are skiping the tests.
### System information
* software version (git revision) of phoenicis and scripts repositories
https://github.com/PhoenicisOrg/phoenicis/commit/00dad34402c462d898094da4d6523ba220fe5823
* used operating system
Ubuntu 19.10
* used Java version
openjdk 11.0.5-ea 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1, mixed mode, sharing)

**Comment by madoar** [comment]
> Module org.graalvm.truffle does not exist.
> Module javafx.web does not exist.
> Module javafx.base does not exist.
> Module javafx.graphics does not exist.
> Module javafx.controls does not exist.
> Module javafx.media does not exist.

This looks to me like some dependencies couldn't be downloaded (i.e. JavaFX and some parts of Graal). Can you retry with a clean `.m2/repository` folder?

**Comment by Zemogiter** [comment]
Removed that folder, tried again, still getting the same result.

**Comment by madoar** [comment]
Have you run `mvn clean package` before `mvn exec:java`?
Can you give us some more information about which commands you executed in which order?

**Comment by Zemogiter** [comment]
1. export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
2. mvn clean package
3. cd phoenicis-dist/src/scripts
3. bash phoenicis-create-package.sh
4. go to `phoenicis-javafx` and run `mvn exec:java` there
[terminal log](https://github.com/PhoenicisOrg/phoenicis/files/3894231/terminal.log)

**Comment by plata** [comment]
These commands do not make sense. If you want to execute Phoenicis via `mvn exec:java`, you must do `mvn install`. The package creation is completely irrelevant.

**Comment by Zemogiter** [comment]
@plata that's weird I was able to run POL5 with `mvn exec:java` without `mvn install`

**Comment by plata** [comment]
That should not be possible as far as I know. What could happen is that you did `mvn install` once and then always used the same version of the other modules.

**Comment by qparis** [comment]
This should be defintely fixed and cleaned up with Java 14. (Jpackage will be part of the JDK)

**Comment by plata** [comment]
Can we solve the issue for Java 11? If not, what do we do about this issue? Should we close it?

**Comment by qparis** [comment]
The package can be created from Java 11. Let's wait until Java 14 is released and everything will be cleaned up

**Comment by plata** [comment]
Ok, then I will close this issue. @Zemogiter feel free to open a new issue if you experience this problem again.
