### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by b3z** [PhoenicisOrg/phoenicis#2125]
### Expected behavior

PlayOnMac startup on run.

### Actual behavior

Closes instantly after execution.

```bash
$ ./playonmac
env: ./playonmac.real: Bad CPU type in executable
```

### Steps to reproduce

Run POM on Catalina 10.15 Beta (19A558d)

### System information
* POM 4.3.4
* Catalina 10.15 Beta (19A558d) Mac Book Air early 2015
* Java 8 Update 231 b11

**Comment by qparis** [comment]
PlayOnMac 4 is not compatible on Catalina
https://www.playonmac.com/en/topic-16558-macOS_Catalina_When_will_PlayOnMac_be_ready.html

**Comment by b3z** [comment]
Ah I see. You should write that somewhere to prevent more new issues.
Thanks.
