### ISSUE TITLE
how to completely remove Phoenicis PlayOnLinux?

### ISSUE THREAD

**Issue by Sobuj53** [PhoenicisOrg/phoenicis#2139]
### Expected behavior
If I remove POL 5 from Pacman it should completely remove the package along with it's dependency that were installed during installation.
### Actual behavior
It only removes POL 5 front end not the complete package.
### Steps to reproduce
Install POL 5 from Pacman, it'll install dependent software along with the GUI but if we want to remove that it will only remove the POL 5 front end not every package that were installed during installation (e.g. java, and other packages)
### System information
* software version (git revision) of phoenicis and scripts repositories,
phoenicis-playonlinux 5.0_alpha2-4
* used operating system
Manjaro KDE
* used Java version
JDK 11

PS. I installed POL 5 using Pacman, the installation process went just fine apps list were loaded in first run, then I encountered some trouble during installing a windows software in it. so I tried to quit by force closing. later I couldn't make it working. So I uninstalled and reinstalled POL 5 again but this time the apps tab is not loading, it's trying to load forever without any success. tried timeshift reverse but that didn't solve either. So I want to completely remove every trace of POL 5 from system and try installing again hoping to resolve the issue eventually.

**Comment by plata** [comment]
I'm assuming you're using the AUR? We're not providing packages for Arch/Manjaro so you should get in contact with the package maintainer regarding this issue.

Feel free to open a separate issue regarding your problems with POL 5 itself.

**Comment by plata** [comment]
@Sobuj53 you might want to have a look at https://github.com/PhoenicisOrg/scripts/issues/1056.

**Comment by Sobuj53** [comment]
Thanks I've managed to remove it by removing all dependency that were installed during package installation as well as removing following folders,

> ~/.m2
~/.openjfx
~/.Phoenicis
~/.org.phoenicis.javafx.JavaFXApplication
