### ISSUE TITLE
Sidebar toggle buttons not updated correctly

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#2151]
### Expected behavior
Category toggle buttons are updated if repository changes.

### Actual behavior
Category toggle buttons are missing.

### Steps to reproduce
Seems to be a timing issue. Therefore reproducing can be difficult.

With #2150, I do not see any category toggle buttons. It seems that it helps to change `FeaturePanelSkin` to:
```Java
container.leftProperty().bind(Bindings.when(getControl().initializedProperty())
                .then(createSidebar()).otherwise(createSidebar()));
```
This supports my theory that the issue happens because the GUI is created "too early".
However, this can only happen if the following code does not work as expected:
https://github.com/PhoenicisOrg/phoenicis/blob/b4b4d6aeba4733ea960414f7fe7d2b8c14b00743/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/skin/SidebarToggleGroupBaseSkin.java#L92

### System information
* current master
* Java 11, Java 13

**Comment by plata** [comment]
@madoar I don't know enough about how the skins etc. are supposed to work and we do not have any documentation, so you will have to take a look at this.

**Comment by madoar** [comment]
This can be quite difficult to localize.

It would be useful to know which `ObservableList`s are working correctly.
Can you add a listener to each of the following lists:

getControl().getElements() before line 82

https://github.com/PhoenicisOrg/phoenicis/blob/b4b4d6aeba4733ea960414f7fe7d2b8c14b00743/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/skin/SidebarToggleGroupBaseSkin.java#L85-L87

https://github.com/PhoenicisOrg/phoenicis/blob/b4b4d6aeba4733ea960414f7fe7d2b8c14b00743/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/common/skin/SidebarToggleGroupBaseSkin.java#L89

If some of these listeners don't trigger or trigger the wrong event we have a hint where to look.

**Comment by plata** [comment]
At load, the listener is called for `mappedToggleButtons` and for `adhocToggleButtons`. After the repository loading, only the listener for `mappedToggleButtons` is called.

**Comment by plata** [comment]
Just saw that javafx-collections does not build (the Travis badge is red). Could that be related?

**Comment by madoar** [comment]
Strange, as far as I remember the last time it was building correctly...

But you're right the failing reason seems really similar to what we you are experiencing. 
The issue is that I don't know how to fix it. It seems like a hiccup to me because it only occurred on Java 11. Also take a look at the commit history. The latest commit only changed the version number but it lead to a failing build while the one before ran just fine...

**Comment by plata** [comment]
I would suggest to merge https://github.com/PhoenicisOrg/javafx-collections/pull/37 and then see what happens (it seems to fix the build).

**Comment by plata** [comment]
I still have this behavior with javafx-collections 1.2.4.

**Comment by madoar** [comment]
Can you try reverting https://github.com/PhoenicisOrg/javafx-collections/pull/17 to see if this has any improvements for you? JitPack allows you to specify a commit for your dependencies

**Comment by plata** [comment]
Yes, it's working with https://github.com/PhoenicisOrg/javafx-collections/pull/42.

**Comment by madoar** [comment]
Working as in the issue does not occur?

**Comment by plata** [comment]
The issue is fixed. I.e. all buttons appear correctly (also their icons).
