### ISSUE TITLE
What does it mean, when it is said, that phoenicis supports CX?

### ISSUE THREAD

**Issue by Golddouble** [PhoenicisOrg/phoenicis#2221]
Hello,

On 
https://www.playonlinux.com/en/comments-1368.html
I read, that your program does support CX on linux.

I do not know what CX is? Is this just the short name for crossover? And are you trying to say, that your program does support exactly this program here: https://www.codeweavers.com/store ?

Thank you for clarification.

**Comment by plata** [comment]
It means that you can install and use the Codeweavers Wine versions in Phoenicis (go to "Engines" tab).

**Comment by Golddouble** [comment]
But I must buy Codewavers crossover first?
Thank you.

**Comment by plata** [comment]
No, you can use the Codeweavers Wine without buying Crossover.

**Comment by Golddouble** [comment]
Thank you. So is this something like free Crossover?

**Comment by plata** [comment]
Yes.
