### ISSUE TITLE
Terminal support on flatpak

### ISSUE THREAD

**Issue by Starcommander** [PhoenicisOrg/phoenicis#2223]
### Expected behavior
When i select a container of the container-tab and select the terminal, then a terminal window should appear.
### Actual behavior
Nothing is shown, because there is no terminal included into flatpak dist
### Steps to reproduce
Install Playonlinux5 flatpak package.
Select any container, and try to open a terminal
### System information
* software version (git revision): Latest master branch of github
* Debian bullseye (11)
* used Java version

I have already a tested solution for this issue, see attachment.
This will build a very thin console app from source.

**Comment by Starcommander** [comment]
Here the attachment, you have to rename the file, because of txt extension.
[org.phoenicis.playonlinux.yml.txt](https://github.com/PhoenicisOrg/phoenicis/files/4774305/org.phoenicis.playonlinux.yml.txt)

**Comment by plata** [comment]
I would appreciate a pull request.
