### ISSUE TITLE
Free or Commercial is a little bit confusing

### ISSUE THREAD

**Issue by Starcommander** [PhoenicisOrg/phoenicis#2235]
### Expected behavior
The filter-checkboxes for apps do have the same naming as in scripts config.
### Actual behavior
In the scripts there is the field 'free' -->  as free in beer (see [docs](https://phoenicisorg.github.io/scripts/Develop/script-json/)).
In the POL Window we have a checkbox "Commercial"
This is a little bit confusing, as it is not the same.

So I would suggest to rename "Commercial" to "Free", and adding a new field with license information.
Some suggestions, this can be:
- Commercial
- Opensource

Or with more details
- Commercial
- Opensource-GPL
- Opensource-Apache
- Opensource-Other

### Steps to reproduce
See checkboxes for filtering apps.
### System information
* software version (git revision): Upstream or 5.0-alpha-2
* used operating system: Debian 10
* used Java version: 11

**Comment by plata** [comment]
In case you would like to provide a PR regarding the renaming of commercial to free:
https://github.com/PhoenicisOrg/phoenicis/blob/47790a1427f93c5a8fd8f63112ce92e12e05522b/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/application/skin/ApplicationSidebarSkin.java#L68

As for the license: It will be additional effort to collect this information. So we should really evaluate if this information is interesting for our users.

**Comment by Starcommander** [comment]
Commercial is something like the opposite of free, but non-free is also not really clear.

What do you think about tooltip-text
- Testing --> Also show apps in testing state
- Patch required --> Also show apps, where CD patch is necessary
- Commercial --> Also show apps not free of costs
- All operation system --> Also show apps tested on different OS

This will also explain for example: Not only testing, but also testing.

Regarding license: The effort is not really huge, but I am also not sure, if it is that worth.

One more thing:
- When I select the checkboxes, all relevant apps are showing.
- But I can not evaluate for a specific (selected) app, whether it is - for example - free of costs.
- Would be a good idea to show this information on the right side bar?

**Comment by madoar** [comment]
> Regarding license: The effort is not really huge, but I am also not sure, if it is that worth.

This would require two subtasks:
- extend all existing scripts with the new `license` information
- add logic to process the new `license` information correctly in the client

I'm fine with adding this information, but I also don't know if it is worth it.

> Would be a good idea to show this information on the right side bar?

This sounds like a useful idea. To add this information to the details panel some new UI components need to be added to the following `initialise` method:

https://github.com/PhoenicisOrg/phoenicis/blob/9a81932e803cde65b05c702d756e2e3654030e6d/phoenicis-javafx/src/main/java/org/phoenicis/javafx/components/application/skin/ApplicationInformationPanelSkin.java#L119-L154

**Comment by Starcommander** [comment]
For me this is solved via PR 2249
