### ISSUE TITLE
Feature Request: Custom Wine/Proton Installation

### ISSUE THREAD

**Issue by trymeouteh** [PhoenicisOrg/phoenicis#2239]
Please allow us to create empty Wine and Proton containers and to install EXE files manually. I always like to install software manually and not using a install script. I like PlayOnLinux since your able to install EXE files manually and create Wine containers.

**Comment by plata** [comment]
The Custom Installer in the apps tab should be what you're looking for.

**Comment by trymeouteh** [comment]
I do not see this option under the apps tab. I am using 5.0-alpha Flatpak

**Comment by plata** [comment]
It's not an option, just another "app".

**Comment by trymeouteh** [comment]
Found it, thank you
