### ISSUE TITLE
MD5 hash mismatch attempting to install vcredist_x86.exe

### ISSUE THREAD

**Issue by greenstick** [PhoenicisOrg/phoenicis#2276]
### Expected behavior
MD5 hashes should match and installation should proceed.

### Actual behavior
Using the PlayOnMac Wizard to install Skyrim via Steam, I receive the following error after installing and logging into Steam:

```
https://web.archive.org/web/20190913165356/http://download.microsoft.com/

Error ! Files mismatch

Local: 17b1813916c3410c6acef0d04b0b7998
Server: 5689d43c3b201dd3810fa3bba4a6476a

Do you want to retry?

```
In subsequent retries, the Local MD5 sometimes changes. 

### Steps to reproduce
Assuming correct versions as outline in this issue:
1. Open PlayOnMac.
2. Install Skyrim.
3. Download Windows fonts as requested by PlayOnMac installation Wizard.
4. Select Steam installation.
5. Download Steam, open it upon completed download, and login with Steam account username and password.
6. Wizard will attempt to download vcredist_x86.exe.
7. Once download is complete, MD5 hash comparison will fail.

### System information
* software version (git revision) of phoenicis and scripts repositories
**PlayOnMac 4.4.1**
Unsure of which version of phoenicis is installed, but it calls to the following link:
https://phoenicis.playonlinux.com/index.php/wine?os=darwin (retrieved on 9/25/20 at 2:45pm)

* used operating system and device
MacOS Catalina 10.15.6
15-inch 2018 MacBook Pro
2.9GHz 6-Core Intel Core i9
32 GB 2400 MHz DDR4
Radeon Pro Vega 20 4GB (PCI)
Intel UHD Graphics 630 1536 MB (integrated)

* used Java version
**Installed version:**
Java Version 8 Update 251 (build 1.8.0_251-b08)
**Later updated to version (issue persists):**
Java Version 8 Update 261 (build 1.8.0_261-b12)

**Comment by plata** [comment]
You're reporting an issue for PlayOnMac 4. However, this repository is for Phoenicis PlayOnLinux/PlayOnMac 5.

Please move the issue to https://github.com/PlayOnLinux/POL-POM-4.
