### ISSUE TITLE
I have to start i twice so it launches

### ISSUE THREAD

**Issue by Toadfield** [PhoenicisOrg/phoenicis#2315]
### Expected behavior
That I just start it
### Actual behavior
That I have to start it twice and the fist time it just doesn't launch
### Steps to reproduce
Start it
### System information
JDK11
Manjaro Kde
Kernel 5.10
Phoenicis 5.0alpha2-6

**Comment by plata** [comment]
Do you build yourself or are you using flatpak/AUR?

**Comment by Toadfield** [comment]
I installed it via aur.

**Comment by plata** [comment]
Would be interesting if the same happens if you build yourself.

**Comment by Toadfield** [comment]
Tried it,I builded the newest version and I have the same problem.

**Comment by plata** [comment]
Is it every time or just the firsts time you start it at all?

**Comment by Toadfield** [comment]
It happens sometimes and sometimes not.

**Comment by plata** [comment]
Anything in the log?

**Comment by Toadfield** [comment]
How can I get the log?

**Comment by plata** [comment]
If you start from terminal, you should see it.

**Comment by Toadfield** [comment]
It stopped working,so no need for that,I will post the output if that happens again.
