### ISSUE TITLE
Select and install multiple apps/wine versions at once

### ISSUE THREAD

**Issue by Toadfield** [PhoenicisOrg/phoenicis#2316]
So that you can click on multiple games while holding strg and install them at once.

**Comment by plata** [comment]
How should the installation wizard work in this case? Or should it open multiple wizards?

**Comment by Toadfield** [comment]
For wine versions it could be easily implemented,cause they don't have installation wizards at all.
For the windows programs,that the wizards will be opened in the order you slected them,and if you finished one,the next one opens.

**Comment by Toadfield** [comment]
Or forget the thing with windows apps.
The thing I would like them most would be to be able to install multiple wine versions at once.

**Comment by plata** [comment]
For better understanding: what's the actual use case of this?

**Comment by Toadfield** [comment]
I want to install all wine versions fastly,cause I select different wine versions for different games,cause many only work with a specific one.

**Comment by plata** [comment]
Understood. However: the installer will download the required version anyways if not installed already. So why would you like to download the versions manually?

**Comment by Toadfield** [comment]
What if I want to install a program manually?
Do I not need to install the wine version manually if I wanna use it for that?

**Comment by plata** [comment]
No. If you use the custom installer, you can select the Wine version and it will be downloaded during the installer.

**Comment by Toadfield** [comment]
What if I add an already installed .exe?
Will I also be asked if I wanna install another wine version?

**Comment by plata** [comment]
Yes, because the custom installer creates a new prefix.

**Comment by Toadfield** [comment]
ok
