### ISSUE TITLE
[Feature Request] Being able to use your system theme

### ISSUE THREAD

**Issue by Toadfield** [PhoenicisOrg/phoenicis#2329]
I wanna use my normal system theme.

**Comment by plata** [comment]
JavaFX cannot just use the KDE/Gnome/XFCE/... system theme.

**Comment by Toadfield** [comment]
Then,what about a switch to qt?

**Comment by plata** [comment]
Then you will have the same issue when you're on Gnome. Not even talking about Mac. However: the Phoenicis framework is not restricted somehow, so anybody can feel free to implement whatever GUI they like.
