### ISSUE TITLE
[Feature Request] If youdelete the files a program in a file manager,then that program gets removed from Phoenicis automatically

### ISSUE THREAD

**Issue by Toadfield** [PhoenicisOrg/phoenicis#2331]
That would be cool.
And also the desktop- and application menu shortcuts will be deleted.

**Comment by plata** [comment]
This will happen if you delete the shortcut. Otherwise it's impossible. Phoenicis is not notified about what happens in the file manager.

**Comment by Toadfield** [comment]
If you add that Phoenicis scans if the files it uses exist and aren't deleted,then this feature could work.

**Comment by plata** [comment]
Like I said: it does so for the shortcuts. And I think for containers as well. If you delete a single file inside a container, well that's your problem then. For example: you could delete some file (not the executable) which is required by the app. Phoenicis cannot know this.

**Comment by Toadfield** [comment]
That's what I mean,I want that that only happens if the executable is deleted.
Or do I get you wrong here?

**Comment by plata** [comment]
Still I don't think it's good to delete it silently. There could be a dialog "Executable has been deleted, do you want to remove xyz?".

**Comment by madoar** [comment]
I am also against an automatic removal. What would be possible is to annotate the shortcut somehow (maybe with a red border) to mark it as problematic
