### ISSUE TITLE
[Feature Request] That all steam games get added automatically (if you set that in the settings)

### ISSUE THREAD

**Issue by Toadfield** [PhoenicisOrg/phoenicis#2355]
What I mean is,if you install a steam game,then the executable of that game gets added automatically.
So I don't mean the shortcut that launches it in steam,but the executable itself.
That would be cool,cause you could choose other wine versions than proton.
The thing that I want to know is,if would still show the steam dialog if you start a game by that or not?
Cause if not,updates for dxvk for that prefix in steam and things like that won't be installed automatically afaik.

**Comment by plata** [comment]
> That would be cool,cause you could choose other wine versions than proton.

Phoenicis always uses the Phoenicis Wine version and not the Proton version of your native Steam.

**Comment by Toadfield** [comment]
I thought that it uses the same proton version.
What's the difference and why is it not the same?
And can I add the normal Proton and Proton-GE to Phoenicis?

**Comment by plata** [comment]
Phoenicis uses it's own Wine versions. We have also Proton builds (see engines tab).

**Comment by Toadfield** [comment]
Then what's the problem here?

**Comment by plata** [comment]
I don't see how this relates to the initial question.

**Comment by Toadfield** [comment]
Cause you said
> Phoenicis always uses the Phoenicis Wine version and not the Proton version of your native Steam.

Then I was confused cause I thought that phoenicis supports proton.
Then you answered
> Phoenicis uses it's own Wine versions. We have also Proton builds (see engines tab).

So does it use the normal steam versions or it's own?
And this relates to the initial question,cause if phoenicis uses it's own proton version,then this feature has no point.

**Comment by plata** [comment]
It uses it's own Wine/Proton builds. If you install Steam in Phoenicis, it's the Windows version (as opposed to the native Linux version on you operating system).

**Comment by Toadfield** [comment]
I don't mean that it should install wine steam,I mean that it should use the games from native steam,but I think this feature would be over the top,so I close it.
