### ISSUE TITLE
[Feature Request] Being able to enable/disable Esync or Fsync for each program

### ISSUE THREAD

**Issue by Toadfield** [PhoenicisOrg/phoenicis#2364]
I would like if esync and fsync gets enabled automatically but that you can disable it if you want.
I forget the env var to disable that every time.

**Comment by plata** [comment]
That's a decision every script developer has to take. Nothing stops you from enabling Esync or Fsync for a certain app. By default, Phoenicis will behave like plain Wine (by intention).

**Comment by Toadfield** [comment]
But it would be cool to turn on that every program uses esync and fsync by default in the settings.
Cause enabling it separately for each program would take too long.

**Comment by plata** [comment]
> Cause enabling it separately for each program would take too long.

That's not true. It should be decided in the install script. Therefore, the exact amount of time required by the user is 0s.

**Comment by Toadfield** [comment]
I can also just put the env vars to enable esync and fsync in .profile
