### ISSUE TITLE
Option to disable "Are you sure you want to clse all PlayOnLinux windows?"

### ISSUE THREAD

**Issue by Razzeee** [PhoenicisOrg/phoenicis#2391]
### Expected behavior
I would like this to be configurable, as I can't see what the point is. It also feels foreign in a gnome desktop.

### Actual behavior
Popup appears on each close, even if I try to close it via the "X" in the overview.
![image](https://user-images.githubusercontent.com/5943908/116574022-9edec280-a90d-11eb-80be-ac6150dbd040.png)

### Steps to reproduce
Close the app

**Comment by plata** [comment]
https://github.com/PhoenicisOrg/phoenicis/commit/cd3e3fb065ec1a38624209ab68c323e94d8b0ffe

**Comment by Razzeee** [comment]
Thank you
