### ISSUE TITLE
GOG Galaxy : wrong checksum in verb Engines/Wine/Verbs/xact/

### ISSUE THREAD

**Issue by mjoriatti** [PhoenicisOrg/phoenicis#2424]
### Expected behavior
The verb should install GOG Galaxy

### Actual behavior
The install process stops with a checksum mismatch on "directx_Jun2010_redist.exe" within xact verb.

### Steps to reproduce
Try to install GOG Galaxy...

### Steps to install without error (dirty workaround)

copy/paste the expected checksum in the Engines/Wine/Verbs/xact/ verb :

80            //.checksum("f8f1217f666bf2f6863631a7d5e5fb3a8d1542df")
81	    .checksum("7e5d2e5e1a13fbc47f990cc55cbdb428cd12f759")

directx_Jun2010_redist.exe then installs correctly.
GOG Galaxy then installs correctly and can be launched.

### System information
* software version : Flatpak 5.0-alpha-3
* used operating system : Debian Bullseye
* used Java version : openjdk version "11.0.11"

**Comment by plata** [comment]
Could you provide a pull request which fixes the checksum?

**Comment by mjoriatti** [comment]
Should be done, I hope I did it correctly.
