### ISSUE TITLE
Please delete this issue

### ISSUE THREAD

**Issue by ovari** [PhoenicisOrg/phoenicis#2455]
Please delete this issue.

**Comment by francescomasala** [comment]
Hi, sorry but it doesn't seem appropriate the way you nicely "tagged" us within your issue, may I know why you did that? It looks like spam to me

**Comment by francescomasala** [comment]
Secondly we don't want to compare our work to anyone, we made a useful software for the community and for us, that's what's important

**Comment by ovari** [comment]
Thank you for your comment.

I am sorry that you feel this comment was spam.

[PlayOnLinux 4 (POL4)](https://www.playonlinux.com/) is currently in use and it is understood that it will be depreciated for Phoenicis. POL4 is not based on Java so is not resource intensive.

It was thought that the reasons for using each useful software would come from the developers as there must be reason to create new software.

Having a list of the pros and cons of each useful software solution can assist us and the community choose the best software choice for each use-case when POL4 is no longer supported.

Please advise if you prefer this issue be deleted.

Thank you once again

**Comment by mirkobrombin** [comment]
> Thank you for your comment.
> 
> I am sorry that you feel this comment was spam.
> 
> [PlayOnLinux 4 (POL4)](https://www.playonlinux.com/) is currently in use and it is understood that it will be depreciated for Phoenicis. POL4 is not based on Java so is not resource intensive.
> 
> It was thought that the reasons for using each useful software would come from the developers as there must be reason to create new software.
> 
> Having a list of the pros and cons of each useful software solution can assist us and the community choose the best software choice for each use-case when POL4 is no longer supported.
> 
> Please advise if you prefer this issue be deleted.
> 
> Thank you once again

I understand your purpose and I share it. You could just take the links off the title, which looks a bit ugly. Maybe these threads are more useful in their respective forums (we now have a forum too).

**Comment by ovari** [comment]
Please delete this issue.
