### ISSUE TITLE
Missing tabs/sections in flatpak version of the app !!!

### ISSUE THREAD

**Issue by aiamuzz** [PhoenicisOrg/phoenicis#2457]
### Expected behavior
work normally in a flatpak'd version of the app

### Actual behavior
missing tabs/sections in the flatpak'd version of the app

### Sreenshots.
deb file installation for the website
![image](https://user-images.githubusercontent.com/3283676/141277372-565c60f2-4bd6-427d-9781-7e8da49c2c3b.png)

installed from flathub
![image](https://user-images.githubusercontent.com/3283676/141277457-6c793a20-c40a-400d-a943-375cb48dd710.png)

### System information
* [5.0-alpha-3](https://flathub.org/apps/details/org.phoenicis.playonlinux)
* Linux Deepin
* Java version
```
$ java --version
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

```

**Comment by plata** [comment]
Looks like you might be using different advanced mode settings.

**Comment by kupiqu** [comment]
@aiamuzz, I guess you did it already but if confused, go to settings and enable `Advance mode (requires restart)` then restart.

This should do it, if so, you can close the issue.

**Comment by aiamuzz** [comment]
@kupiqu ... thanks, that was simple ...
