### ISSUE TITLE
Almost non-readable with GNOME "HighContrastInverse" theme

### ISSUE THREAD

**Issue by peter-kehl** [PhoenicisOrg/phoenicis#2478]
### Expected behavior
Readable checkbox [] descriptions etc.

### Actual behavior
![image](https://user-images.githubusercontent.com/4270240/147737873-ff374e6d-add6-49cc-8b04-69077dae3b1c.png)

### Steps to reproduce & System information
Current Manjaro x64 Linux 5.16.0-1-MANJARO. GNOME 41.2 (current for this Manjaro).

In Tweaks application: Appearance > Themes > Applications > HighContrastInverse:
![image](https://user-images.githubusercontent.com/4270240/147738062-efb98d3a-fff5-4eca-93bf-a73963482673.png)

This theme works for me for over a year. PlayOnLinux 4.3.4-4 (as packaged for Arch/Manjaro Linux) is the first application where I ever saw this problem.

* used Java version
I have a few, but the default one is OpenJDK Environment (build 1.8.0_292-b10).

**Comment by plata** [comment]
This repository is for PlayOnLinux 5 (Phoenicis). For PlayOnLinux 4 please ask in the forums: https://www.playonlinux.com/en/forums.html.
