### ISSUE TITLE
¿is possible to install .INF driver?

### ISSUE THREAD

**Issue by juanpc2018** [PhoenicisOrg/phoenicis#2532]
PlayOnMac Version 4.3.3 
OSX HighSierra 10.13.6

Problem:
there is an old SCSI scanner...
Works OK in Windows.

has a Mac installer, but only works in OSX SnowLeopard 10.6.8 
because the software was designed for G4 PowerPC CPU,
OSX 10.6.8 has Rosetta v1 PPC Emulator.
Works OK in OSX 10.6.8
but... No Mac from 2012 or newer can run OSX SnowLeopard 10.6.8,
the hackintosh people are interested in the opposite, running Newer OSX, Not older.

Windows installer Works in PlayOnMac, 
but requires .INF driver to detect the SCSI scanner...

¿is possible to install .INF driver?

SCSI scanner can be used usign a FireWire to SCSI converter, or with a PCIe SCSI card, both work Ok in Windows8.1 or OSX SnowLeopard 10.6.8.
Using VirtualMachines is Not possible, because None so far has PCIe / FireWire Passthough.

ReactOS in theory is the same as Wine / PlayOnMac / PlayOnLinux.
can load .INF drivers..
but havent tested ReactOS Native, that would be my next test.

i cannot install more than OSX Mojave in MacPro 5,1 2010 Officially
OSX Catalina with an Unofficial Patch.
but is pointless because OSX removed 32-Bit driver support in OSX Mojave.
the highest OSX that can install & detect PCIe SCSI is OSX HighSierra 10.13.6
havent tested IF OSX Mojave or Catalina can detect & install the SCSI PCIe card or the FireWire to SCSI converter.
but most likely it will Fail, because its 32-Bit software, OSX Mojave is 64-Bit Only.
have tested other HW, does Not install, or installs but does Not Run, or Run but does Not detect.

without configuration software would be more difficult, 
SCSI scanners require Async mode and other configurations to work in the SCSI controller.

SCSI scanner Need:
SCSI controller PCIe or FireWire,
SCSI controller driver Win or Mac, havent tested Linux. probably has.
Windows scanner driver .INF or OSX Rosetta v1 PPC Emualtor. 
SCSI config software,
propietary scanner software WIn or Mac.

There are 3rd party scanner softwares like VUEScan and SilverFast, but those do Not support the Scanner i have, if they could, they have done already, also the original software is very good for color correction editing.

OSX HighSierra has all, exept scanner software,
because lacks Rosetta v1 PPC Emulator.

Wine / PlayOnMac has scanner software,
but does Not have .INF driver

in OSX, scanner driver is built-in the scanner software.
in Windows needs a .INF installer.

Log
[05/04/22 07:55:51] - Running wine-5.9 /Users/OSX/Downloads/0-DT/Hasselblad.com/Win/fc403_eng/SETUP.EXE (Working directory : /)
0070:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0058:fixme:virtual:NtQueryVirtualMemory (0xffffffff,0x6ad80000,info_class=1000,0x6ad85008,8,0x0) Unknown information class
0058:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\nsiproxy": c0000003
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 87
0058:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\NDIS": 00000001
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 731
00cc:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
[05/04/22 07:57:14] - Running wine-5.9 winepath -u C:\\users\\OSX\\Desktop (Working directory : /Users/OSX/Library/PlayOnMac/wineprefix/x32/drive_c)
/Users/OSX/Library/PlayOnMac//wineprefix/x32/dosdevices/c:/users/OSX/Desktop
[05/04/22 08:00:46] - Running wine-5.9 start.exe /wait /unix  (Working directory : /Users/OSX/Library/PlayOnMac/wineprefix/x32/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Hasselblad)

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
[05/04/22 08:02:32] - Running wine-5.9 FlexColor.exe (Working directory : /Users/OSX/Library/PlayOnMac/wineprefix/x32/drive_c/Program Files/Hasselblad/FlexColor English v4.0.3)
0164:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031FA74 1 C) semi-stub
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031FA74 1 C) semi-stub
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031FA74 1 C) semi-stub
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031FA74 1 C) semi-stub
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031FA74 1 C) semi-stub
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031F870 1 C) semi-stub
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031D89C 1 C) semi-stub
0164:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031D694 1 C) semi-stub
0164:fixme:sti:stillimagew_GetDeviceList (7F62F3F0, 0, 0x0, 0031EE28, 0031EE1C): stub
0164:fixme:win:AnimateWindow partial stub

**Comment by plata** [comment]
Please ask in the wiki for PlayOnMac 4.x.
