### ISSUE TITLE
Latest release won't build

### ISSUE THREAD

**Issue by WarpOverload** [PhoenicisOrg/phoenicis#2587]
### Expected behavior
To compile correctly so I can go to bed, and wake up playing SimCity 4 for the entire day.
### Actual behavior
[INFO] phoenicis .......................................... FAILURE [  0.197 s]
[INFO] phoenicis-configuration ............................ SKIPPED
[INFO] phoenicis-entities ................................. SKIPPED
[INFO] phoenicis-multithreading ........................... SKIPPED
[INFO] phoenicis-win32 .................................... SKIPPED
[INFO] phoenicis-tools .................................... SKIPPED
[INFO] phoenicis-repository ............................... SKIPPED
[INFO] phoenicis-scripts .................................. SKIPPED
[INFO] phoenicis-library .................................. SKIPPED
[INFO] phoenicis-engines .................................. SKIPPED
[INFO] phoenicis-settings ................................. SKIPPED
[INFO] phoenicis-containers ............................... SKIPPED
[INFO] phoenicis-javafx ................................... SKIPPED
[INFO] phoenicis-cli ...................................... SKIPPED
[INFO] phoenicis-dist ..................................... SKIPPED
[INFO] phoenicis-tests .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
Certified compiling classic! 
### Steps to reproduce
Get the latest build and build it with mvn clean package.
### System information
I don't know what version of phoenics this is, I'm too tired. Ask me in the morning.
git version 2.37.3
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
gradle 1.8
Manjaro Linux 21.3
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (build 25.345-b01, mixed mode)

**Comment by plata** [comment]
Please post the place of the real error or complete log. This excerpt of the log is not sufficient to say anything.

**Comment by dschuessler** [comment]
Doesn't build on macOS 12.6 either.

```
openjdk 19 2022-09-20
OpenJDK Runtime Environment Homebrew (build 19)
OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)
```

https://gist.github.com/dschuessler/1415775eb8b2f26c36650983d5b07d56

**Comment by plata** [comment]
You must use Java 11.

**Comment by dschuessler** [comment]
Indeed, that worked. Thank you!
