### ISSUE TITLE
Build fails on Slackware 15.0 on javafx-step

### ISSUE THREAD

**Issue by tapwag** [PhoenicisOrg/phoenicis#2643]
### Expected behavior
build should terminate okay

### Actual behavior
[phoenicis-output.txt](https://github.com/PhoenicisOrg/phoenicis/files/10832286/phoenicis-output.txt)

### Steps to reproduce
mvn clean package

### System information
* software version (git revision) of phoenicis and scripts repositories
 latest git
* used operating system
 Slackware Linux 15.0
* used Java version
 jdk-11.0.1

mvn --version
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /usr/share/maven
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-11.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.19", arch: "amd64", family: "unix"

**Comment by Clockwork6400** [comment]
I am having the same problem on FreeBSD. My build doesn't complete due to java-fx.

**Comment by plata** [comment]
The [lesscss-maven-plugin](https://github.com/gabrysbiz/lesscss-maven-plugin), which causes the issue, is dead. We need an alternative. Maybe https://javalite.io/lessc.
