### ISSUE TITLE
Work with SELinux and/OR AppArmor to restrict access, 

### ISSUE THREAD

**Issue by Mannshoch** [PhoenicisOrg/phoenicis#313]
Having Wine on Linux mean also you have Windows Programs on Linux. This tools contains their own Problems and security holes. In this Modern times most Programs you work with use Internet on a way and could be attacked on this way.

Implement the using of SELinux and/OR AppArmor to prevent a to easy corruption of the Host Linux system.

More important then the using on a normal POL prefix should the normal default wine Installation been secured. A normal Linux system with a Filetype Link to Wine will also start exe files a user double-click.

**Comment by Mannshoch** [comment]
What you think.
How good would "Docker" fit on the Wineprefix Idea?

**Comment by Veske** [comment]
Docker is not a solution. You cannot expect users to willingly want to install docker on their systems. Also a lot of distributions don't have their kernel compiled with SELinux.

**Comment by samrocketman** [comment]
> Also a lot of distributions don't have their kernel compiled with SELinux.

Provide the support where it's supported.  The RPM package of the distribution should configure SELinux if it's installed.  The same could be said of AppArmor (configure if installed).

Most _popular_ distributions come with some form of security containment layer.  It would make sense to use it if it's available.

**Comment by Mannshoch** [comment]
Maybe firejail could be a solution for that. 
https://firejail.wordpress.com/
https://github.com/netblue30/firejail

**Comment by plata** [comment]
Would flatpak be sufficient to fulfill your requirements?

**Comment by Mannshoch** [comment]
I'm a Ubuntu user so [snap](https://github.com/PhoenicisOrg/phoenicis/issues/752) would fit better for me.
But because its a matter of security I would say Yes! 👍

**Comment by plata** [comment]
Good. Working on it in #1406.

**Comment by plata** [comment]
Flatpak is up and running.
