### ISSUE TITLE
Setup new website (phoenicis.org)

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis#557]
The website will be <http://www.phoenicis.org/>. 

Think about the content which content shall be available there.
For example:
- news blog
- user forum ([Discourse](https://github.com/discourse/discourse)?)
- supported apps (like for [PoL4](https://www.playonlinux.com/en/supported_apps.html))
- link to the relevant GitHub repositories ([Source](https://github.com/PlayOnLinux/POL-POM-5) and [Scripts](https://github.com/PlayOnLinux/Scripts))

Also think about what shall NOT be done on that website.
For example:
- file a bug (GitHub issue)
- upload a new script (GitHub PR) - or is this too difficult for the average user/do we need an easier interface?
- custom user management (use GitHub, Steam...)

Always keep in mind that the website shall convey the idea that the Phoenicis suite is the successor to PoL/PoM but also create a new strong brand unifying those.

**Comment by qparis** [comment]
Upload a script should be possible, but through GitHub.

Also I think we shall create a web service (WebServiceApplicationsSource will need to be implemented) directly bound to the git repository

**Comment by plata** [comment]
What's the difference of that WebServiceApplicationSource and the existing one which uses `git+https://github.com/PlayOnLinux/Scripts`?

**Comment by plata** [comment]
It would be good to have a hook which updates the supported apps as soon as anything is merged into Scripts master.

**Comment by qparis** [comment]
Not depending on git + having a phoenicis.org address (and having the possibility to create CDNs), usage statistics, ...

**Comment by plata** [comment]
Sorry, could you explain in more detail what you have in mind? I'm currently having difficulties understanding your idea.

**Comment by qparis** [comment]
I don't really like the idea of having a production software depending on git.
Also, I'd rather have phoenicis.org in the official phoenicis repository

**Comment by Veske** [comment]
So how will people understand that Play on Linux is something I should look under http://www.phoenicis.org/? The name says literally nothing to new people, no?

**Comment by plata** [comment]
@Veske PlayOnLinux will be named Phoenicis PlayOnLinux (similarly, PlayOnMac will be Phoenicis PlayOnMac). We want to have one common website because both are in fact the same software. Of course, playonlinux.com and playonmac.com do still exist and will link you to phoenicis.org. So no one will be lost until people are used to the Phoenicis brand.

**Comment by plata** [comment]
@qparis I would like to have an explanation of the name Phoenicis on the website. Is it from a star in the Phoenix constellation?

**Comment by madoar** [comment]
Is there already a plan about how to create the website? Do you want to use a CMS or do you want to write a custom website? If you want to write a custom website with which technology?

**Comment by qparis** [comment]
For a start, we are going to create a very simple website. I don't think we are going to need a CMS for that :-)

**Comment by qparis** [comment]
I will handle this ticket

**Comment by plata** [comment]
@qparis that's great!
@madoar for the beginning, it's important to have a website which presents the Phoenicis brand, showcases the application and links to GitHub. Everything else (like e.g. forum) can be done later on.

**Comment by qparis** [comment]
Do we want to keep the same logo?

**Comment by plata** [comment]
@qparis I would like a new one. Correct me if I'm wrong but the current logo seems to refer to the Windows XP flag. This is somewhat outdated nowadays. Moreover, Phoenicis is much more than a GUI for Windows apps in a non-Windows environment (as we can plug any engine). Therefore I believe that we should find a logo which is more appropriate.

As I stated above, the website should contain a description of the name "Phoenicis". We could use a logo resembling this. Maybe a star constellation or a stylized bird (depending where the name is coming from).

**Comment by Veske** [comment]
What does Phoenicis mean?

**Comment by joskfg** [comment]
What do you think about to open a slack to have direct communication and allow people to help each other? I followed some discussions in Issues and I think it is pretty easier to do it in a chat. After that it can represent a Pull Requests to the scripts repository with the updates.

Another thing is it could be pretty good to know in which SO/Hardware the script has been tested to know if it works or not. I know that in winehq you have similar information but it is not about the specific POL script.

**Comment by qparis** [comment]
Yeah good idea. I will do it

**Comment by qparis** [comment]
Just a small comment to inform you that I'm working on this task. 
I have two goals: 
- Make the website compatible compatible with POL-POM-5 API, so that we can directly read existing directories 
- Make the website compatible to legacy POL 4 website (news, forums, ...). Thanks to this work, we will be able to keep all the content we already have. 
- Everything should be accessible via REST APIs 

Few screenshots (the design remains to be done): 
<img width="1316" alt="capture d ecran 2017-06-05 a 23 31 51" src="https://cloud.githubusercontent.com/assets/373645/26804181/5d0ec612-4a47-11e7-843f-1a24a175b224.png">
<img width="1316" alt="capture d ecran 2017-06-05 a 23 33 13" src="https://cloud.githubusercontent.com/assets/373645/26804180/5d082910-4a47-11e7-8d0a-d16a7383c002.png">

**Comment by plata** [comment]
Like it so far. Did you think about the logo already? Will this work well on mobile?

**Comment by madoar** [comment]
The website looks quite nice :) :+1:

**Comment by plata** [comment]
some input from @nodiscc

> It would be nice if the PoL team could compile a list of resources about PoL scripting (examples, tutorials, helpers...)

**Comment by plata** [comment]
@qparis what's the status here? I think for the alpha it's sufficient if the website exists and has a super simple main page.

**Comment by baradhili** [comment]
Is this dead? I visit http://www.phoenicis.org/ and get a sales page...
I'd really like somewhere to be able to work out how to port a bash script across to the new model...

**Comment by qparis** [comment]
This is not a sale page, no worries.

**Comment by plata** [comment]
@baradhili we have a description in the [wiki](https://github.com/PhoenicisOrg/Scripts/wiki/script.js). If you have any questions feel free to open an issue about it.

**Comment by plata** [comment]
@qparis what's the status? The Crowdin Open Source request form was asking me for a website, so it might be that they will ask me about it. Showing the supported apps etc. doesn't seem to be so easy. Can we maybe launch the website without that and enhance it later on?

**Comment by qparis** [comment]
Independently of the status of phoenicis website, I think you should give them PlayOnLinux website ; I think the check process will be quicker. We will be able to change that later on.

Concerning the website, I'll try to finish this tomorrow

**Comment by qparis** [comment]
So as agreed:  
* The first commit is uploaded (website repository)
* The news are the same than those on www.playonlinux.com for the moment (reuse). I can give you access if you need 
* The domain name is registered. As soon as you have reviewed the website content / the code, I can bring the website up 
* Screenshot: 
<img width="1283" alt="capture d ecran 2018-03-04 a 17 23 28" src="https://user-images.githubusercontent.com/373645/36947775-d92f48c0-1fd0-11e8-9ed5-f78c1942758e.png">

**Comment by plata** [comment]
I don't think it makes too much sense to read the code. I'll just have a quick look and open issues for the things I notice. Really like the clean look of it.

BTW: seems like playonlinux.com is down.

**Comment by plata** [comment]
I don't think we need access to the news right now. If we want to have the news translated in future, we must think about a solution.

**Comment by madoar** [comment]
The screenshot looks very nice!

About the `Github` button:
It looks like the website has some problems with the font of the icon to the left of `Github`.

I've taken a short look at your website code.
I agree with @plata, it looks very clean.
Can you maybe add a short README to the website repository giving a short overview about the technologies you've used and about the folder structure (what's where).
I believe this would help others who want to to help improve the website :)

**Comment by qparis** [comment]
Agreed :)

**Comment by plata** [comment]
@qparis it would be great if you could handle the open issues for the website so it can go online and we can release alpha. However, if you don't have the time, I suggest to fix only PhoenicisOrg/Website#14 and PhoenicisOrg/Website/#5 and bring it online.

**Comment by madoar** [comment]
@plata I think we can close this Issue now, what do you think?

**Comment by plata** [comment]
Yes.
