### ISSUE TITLE
typo in wine version 15.27-NeedForSpeed

### ISSUE THREAD

**Issue by pyroxar** [PhoenicisOrg/phoenicis#935]
One of wine is mislabeled.
This bug is present only in upstream wine version.
![zrzut ekranu z 2017-06-28 12-00-43](https://user-images.githubusercontent.com/23406555/27632336-b11bec92-5bfb-11e7-8d5e-eccff2ea3e0c.png)

**Comment by madoar** [comment]
@qparis I think you're the one to fix this :)

**Comment by qparis** [comment]
Fixed
