### ISSUE TITLE
Structure/select issues required for beta

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#995]
Currently we have "only" two issues left until all current alpha issues are done. 
I believe we should take this time to decide what should be done next, in which order.
I must confess that I currently have no clue what problem we should tackle next.

As a note/idea:
Maybe we should search for a tool that helps us to structure our issues a little bit better. Github itself only provides us with a method to define issues but not a way to link them together. I.e. things like blocking issues and so on can only be defined by text which has no real meaning. Maybe we should search for a github integration tool that provides us with a better platform for this?

**Comment by plata** [comment]
Any proposal for a tool?

**Comment by plata** [comment]
I think we have quite a lot of issues which are open for some time. We should take some time to either close them or decide that it's not required. They make the list of open issues somewhat unreadable which results in a lack of structure as described in this issue.

In particular, I'm talking about the following issues:
- #935 
- #931 
- #926 
- #923 
- #919 
- #830 
- #820 
- #819 
- #818 
- #814 
- #794 
- #758 
- #740 
- #478 
- #448

**Comment by madoar** [comment]
The problem with a lot of the issues you've named is, that each of them is the tip of an iceberg. These issues will often require the addition of other issues to solve the topic completely and in a good way.

#830, for example, would introduce CDI to the core controller classes. If this works we would need to think about the current architecture of the javafx client to see if we could change it in some places to make the code better readable, this would require us to open a large new construction site. 

With regards to that I would like to prioritize these issues to tackle them in a given order.
Some of these issues are only code beatification and therefore not really required.

**Comment by plata** [comment]
Agree for #830. But especially the issues which you call code beautification should be handled in my opinion to get them out of the way because hey just blow up the issues list. If they are not important enough to handle them, we should simple delete them (because in this case they will never be solved).

**Comment by madoar** [comment]
There are more of these large issues:

- #931 
- #919 (#740 belongs to this)
- #819 
- #820

Everything else should be standalone issues, that shouldn't really generate new issues I think.

**Comment by plata** [comment]
Ok. Let's first get the other stuff done, then we check again how we handle the remaining (bigger) topics.

**Comment by madoar** [comment]
About Github tools:
There seem to be a few project management integrations. I'm not too sure how good they are.
For a list, take a look at https://github.com/marketplace.
What I believe to be interesting is https://github.com/marketplace/gemnasium when they support java.

**Comment by plata** [comment]
I think gemnasium is about dependencies in the software, right?

**Comment by madoar** [comment]
Yes, that's why I've tried to list it separately

**Comment by plata** [comment]
The only free ones there are ZenHub and Waffle.

**Comment by madoar** [comment]
I'm not sure if any of these tools provides the ability to link different issues together...

**Comment by plata** [comment]
from the ZenHub description: "visualize blockers with Issue dependencies"

**Comment by plata** [comment]
Waffle doesn't seem to add a lot more than GitHub projects.

**Comment by plata** [comment]
@madoar I think ZenHub is really what you want. E.g. for the several issues we have regarding generic engines, you would create one Epic which collects all the issues and structures their overall concept. But you can simply try it.

**Comment by jipiboily** [comment]
@madoar Gemnasium is currently working on Java support :) You can get early access here: https://gemnasium.com/java-support-soon/ in a few weeks.

**Comment by madoar** [comment]
I believe @qparis should take a look at this, to decide if we should give it a try.

**Comment by plata** [comment]
Did you try ZenHub yourself to see if it's any good?

**Comment by madoar** [comment]
No I don't have another project for which I need it currently and I don't think I have the required rights to add it to this repository.

**Comment by plata** [comment]
Can't you just create a dummy repo to test it?

**Comment by plata** [comment]
Outdated. We can discuss the open topics for alpha-2 in the team discussion.
